"""The data an edge streams up to the hub, for the Store & Forward demo.

The MQTT leg was already wired before this: Edge1's transmitter publishes tag
provider `edge`, tag path `MQTT Tags`, to the hub's broker as Sparkplug B, with
`enableStoreForwardByDefault` true behind an in-memory history store. What was
missing was anything that MOVES -- a static tag proves nothing about buffering.

So this creates a handful of tags under the transmitter's own path and walks them
once a second. Anything written here is published by Transmission automatically,
because it sits inside the path the transmitter is configured to watch.

Lives in each Site because EAM carries a Site's own resources to its edge as
part of the flattened `Edge` project. It is a NO-OP anywhere the `edge` provider
does not exist, which is how the same resource can sit harmlessly on the hub.

Jython 2.7 -- `except X, e`, not `as e`.
"""
import math

from java.lang import Throwable as JThrowable

PROVIDER = "edge"
FOLDER = "MQTT Tags/Demo"
LOG = "EdgeStream"
FAULT_TAG = "Fault"

# Name -> (base, amplitude, period seconds). Three different shapes so the trend
# after a buffered outage is obviously continuous rather than a flat line.
SIGNALS = [
    ("FlowRate", 120.0, 35.0, 60.0),
    ("Pressure", 4.2, 0.8, 25.0),
    ("Temperature", 68.0, 6.0, 180.0),
]

# The edge publishes its own address as a metric so the hub can tell its edge
# nodes apart. The Sparkplug edge node id is GENERATED by Transmission
# ("Edge Node e055db"), so it identifies the node but says nothing about which
# container it is -- and the Store & Forward page has to know that precisely,
# because breaking the uplink means banning that peer address at the broker.
# Letting each edge state its own address keeps this discovered rather than
# hard-coded, and survives an edge being rebuilt with a new node id.
ADDRESS_TAG = "Address"

# The theme this gateway is actually wearing, published as a tag.
#
# The theme itself is a project RESOURCE (demo_styles.CHOSEN_PACK) because only
# a resource travels over EAM -- but a resource is not readable from another
# gateway, so the hub used to report each edge's theme from its own record of
# what it last SENT. That is a promise, not an observation: it says nothing
# about whether the push landed, and it cannot notice a theme changed any other
# way. Publishing it as a tag makes it a fact the hub reads back.
#
# One tag serves BOTH roads, which is why it goes here rather than in anything
# transport-specific: the Gateway Network edge is mounted by the hub as [Edge1]
# so the hub reads it directly, and the MQTT edge's tags are published as
# Sparkplug metrics, so MQTT Engine mirrors it. Neither needed a new mechanism.
PACK_TAG = "Pack"


def _logger():
    return system.util.getLogger(LOG)


def _now_millis():
    from java.lang import System as JSystem
    return JSystem.currentTimeMillis()


def _own_address():
    """This container's address on the shared network.

    Whatever the broker sees as the peer address is what a ban has to name, and
    that is this container's own IP -- there is no NAT between the containers.
    """
    from java.net import InetAddress
    try:
        return str(InetAddress.getLocalHost().getHostAddress())
    except (Exception, JThrowable), e:
        _logger().warn("could not read own address: %s" % e)
        return ""


def _own_pack():
    """The theme committed on THIS gateway, or "?" if it cannot be read.

    Never raises. It is written every tick from a timer, and a timer that throws
    stops the data stream with it -- the signals share this tick.
    """
    try:
        import demo_styles
        return str(demo_styles.chosen_pack())
    except Exception, e:
        _logger().warn("cannot read the committed pack: %s" % e)
        return "?"


def available():
    """True only where the transmitter's tag provider exists -- i.e. on an edge."""
    try:
        return system.tag.exists("[%s]" % PROVIDER)
    except (Exception, JThrowable):
        return False


# Cirrus Link control tags. Transmission does not notice tags that appear after
# it has already published its DBIRTH -- the edge node's birth certificate lists
# the metrics, so a new folder needs a rebirth before the hub will ever see it.
REFRESH_TAGS = [
    "[MQTT Transmission]Transmission Control/Refresh",
    "[MQTT Transmission]Transmission Control/Rebirth",
]


def _diagnose():
    """Log what actually lives under the Transmission provider.

    The control-tag path is version-specific and guessing it costs a push cycle,
    so on the run that creates the tags we write down what is really there.
    """
    try:
        for node in system.tag.browse("[MQTT Transmission]").getResults():
            _logger().info("transmission root: %s" % node["fullPath"])
        for node in system.tag.browse(
                "[MQTT Transmission]Transmission Control").getResults():
            _logger().info("transmission control: %s" % node["fullPath"])
    except (Exception, JThrowable), e:
        _logger().warn("browse failed: %s" % e)


def _rebirth():
    """Ask Transmission to re-publish its birth certificate."""
    for path in REFRESH_TAGS:
        try:
            if system.tag.exists(path):
                system.tag.writeBlocking([path], [True])
                _logger().info("rebirth requested via %s" % path)
                return True
        except (Exception, JThrowable), e:
            _logger().warn("rebirth via %s failed: %s" % (path, e))
    _logger().warn("no Transmission refresh tag found -- see browse above")
    return False


# Set once per gateway script scope. A project scan resets it, which just means
# one extra rebirth per deploy -- harmless, and far better than a rebirth every
# second or none at all after the tags already exist.
_REBIRTHED = False


def ensure_tags():
    """Create the memory tags if absent, and rebirth once so Transmission
    publishes them.

    The rebirth cannot be tied to tag CREATION alone: the tags survive a restart
    while Transmission's birth certificate does not, and on any run where they
    already exist the hub would never be told about them.
    """
    global _REBIRTHED

    missing = [n for n in [s[0] for s in SIGNALS] + [ADDRESS_TAG, PACK_TAG, FAULT_TAG]
               if not system.tag.exists("[%s]%s/%s" % (PROVIDER, FOLDER, n))]
    if not missing:
        if not _REBIRTHED:
            _REBIRTHED = True
            _diagnose()
            _rebirth()
        return False

    tags = []
    for name, base, amp, period in SIGNALS:
        tags.append({
            "name": name,
            "tagType": "AtomicTag",
            "valueSource": "memory",
            "dataType": "Float8",
            "value": base,
        })
    tags.append({
        "name": ADDRESS_TAG,
        "tagType": "AtomicTag",
        "valueSource": "memory",
        "dataType": "String",
        "value": _own_address(),
    })
    tags.append({
        "name": PACK_TAG,
        "tagType": "AtomicTag",
        "valueSource": "memory",
        "dataType": "String",
        "value": _own_pack(),
    })
    # The Store & Forward demo's alarm: raised and cleared from the console
    # (sf_local.act), journaled here first and carried to the hub by this
    # edge's road -- Edge sync on the Gateway Network, Sparkplug on MQTT.
    tags.append({
        "name": FAULT_TAG,
        "tagType": "AtomicTag",
        "valueSource": "memory",
        "dataType": "Boolean",
        "value": False,
        "alarms": [{"name": "Line fault", "mode": "Equality", "setpointA": 1.0,
                    "priority": "High", "label": "Line fault"}],
    })
    # "i": tags that already exist are left alone, so an edge built before the
    # fault tag existed gains it without touching the others.
    system.tag.configure("[%s]%s" % (PROVIDER, FOLDER), tags, "i")
    _logger().info("created %d demo tags under %s" % (len(tags), FOLDER))
    _REBIRTHED = True
    _diagnose()
    _rebirth()
    return True


def _shape():
    """A phase shift and an amplitude factor unique to this edge.

    Both edges run the same script, so without this they trace the SAME curve
    and the trend on the hub draws one line with another hidden exactly beneath
    it -- which makes it impossible to see that only one of them lost its link.
    Derived from the container's own address so it needs no per-site config and
    two edges never collide.
    """
    try:
        last = int(_own_address().rsplit(".", 1)[-1])
    except (ValueError, IndexError):
        return 0.0, 1.0
    return (last % 7) * 8.5, 0.75 + (last % 3) * 0.2


# --- local history, for the edge that reaches the hub over the Gateway Network -
#
# That edge has no MQTT road, so its store-and-forward is Ignition's own: values
# are recorded by the edge's historian and forwarded to the hub's, carrying their
# original timestamps, whenever the link is there.
#
# NEITHER of the two resources involved is the one you would reach for, and both
# wrong guesses fail SILENTLY:
#
#   * An Edge gateway has exactly ONE historian and you do not create it. Its
#     name comes from the `ignition/edge-system-properties` singleton
#     (`historianName`, default "Edge Historian"), and EdgeHistorianCollection
#     builds that one from the property instead of reading the historian-provider
#     collection at all. A `historian-provider` resource created on an Edge lists
#     over the REST API reporting `enabled: true` and is never instantiated --
#     no start line in the log, no store on disk -- so every tag pointed at it
#     records nothing while looking correctly configured. That cost a day.
#
#   * Forwarding is NOT the provider's own `remoteSync` block. It is the
#     `ignition/edge-sync-settings` singleton: `remoteServerName`,
#     `remoteHistoryProviderName`, `remoteHistoryEnabled`. Writing it takes
#     effect immediately -- the historian restarts in place and logs
#     "Will synchronize data to remote historian '<X>' on server '<Y>'", which is
#     the line to confirm rather than the write's return code.
#
# Both are read here rather than hard-coded, which is what keeps this inherited
# resource a no-op everywhere it should be: the hub has neither file, and the
# MQTT edge has sync disabled, so only the Gateway Network edge historises.
EDGE_SYSTEM_PROPS = ("ignition", "edge-system-properties")
EDGE_SYNC_SETTINGS = ("ignition", "edge-sync-settings")
DEFAULT_HISTORIAN = "Edge Historian"

# How often ensure_history() re-checks that the demo tags still point at the
# historian. Cheap -- three getConfiguration calls -- against a timer that runs
# every second, and the thing it catches is an edge silently not recording.
HISTORY_RECHECK_MILLIS = 30000

_HISTORY_CHECKED = 0


def _config_resource(module, type_id):
    """A gateway config resource's config.json, or None where it does not exist.

    Read off disk because these are singletons with no scripting API: there is
    no system.* call that reports the edge's historian name or its sync
    settings, and configuring a tag against a historian that is not running
    succeeds silently, so guessing is indistinguishable from working.
    """
    import os
    import json
    from java.lang import System as JSystem

    for prop in ("ignition.installdir", "user.dir"):
        base = JSystem.getProperty(prop)
        if not base:
            continue
        path = os.path.join(base, "data", "config", "resources", "core",
                            module, type_id, "config.json")
        if not os.path.isfile(path):
            continue
        handle = open(path)
        try:
            return json.loads(handle.read())
        except (Exception, JThrowable), e:
            _logger().warn("could not read %s/%s: %s" % (module, type_id, e))
            return None
        finally:
            handle.close()
    return None


def history_target():
    """The historian to record to, or None where this gateway should not.

    None on the hub (neither resource exists) and on the MQTT edge (sync
    disabled), so the same inherited script does the right thing on all three.
    """
    sync = _config_resource(*EDGE_SYNC_SETTINGS)
    if not sync or not sync.get("remoteHistoryEnabled"):
        return None
    props = _config_resource(*EDGE_SYSTEM_PROPS) or {}
    return props.get("historianName") or DEFAULT_HISTORIAN


def ensure_history():
    """Point the demo tags at this edge's historian, if it forwards history.

    Re-applied rather than done once, for the same reason the hub re-applies its
    own: a tag rewritten by anything comes back with history off, and the edge is
    the side that would silently stop recording.
    """
    global _HISTORY_CHECKED
    if not available():
        return 0

    # RE-CHECK ON A CLOCK, NOT ONCE. This used to guard on a plain `_HISTORISED`
    # boolean, which made the docstring above a lie: the first pass set it, and
    # from then on a tag that lost its history setting was never repaired for the
    # life of the script module. It also failed in complete silence, because the
    # guard returns before either log line -- so an edge that had stopped
    # recording looked exactly like one that had never needed to start.
    #
    # That is not hypothetical. Found 05/08/2026 with 29 hours of history
    # missing: the tags had lost their setting, the timer called this every
    # second for a day, and the log said nothing at all either way. The hub's own
    # SFHistory timer had it right all along -- sweep on an interval and write
    # only what is missing.
    now = _now_millis()
    if _HISTORY_CHECKED and (now - _HISTORY_CHECKED) < HISTORY_RECHECK_MILLIS:
        return 0
    # The FIRST sweep of each script-module lifetime says what it decided, even
    # when it decides to do nothing. Every outcome here was silent before, so
    # "recording fine", "not a forwarding edge" and "cannot see its settings"
    # were indistinguishable from the log -- and one of those three is a broken
    # demonstration. One line per project scan is a fair price.
    first = not _HISTORY_CHECKED
    _HISTORY_CHECKED = now

    historian = history_target()
    if not historian:
        if first:
            _logger().info(
                "no history target -- this edge does not forward history "
                "(remoteHistoryEnabled off, or edge-sync-settings unreadable)")
        return 0

    configured = 0
    for name in [s[0] for s in SIGNALS]:
        path = "[%s]%s/%s" % (PROVIDER, FOLDER, name)
        try:
            # The PROVIDER has to be checked too, not just the flag. A tag left
            # pointing at a historian that no longer exists still reports
            # historyEnabled: true, so testing the flag alone treats a tag that
            # records nothing as already done.
            current = system.tag.getConfiguration(path, False)
            if (current and current[0].get("historyEnabled")
                    and str(current[0].get("historyProvider")) == historian):
                continue
            system.tag.configure("[%s]%s" % (PROVIDER, FOLDER),
                                 [{"name": name,
                                   "historyEnabled": True,
                                   "historyProvider": historian}], "m")
            configured += 1
        except (Exception, JThrowable), e:
            _logger().warn("could not historise %s: %s" % (path, e))
            return 0
    if configured:
        _logger().info("history enabled on %d tag(s) -> %s"
                       % (configured, historian))
    elif first:
        _logger().info("history already set on all %d tag(s) -> %s"
                       % (len(SIGNALS), historian))
    return configured


def tick(now_millis):
    """Walk every signal one step. Called by the EdgeDataStream timer."""
    paths, values = [], []
    phase, factor = _shape()
    seconds = now_millis / 1000.0 + phase
    for name, base, amp, period in SIGNALS:
        value = base + amp * factor * math.sin(2.0 * math.pi * seconds / period)
        paths.append("[%s]%s/%s" % (PROVIDER, FOLDER, name))
        values.append(round(value, 3))
    # Rewritten every tick rather than only at creation: a container restart can
    # come back on a different address, and Sparkplug publishes on change, so an
    # unchanged value costs nothing.
    paths.append("[%s]%s/%s" % (PROVIDER, FOLDER, ADDRESS_TAG))
    values.append(_own_address())
    paths.append("[%s]%s/%s" % (PROVIDER, FOLDER, PACK_TAG))
    values.append(_own_pack())
    system.tag.writeBlocking(paths, values)
    return len(paths)
