#!/bin/bash
# The two steps that need root. Run with:  sudo ./finish-setup.sh
#
#   1. Points the .test names at 127.0.0.1 so the browser can find the proxy.
#      Nginx Proxy Manager routes by hostname but does not do DNS.
#   2. Trusts the local CA so HTTPS shows a padlock instead of a warning.
#
# Works on macOS (work machine) and Linux (this VM). Both halves are
# idempotent -- re-running changes nothing.
#
# One caveat on Linux: Firefox and Chrome keep their OWN certificate stores and
# ignore the system one. This script imports into every NSS profile it can find
# for the invoking user (needs certutil, from libnss3-tools); if that tool is
# missing it says so and the system store still covers curl and most CLIs.
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "This needs root. Run: sudo $0" >&2
  exit 1
fi

CERT="$(cd "$(dirname "$0")" && pwd)/certs/rootCA.pem"
CA_NAME="work-dockers local CA"

# ------------------------------------------------------------- /etc/hosts --
# Delegated: scripts/hosts-setup.sh owns this now, derives the names from the
# stack manifests, and is what `wd bootstrap` runs. This script keeps only the
# CA-trust half, which genuinely differs per OS. (The hosts logic used to be
# triplicated, and this copy had the weakest matching -- a substring grep that
# a comment could satisfy.)
"$(cd "$(dirname "$0")/../.." && pwd)/scripts/hosts-setup.sh"

# ---------------------------------------------------------------- CA trust --
if [ ! -f "$CERT" ]; then
  echo "No CA at $CERT -- run ./create-certs.sh first." >&2
  exit 1
fi

case "$(uname -s)" in
  Darwin)
    echo "==> trusting the local CA in the System keychain"
    security add-trusted-cert -d -r trustRoot \
      -k /Library/Keychains/System.keychain "$CERT"
    ;;

  Linux)
    echo "==> trusting the local CA in the system store"
    install -m 644 "$CERT" /usr/local/share/ca-certificates/work-dockers-rootCA.crt
    update-ca-certificates >/dev/null

    # Browsers do not read the system store on Linux. Import into the NSS
    # databases of the user who ran sudo: Chrome/Chromium (~/.pki/nssdb) and
    # every Firefox profile, deb or snap.
    RUN_USER="${SUDO_USER:-root}"
    RUN_HOME="$(getent passwd "$RUN_USER" | cut -d: -f6)"
    if command -v certutil >/dev/null 2>&1; then
      # Compare FINGERPRINTS, never the nickname. The CA is machine-local and
      # regenerated by any from-scratch rebuild, and after a rotation the OLD
      # cert still sits in every profile under this nickname -- so a nickname
      # check says "already trusted", skips the import, and the browser goes on
      # warning about a CA this script just claimed to have handled. Found the
      # hard way after the 28/08/2026 rebuild.
      want_fp="$(openssl x509 -in "$CERT" -noout -fingerprint -sha256 | cut -d= -f2)"
      while IFS= read -r db; do
        profile="$(dirname "$db")"
        have_fp="$(sudo -u "$RUN_USER" certutil -d "sql:$profile" -L -n "$CA_NAME" -a 2>/dev/null \
                   | openssl x509 -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2 || true)"
        if [ -n "$have_fp" ] && [ "$have_fp" = "$want_fp" ]; then
          echo "    already trusted: $profile"
        else
          if [ -n "$have_fp" ]; then
            # A different cert under our nickname is the rotation case: drop it
            # or certutil -A quietly keeps both and Firefox trusts neither
            # consistently.
            sudo -u "$RUN_USER" certutil -d "sql:$profile" -D -n "$CA_NAME" 2>/dev/null || true
            echo "    replacing stale CA in: $profile"
          fi
          sudo -u "$RUN_USER" certutil -d "sql:$profile" -A -t "C,," -n "$CA_NAME" -i "$CERT"
          echo "    imported into : $profile"
        fi
      done < <(find "$RUN_HOME/.pki/nssdb" \
                    "$RUN_HOME/.mozilla/firefox" \
                    "$RUN_HOME/snap/firefox/common/.mozilla/firefox" \
                    -maxdepth 2 -name cert9.db 2>/dev/null)
    else
      echo "    certutil not found (apt install libnss3-tools) -- browsers will"
      echo "    still warn until you import $CERT manually:"
      echo "    Firefox: Settings > Privacy & Security > Certificates > Import,"
      echo "    tick 'Trust this CA to identify websites'."
    fi
    ;;

  *)
    echo "Unknown OS $(uname -s) -- trust $CERT manually." >&2
    ;;
esac

echo
echo "Done. Restart the browser, then try https://ignition.test"
