#!/usr/bin/env python3
"""Generate the SHARED left-rail components every demo tab embeds.

GENERATED FILES: views/RailHead, RailGroup, RailFact, RailButton, RailLink,
NotRunning and StripNode in GatewayAdmin. Edit this script and re-run it; hand
edits are overwritten. The `wd-node` class StripNode wears is in the project
stylesheet's hand-maintained half.

    python3 scripts/gen-rail-views.py && ./wd validate && ./wd deploy PROJECT=GatewayAdmin

WHY THEY ARE VIEWS RATHER THAN A PATTERN. Four demo tabs carry a rail and one
of the four (MQTT) is itself generated by scripts/gen-sparkplug-views.py. A
"pattern" copied into four places is four places to fix a wording or a height,
and the generated one would drift from the hand-built three the first time
either changed. An embedded view is the only form of sharing Perspective has
that a scan enforces.

THE HEIGHT RULE. Every rail piece whose content can wrap is embedded with
`useDefaultViewHeight: false` and has a root with NO `height: 100%` -- that
combination is what lets the box grow to two lines and collapse to nothing.
`height: 100%` on a content-sized embed resolves to `auto`, which for a box
whose children are all flex items is zero (docs/PERSPECTIVE-LAYOUT.md).

The data all of them render comes from demo_rail.rail(<demo id>) and the demo's
own module; nothing here decides a word.
"""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VIEWS = (REPO + '/ignition/projects/GatewayAdmin'
         '/com.inductiveautomation.perspective/views')
S = '{session.custom.style}'

RESOURCE = {
    "scope": "G", "version": 1, "restricted": False, "overridable": True,
    "files": ["view.json"],
    "attributes": {"lastModification": {"actor": "external",
                                        "timestamp": "1970-01-01T00:00:00Z"}},
}

# One rail, one width, on all four tabs. Fixed, never grown: spare width is the
# content's (Nigel, 21/09/2026), and a rail that widens with the window moves
# every measured list offset on the MQTT tab with it.
RAIL_WIDTH = 260

# Every rail row is one of these two heights, so four tabs' rails line up with
# each other and the whole column's height is arithmetic rather than a
# measurement. 640px of laptop is the constraint that sets them.
ROW = 22          # a fact
HEAD = 18         # a group heading: 10px capitals need no more, and the MQTT
                  # rail's 534px budget needs the 4px three times over
BTN = 30          # a button, a link, a dropdown


def expr(e):
    return {"binding": {"type": "expr", "config": {"expression": e}}}


def comp(type_, name, props=None, pos=None, pc=None, children=None,
         events=None, meta=None):
    c = {"type": type_, "meta": {"name": name}, "props": props or {}}
    if meta:
        c["meta"].update(meta)
    if pos is not None:
        c["position"] = pos
    if pc:
        c["propConfig"] = pc
    if children is not None:
        c["children"] = children
    if events:
        c["events"] = {"component": events}
    return c


def view(root, params=None, size=(RAIL_WIDTH, ROW), custom=None, pc=None):
    v = {"custom": custom or {}, "params": params or {},
         "props": {"defaultSize": {"width": size[0], "height": size[1]}},
         "root": root}
    conf = dict(pc or {})
    for name in (params or {}):
        conf["params.%s" % name] = {"paramDirection": "input"}
    if conf:
        v["propConfig"] = conf
    return v


def write(name, v):
    d = os.path.join(VIEWS, name)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, 'view.json'), 'w') as fh:
        json.dump(v, fh, indent=2, ensure_ascii=False, sort_keys=True)
        fh.write('\n')
    with open(os.path.join(d, 'resource.json'), 'w') as fh:
        json.dump(RESOURCE, fh, indent=2)
        fh.write('\n')


# --------------------------------------------------------------- RailGroup

def build_group():
    """STATUS / CONTROLS / GATEWAYS. The small-caps heading Redundancy's rail
    already used -- the visual reference Nigel pointed at."""
    root = comp("ia.display.label", "root",
                {"text": "STATUS",
                 "style": {"fontSize": "10px", "fontWeight": "600",
                           "letterSpacing": "0.08em", "lineHeight": 1.4,
                           "opacity": "0.7", "whiteSpace": "nowrap"}},
                None, {"props.text": expr("{view.params.text}")})
    return view(root, params={"text": ""}, size=(RAIL_WIDTH, HEAD))


# ---------------------------------------------------------------- RailHead

def build_head():
    """The demo's own name, and the one status badge.

    The badge's words are demo_control's, verbatim -- the same string the
    demo's card on the Demos tab shows. Two spellings of one state is how a
    reader ends up believing the page tracks two different things.
    """
    name = comp("ia.display.label", "name",
                {"text": "",
                 "style": {"fontSize": "11px", "fontWeight": "700",
                           "letterSpacing": "0.1em", "lineHeight": 1.4,
                           "whiteSpace": "nowrap"}},
                {"basis": "auto", "grow": 1, "shrink": 1},
                {"props.text": expr("{view.params.name}")})
    badge = comp("ia.display.label", "badge",
                 {"text": "", "style": {"fontSize": "10px", "lineHeight": 1.4,
                                        "padding": "0 8px",
                                        "whiteSpace": "nowrap"},
                  "tooltip": {"enabled": True}},
                 {"shrink": 0},
                 {"props.text": expr("{view.params.state}"),
                  "props.style.classes": expr(
                      "%s + '/status/' + {view.params.badge}" % S),
                  "meta.tooltip.text": expr("{view.params.tip}")},
                 meta={"tooltip": {"enabled": True, "text": ""}})
    root = comp("ia.container.flex", "root",
                {"direction": "row", "alignItems": "center",
                 "style": {"gap": "8px", "width": "100%"}},
                None, None, [name, badge])
    return view(root, params={"name": "", "state": "", "badge": "badge-neutral",
                              "tip": ""}, size=(RAIL_WIDTH, ROW))


# --------------------------------------------------------------- NotRunning

def build_not_running():
    """The one not-running banner, on all four tabs.

    SELF-COLLAPSING. `meta.visible: false` hides a component without
    collapsing its box (docs/PERSPECTIVE-LAYOUT.md) -- 40px of nothing at the
    top of every rail whose demo is running. `position.display` removes the
    flex child instead, and with the embed content-sized the view goes to
    zero with it, so no tab has to remember to hide this.
    """
    inner = comp("ia.display.label", "text",
                 {"text": "",
                  "style": {"borderRadius": "6px", "fontSize": "11px",
                            "fontWeight": "600", "lineHeight": 1.4,
                            "padding": "6px 9px", "whiteSpace": "normal"}},
                 {"shrink": 0},
                 {"props.text": expr("{view.params.text}"),
                  "props.style.classes": expr(
                      "%s + '/status/badge-warn'" % S),
                  "position.display": expr("{view.params.text} != ''")})
    root = comp("ia.container.flex", "root",
                {"direction": "column", "style": {"gap": "0px",
                                                  "width": "100%"}},
                None, None, [inner])
    return view(root, params={"text": ""}, size=(RAIL_WIDTH, 40))


# --------------------------------------------------------------- RailFact

def build_fact():
    """`label   value` -- the whole vocabulary of a rail fact. No sentences.

    The value carries a status badge only when the demo's module asks for one,
    so a fact that is merely a number is not dressed up as a state.
    """
    label = comp("ia.display.label", "label",
                 {"text": "", "style": {"fontSize": "11px", "lineHeight": 1.4,
                                        "whiteSpace": "nowrap"}},
                 {"basis": "auto", "grow": 1, "shrink": 0},
                 {"props.text": expr("{view.params.label}"),
                  "props.style.classes": expr("%s + '/text/muted'" % S)})
    plain = comp("ia.display.label", "value",
                 {"text": "",
                  "style": {"fontSize": "11px", "fontWeight": "600",
                            "minWidth": "0", "overflow": "hidden",
                            "lineHeight": 1.4, "textOverflow": "ellipsis",
                            "whiteSpace": "nowrap"}},
                 {"basis": "auto", "shrink": 1},
                 {"props.text": expr("{view.params.value}"),
                  "position.display": expr("{view.params.badge} = ''")})
    badged = comp("ia.display.label", "badged",
                  {"text": "", "style": {"fontSize": "10px", "lineHeight": 1.4,
                                         "padding": "0 8px",
                                         "whiteSpace": "nowrap"}},
                  {"shrink": 0},
                  {"props.text": expr("{view.params.value}"),
                   "props.style.classes": expr(
                       "%s + '/status/' + {view.params.badge}" % S),
                   "position.display": expr("{view.params.badge} != ''")})
    root = comp("ia.container.flex", "root",
                {"direction": "row", "alignItems": "center",
                 "justify": "space-between",
                 "style": {"gap": "8px", "minWidth": "0", "width": "100%"},
                 "tooltip": {"enabled": True}},
                None, {"props.tooltip.text": expr("{view.params.tip}")},
                [label, plain, badged])
    return view(root, params={"label": "", "value": "", "badge": "",
                              "tip": ""}, size=(RAIL_WIDTH, ROW))


# -------------------------------------------------------------- RailButton

def build_button():
    """One guarded rail button, full rail width, with its reason under it.

    THE BINDING SHAPE IS demo_action's, unchanged -- enabled on the in-flight
    latch AND this button's own `can.ok`, the label from the server so a
    countdown is computed once, the refusal as the tooltip, and the note line
    beside the button rather than at the foot of the page. What is new is that
    it is written down ONCE instead of per button per tab: the four rails held
    eighteen copies of these six bindings between them.

    `action` is a key into demo_rail.ACTIONS, not a script. A view cannot be
    handed a handler as a parameter, and the alternative -- a copy of this
    component per button so each could carry its own script -- is the thing
    this view exists to stop.
    """
    acting = "{session.custom.acting}"
    key = "{view.params.key}"
    live = "%s = '' && {view.params.can.ok}" % acting
    note = ("if(%s = %s, {session.custom.actingWhat}, "
            "if({view.params.can.note} != '', {view.params.can.note}, "
            "if({session.custom.actKey} = %s, {session.custom.actNote}, '')))"
            % (acting, key, key))
    btn = comp(
        "ia.input.button", "btn",
        {"text": "", "align": "center", "justify": "flex-start",
         "image": {"height": 16, "width": 16, "position": "left",
                   "source": "", "style": {"classes": ""},
                   "icon": {"color": "", "path": ""}},
         "style": {"fontSize": "12px", "gap": "8px", "height": "%dpx" % BTN,
                   "minHeight": "%dpx" % BTN, "padding": "0 10px",
                   "whiteSpace": "nowrap", "width": "100%"},
         "tooltip": {"enabled": True}},
        {"shrink": 0},
        {"props.enabled": expr(live),
         "props.image.icon.path": expr("{view.params.icon}"),
         "props.image.width": expr("if({view.params.icon} = '', 0, 16)"),
         "props.style.classes": expr(
             "%s + '/buttons/' + {view.params.kind}" % S),
         "props.style.cursor": expr(
             "if(%s, 'pointer', 'not-allowed')" % live),
         "props.style.opacity": expr("if(%s, 1, 0.45)" % live),
         # Armed (the first click of a two-click action): the label itself
         # says what the second click does, not only the note under it.
         "props.text": expr("if(%s = %s, {view.params.can.busy}, "
                            "if({session.custom.armKey} = %s, "
                            "'Click again to confirm', "
                            "{view.params.can.label}))" % (acting, key, key)),
         "meta.tooltip.text": expr("{view.params.can.why}")},
        events={"onActionPerformed": {
            "type": "script", "scope": "G",
            "config": {"script": "\timport demo_rail\n"
                                 "\tdemo_rail.fire(self.session, "
                                 "self.view.params.action)\n"}}},
        meta={"tooltip": {"enabled": True, "text": ""}})
    # `quiet` buttons never grow a note: the MQTT rail puts a scenario's
    # buttons two to a line, where a refusal wrapping under a 114px button
    # would push the rail past a 640px laptop. Their block shows ONE answer
    # line at its foot instead (gen-sparkplug-views.ctl_note).
    why = comp("ia.display.label", "note",
               {"text": "", "style": {"fontSize": "10px", "lineHeight": 1.35,
                                      "whiteSpace": "normal"}},
               {"shrink": 0},
               {"props.text": expr(note),
                "props.style.classes": expr("%s + '/text/muted'" % S),
                "position.display": expr("!{view.params.quiet} && %s != ''"
                                         % note)})
    root = comp("ia.container.flex", "root",
                {"direction": "column",
                 "style": {"gap": "2px", "width": "100%"}},
                None, None, [btn, why])
    return view(root, params={"key": "", "action": "", "icon": "",
                              "kind": "chip", "quiet": False,
                              "can": {"ok": False, "why": "", "label": "",
                                      "busy": "", "note": ""}},
                size=(RAIL_WIDTH, BTN))


# ---------------------------------------------------------------- RailLink

def build_link():
    """One gateway this demo needs, as a real anchor.

    An `ia.navigation.link`, not a button: a stopped stack's chip must still be
    clickable, because the proxy's down page names the demo that starts it, and
    a link has no `enabled` property to get that wrong (demo_control._links).

    Narrower than OpenLink and laid out three to a line in a 260px rail rather
    than one per line: three gateways one per line costs 90px of a 640px
    laptop, and these are the least-pressed thing on the rail.
    """
    link = comp("ia.navigation.link", "open",
                {"target": "blank", "rel": "noopener",
                 "style": {"alignItems": "center", "display": "flex",
                           "fontSize": "11px", "height": "%dpx" % (BTN - 4),
                           "justifyContent": "center",
                           "minHeight": "%dpx" % (BTN - 4), "padding": "0 4px",
                           "textDecoration": "none", "whiteSpace": "nowrap",
                           "width": "100%"}},
                {"basis": "0px", "grow": 1, "shrink": 1},
                {"props.style.classes": expr("%s + '/buttons/chip'" % S),
                 "props.text": expr("{view.params.link.label} + ' ↗'"),
                 "props.url": expr("{view.params.link.url}")})
    root = comp("ia.container.flex", "root",
                {"direction": "row", "alignItems": "stretch",
                 "style": {"gap": "0px", "width": "100%"}},
                None, None, [link])
    return view(root, params={"link": {}}, size=(118, BTN - 4))


# --------------------------------------------------------------- StripNode

def build_strip_node():
    """One box on a tab's architecture strip: a name, a state, one line.

    The MQTT strip (generated) and the Store & Forward strip (hand-built) both
    draw their gateways with this, so an edge on one tab and an edge on the
    other are the same shape in the same words. A box with no state -- the
    broker, which has no health of its own to report -- drops the badge rather
    than showing an empty pill.

    `height: 100%` IS right here, unlike the rail pieces: a strip node's box is
    decided by the strip that places it (a flex child with a basis), not by its
    own content, which is the case docs/PERSPECTIVE-LAYOUT.md says it holds.
    """
    name = comp("ia.display.label", "name",
                {"text": "", "style": {"fontSize": "13px", "fontWeight": "600",
                                       "lineHeight": 1.35, "minWidth": "0",
                                       "overflow": "hidden",
                                       "textOverflow": "ellipsis",
                                       "whiteSpace": "nowrap"}},
                {"basis": "auto", "grow": 1, "shrink": 1},
                {"props.text": expr("{view.params.name}")})
    badge = comp("ia.display.label", "state",
                 {"text": "", "style": {"fontSize": "10px", "lineHeight": 1.4,
                                        "padding": "0 8px",
                                        "whiteSpace": "nowrap"}},
                 {"shrink": 0},
                 {"props.text": expr("{view.params.state}"),
                  "props.style.classes": expr(
                      "%s + '/status/' + {view.params.badge}" % S),
                  "position.display": expr("{view.params.state} != ''")})
    line = comp("ia.display.label", "line",
                {"text": "", "style": {"fontSize": "11px", "lineHeight": 1.35,
                                       "minWidth": "0", "overflow": "hidden",
                                       "textOverflow": "ellipsis",
                                       "whiteSpace": "nowrap"}},
                {"shrink": 0},
                {"props.text": expr("{view.params.line}"),
                 "props.style.classes": expr("%s + '/text/muted'" % S),
                 "position.display": expr("{view.params.line} != ''")})
    top = comp("ia.container.flex", "top",
               {"direction": "row", "alignItems": "center",
                "style": {"gap": "8px", "minWidth": "0"}},
               {"shrink": 0}, None, [name, badge])
    root = comp("ia.container.flex", "root",
                {"direction": "column", "justify": "center",
                 "style": {"classes": "wd-node", "gap": "2px",
                           "height": "100%", "minWidth": "0",
                           "overflow": "hidden", "width": "100%"},
                 "tooltip": {"enabled": True}},
                None, {"props.tooltip.text": expr("{view.params.tip}")},
                [top, line])
    return view(root, params={"name": "", "state": "", "badge": "badge-neutral",
                              "line": "", "tip": ""}, size=(300, 44))


def main():
    out = {
        'StripNode': build_strip_node(),
        'RailGroup': build_group(),
        'RailHead': build_head(),
        'NotRunning': build_not_running(),
        'RailFact': build_fact(),
        'RailButton': build_button(),
        'RailLink': build_link(),
    }
    for name, v in out.items():
        write(name, v)
    print('wrote %d shared rail views' % len(out))


if __name__ == '__main__':
    main()
