#!/usr/bin/env bash
#
# Put the demo estate's UI logins into the HUB GATEWAY'S OWN SECRET STORE, so a
# Perspective script can read one without the password being written into a
# project resource, a binding or a view.
#
#   scripts/ign-secrets.sh            install/refresh the provider and secrets
#   scripts/ign-secrets.sh --list     what is stored (NAMES only, never values)
#
# WHY THE GATEWAY NEEDS ITS OWN COPY AT ALL
#
# The console's Open buttons sign you in to the four Ignition gateways without
# anything reaching the browser -- that happens server-side in the control
# plane, which reads .gateways.env (see control/autologin.py). Those
# credentials are deliberately NOT duplicated here.
#
# The other UIs are the problem this solves. Nginx Proxy Manager has its own
# local login and no way to be signed in from outside, so the console can only
# open it -- and then somebody has to know the password. The one thing that must not happen is that password living in a
# view, because views are committed to git and pushed to the edges by EAM.
#
# Ignition 8.3 has a secret store for exactly this. `system.secrets` reads it
# from a gateway script; nothing else can.
#
# WHY THE `file` PROVIDER RATHER THAN `internal`
#
# Three provider types exist: file, internal and remote. `internal` would keep
# the values in the gateway's own config, which means they land in a .gwbk and
# travel with it -- and a .gwbk already carries enough that it must not move
# between machines. `file` keeps them as files this script owns, so the source
# of truth stays .secrets.env, one place, regenerated by `make env`.
#
# Each entry is CLEARTEXT because the file is the secret: 0600, inside the
# gateway's own data volume, readable only by the gateway user. CIPHERTEXT
# would mean encrypting with the gateway's key, which is in the same volume.
#
# NOTHING HERE PRINTS A VALUE. Values move from .secrets.env into the container
# through a pipe; they are never an argument (argv is world-readable) and never
# echoed. --list prints names.
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

GATEWAY_CONTAINER=ignition
STANZA=local
PROVIDER=wd
# Inside the gateway's own data volume, beside the config it already protects.
SECRET_DIR=/usr/local/bin/ignition/data/wd-secrets

# secret name : the stack whose .env holds it : the variable.
#
# Read from stacks/<stack>/.env rather than .secrets.env, because that file
# only holds the GENERATED values. A username like `admin` is a plain value in
# the committed .env.example and never reaches .secrets.env, so looking there
# would report every username missing.
#
# Usernames are stored beside the passwords even though they are not secret.
# The alternative is a second table of usernames in the Perspective library,
# which is the copy that goes stale the day somebody changes an admin email --
# and it goes stale silently, because a wrong username and a wrong password
# fail identically.
#
# A stack of `-` means the root .secrets.env itself: wd-control-token is the
# token wd-control's MQTT cut demands (control/mqttcut.py), and no stack's .env
# carries it.
SECRETS="
npm-username:npm:INITIAL_ADMIN_EMAIL
npm-password:npm:INITIAL_ADMIN_PASSWORD
wd-control-token:-:WD_CONTROL_TOKEN
"
# Names this script used to install and no longer does: dropped from the
# provider and deleted from the gateway, so nothing reads a stale login.
RETIRED="emqx-dashboard-username emqx-dashboard-password"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_ENV="$here/.secrets.env"

if [ "${1:-}" = "--list" ]; then
  node "$here/scripts/ign-gw.js" api --gateway "$STANZA" \
    --path "/data/api/v1/resources/list/ignition/secret-provider" 2>/dev/null \
    | sed -n 's/.*"name":"\([^"]*\)".*/provider: \1/p' | head -5
  docker exec "$GATEWAY_CONTAINER" sh -c "ls -1 $SECRET_DIR 2>/dev/null" \
    | sed 's/^/  secret: /' || echo "  (no secrets installed)"
  exit 0
fi

[ -f "$SECRETS_ENV" ] || { echo "no .secrets.env -- run: make env" >&2; exit 1; }

docker ps --format '{{.Names}}' | grep -qx "$GATEWAY_CONTAINER" \
  || { echo "the hub gateway is not running -- make core" >&2; exit 1; }

# --- 1. the files ------------------------------------------------------------
# On the backup half too when it runs: the provider RESOURCE reaches it by
# redundancy sync, but these files live in each half's own volume, and the
# backup is the gateway that answers after a failover.
HALVES="$GATEWAY_CONTAINER"
docker ps --format '{{.Names}}' | grep -qx ignition-backup && HALVES="$HALVES ignition-backup"
for half in $HALVES; do
  docker exec "$half" sh -c "mkdir -p $SECRET_DIR && chmod 700 $SECRET_DIR"
  for name in $RETIRED; do docker exec "$half" rm -f "$SECRET_DIR/$name"; done
done

installed=0
missing=""
for entry in $SECRETS; do
  name="${entry%%:*}"; rest="${entry#*:}"
  stack="${rest%%:*}"; var="${rest##*:}"
  env_file="$here/stacks/$stack/.env"
  [ "$stack" = "-" ] && env_file="$SECRETS_ENV"
  # Into a variable, used, and gone. Never an argument, never echoed.
  value=""
  [ -f "$env_file" ] && value="$(sed -n "s/^$var=//p" "$env_file" | head -1)"
  if [ -z "$value" ]; then
    missing="$missing $stack/$var"
    continue
  fi
  # printf, not echo: the value may begin with a dash, and echo would read it
  # as an option on some shells. No trailing newline -- the provider reads the
  # whole file as the secret, so a newline would become part of the password
  # and every login would fail with a correct-looking value.
  for half in $HALVES; do
    printf '%s' "$value" \
      | docker exec -i "$half" sh -c "cat > $SECRET_DIR/$name"
  done
  unset value
  installed=$((installed + 1))
done

for half in $HALVES; do
  docker exec "$half" sh -c \
    "chmod 600 $SECRET_DIR/* 2>/dev/null; chown -R \$(id -u):\$(id -g) $SECRET_DIR 2>/dev/null || true"
done

printf 'secrets          %d written to %s\n' "$installed" "$SECRET_DIR"
[ -z "$missing" ] || printf 'secrets          MISSING from .secrets.env:%s\n' "$missing"

# --- 2. the provider ---------------------------------------------------------
# Extension-point resource: profile.type names the type, settings carries its
# config. `files` is a MAP keyed by the secret name (FileSecretProviderConfig
# -> propertyName), each entry {description, filePath, fileType}.
work="$(mktemp -d)"; trap 'rm -rf "$work"' EXIT

# The signature is an optimistic lock, and an UPDATE is refused without it --
# "Missing 'signature' parameter", which reads as a malformed body rather than
# as a resource that already exists. Absent on the first install, which is what
# makes the POST the right verb then.
node "$here/scripts/ign-gw.js" api --gateway "$STANZA" \
  --path "/data/api/v1/resources/list/ignition/secret-provider" \
  > "$work/existing.json" 2>/dev/null || true
SIGNATURE="$(PROVIDER="$PROVIDER" python3 - "$work/existing.json" <<'SIG'
import json, os, sys
try:
    raw = open(sys.argv[1]).read()
    doc = json.loads(raw[raw.index("{"):])
except Exception:
    raise SystemExit
for item in doc.get("items", []):
    if item.get("name") == os.environ["PROVIDER"]:
        print(item.get("signature", ""))
SIG
)"

SECRETS="$SECRETS" RETIRED="$RETIRED" SECRET_DIR="$SECRET_DIR" PROVIDER="$PROVIDER" \
  SIGNATURE="$SIGNATURE" EXISTING="$work/existing.json" python3 - "$work/provider.json" <<'PY'
import json, os, sys

# Start from what the provider ALREADY lists and overwrite only this script's
# names. Other scripts register secrets in the same provider --
# scripts/sparkplug-setup.sh adds the Sparkplug demo's action token -- and
# rebuilding the map from the list above alone silently dropped them: the file
# stays on disk, the provider stops naming it, and system.secrets answers "not
# found" to a script that worked the day before. Bootstrap runs this AFTER the
# Sparkplug step, so a wholesale rewrite would have broken that demo on every
# fresh build.
files = {}
try:
    raw = open(os.environ["EXISTING"]).read()
    for item in json.loads(raw[raw.index("{"):]).get("items", []):
        if item.get("name") == os.environ["PROVIDER"]:
            settings = (item.get("config") or {}).get("settings") or {}
            files = dict(settings.get("files") or {})
except Exception:
    files = {}
for name in os.environ.get("RETIRED", "").split():
    files.pop(name, None)
for entry in os.environ["SECRETS"].split():
    name = entry.split(":", 1)[0]
    files[name] = {
        "description": "installed by scripts/ign-secrets.sh from .secrets.env",
        "filePath": os.environ["SECRET_DIR"] + "/" + name,
        "fileType": "CLEARTEXT",
    }

body = {
    "name": os.environ["PROVIDER"],
    "collection": "core",
    "enabled": True,
    "description": "Logins for the estate's non-Ignition UIs. Files under the "
                   "gateway's data volume; source of truth is .secrets.env.",
    "config": {"profile": {"type": "file"}, "settings": {"files": files}},
}
if os.environ.get("SIGNATURE"):
    body["signature"] = os.environ["SIGNATURE"]
open(sys.argv[1], "w").write(json.dumps([body]))
PY

if [ -n "$SIGNATURE" ]; then METHOD=PUT; VERB=updated; else METHOD=POST; VERB=installed; fi
if node "$here/scripts/ign-gw.js" api --gateway "$STANZA" \
     --method "$METHOD" --path /data/api/v1/resources/ignition/secret-provider \
     --body-file "$work/provider.json" >"$work/out" 2>&1; then
  printf 'provider         %s %s\n' "$PROVIDER" "$VERB"
else
  printf 'provider         %s FAILED\n  %s\n' "$METHOD" "$(head -c 300 "$work/out")"
  exit 1
fi

# --- 3. prove it, from the gateway's side ------------------------------------
# Reading it back through the API says the RESOURCE exists. It does not say the
# gateway can actually open the files -- wrong ownership inside the container
# would leave every read failing at the moment somebody clicks. So ask for the
# names the provider can see.
node "$here/scripts/ign-gw.js" api --gateway "$STANZA" \
  --path "/data/api/v1/resources/list/ignition/secret-provider" 2>/dev/null \
  | grep -q "\"$PROVIDER\"" \
  && printf 'verified         provider %s is registered\n' "$PROVIDER" \
  || printf 'verified         WARNING: %s not in the provider list\n' "$PROVIDER"
