#!/usr/bin/env node
// Drive an Ignition 8.3 gateway's configuration UI headlessly.
//
// Gateway Network pairing, EAM controller/agent setup, MQTT server config and the
// third-party module certificate wizard are all UI-only -- none of it is file-based
// and the gateway API rejects the mutations (POST /data/api/v1/trial returns 403
// even from an authenticated session where GET returns 200). So drive the browser,
// the same way scan.js does for project scans.
//
//   node ign-gw.js <command> --gateway <name> [options]
//
// Commands:
//   explore   --path <url-path>     log in, go there, dump controls + screenshot
//                --click "A > B"     walk the nav by control text first
//   gan-connect --host H --port P    create an outgoing Gateway Network connection
//   gan-approve                      approve every pending incoming connection
//   module-install --file X.modl   upload + accept cert/EULA + install, live
//   commission                      complete the module certificate wizard at /welcome
//   trial-reset                     reset the 2-hour Perspective trial
//   backup    --out <file>          download a gateway backup (.gwbk)
//   db-create --name N --url U --username U   create a database connection (DB_PASSWORD in env)
//
// Credentials come from the shared 0600 file keyed by gateway name (local,
// local-edge1, local-edge2) -- never from argv, which every process can read.
// Same file and format as the toolkit's scan skill.
//
// Env: SHOT_DIR (screenshots), TIMEOUT_MS (per step, default 20000), HEADFUL=1.

const fs = require('fs');
const path = require('path');

// Inside the toolbox image playwright is installed globally and NODE_PATH points
// at it, so the bare require is the answer and the rest of this list never runs.
// The remaining candidates are for running this natively on the machine it was
// written on; they are a convenience, not a dependency -- `./wd` needs none of
// them. Nothing here may be a hard-coded absolute path that only exists on one
// person's laptop, which is what this used to be.
function loadPlaywright() {
  const candidates = [
    null,
    process.env.PLAYWRIGHT_HOME && path.join(process.env.PLAYWRIGHT_HOME, 'node_modules', 'playwright'),
    path.join(__dirname, '..', 'node_modules', 'playwright'),
  ].filter(c => c !== undefined);
  for (const c of candidates) {
    try { return c ? require(c) : require('playwright'); } catch (e) { /* next */ }
  }
  console.error('ign-gw: playwright not found.');
  console.error('  The supported way to run this is through the toolbox, which has it:');
  console.error('    ./wd -- node scripts/ign-gw.js ...        (or wd.cmd on Windows)');
  console.error('  To run natively instead: npm i playwright && npx playwright install chromium');
  process.exit(2);
}

function arg(name, dflt) {
  const i = process.argv.indexOf('--' + name);
  return i > -1 ? process.argv[i + 1] : dflt;
}
function die(msg) { console.error('ign-gw: ' + msg); process.exit(2); }

// The credentials live IN THE REPO, generated by make-env.sh from the same
// .secrets.env every stack draws on. It used to be a machine-wide file outside
// the repo, which is the sort of dependency that is invisible until someone
// clones this and every script dies at the first API call.
const CREDS = arg('creds')
  || process.env.IGNITION_SCAN_CREDS
  || path.join(__dirname, '..', '.gateways.env');
const NAME = arg('gateway', 'local');
const CMD = process.argv[2];
const STEP = parseInt(process.env.TIMEOUT_MS || '20000', 10);
const SHOT_DIR = process.env.SHOT_DIR || '/tmp';

// page.evaluate() has no `timeout` option of its own -- unlike goto/click/fill,
// it just awaits whatever promise the page function returns, forever. Every
// fetch() this file issues FROM INSIDE THE PAGE therefore carries its own
// AbortSignal.timeout(FETCH_TIMEOUT_MS); without it, a gateway that accepts the
// TCP connection and then never answers -- a network partition mid-failover is
// exactly how this surfaced -- hangs the whole Node process on one GET. Found
// 18/09/2026: a backup-trial swap command stuck ~1h this way, the master left Active
// the entire time because the poll checking whether the backup had taken over
// never returned. Node's own global fetch() (used by the trial-reset and
// commission pollers below, outside any page) has the identical gap and gets
// the identical fix.
const FETCH_TIMEOUT_MS = parseInt(process.env.FETCH_TIMEOUT_MS || '10000', 10);

// Turn whatever comes back out of a timed-out page.evaluate() -- a real
// AbortSignal timeout, or any other rejection -- into one plain line naming
// THIS gateway and the step that failed, instead of Chromium's bare "signal
// timed out" with no indication of which of the three gateways or which call.
// `step` carries its own timeout budget in its text where that is useful --
// this does not guess at a duration, because the different call sites below
// share this helper but do not share ONE timeout value (FETCH_TIMEOUT_MS for
// a fetch(), STEP for a Playwright action), and a made-up number would be
// wrong as often as not.
function describeFailure(step, e) {
  const msg = ((e && e.message) || String(e)).split('\n')[0];
  return new Error(`${NAME}: ${step} -- ${msg}`);
}

if (!CMD || CMD.startsWith('--')) die('usage: ign-gw.js <explore|commission|trial-reset|backup|api> --gateway <name>');
if (!fs.existsSync(CREDS)) {
  die(`credentials file not found: ${CREDS}\n`
    + '  It is generated, not authored. Build it with:  ./wd env');
}

const kv = {};
for (const line of fs.readFileSync(CREDS, 'utf8').split('\n')) {
  const i = line.indexOf('=');
  if (i > 0 && !line.trim().startsWith('#')) kv[line.slice(0, i).trim()] = line.slice(i + 1).trim();
}
// Each gateway is listed twice: `.url` addresses it by CONTAINER NAME on the
// backbone network, `.hosturl` by the host port this machine happens to publish
// it on. Inside the toolbox only the first works -- `localhost` there is the
// toolbox itself. Outside it, only the second does.
//
// Container-name addressing is what makes the scripts identical everywhere: the
// hub is `http://ignition:8088` whether the host mapped it to 8088, 8090 or
// nothing at all. Host ports differ per machine and exist for the browser.
//
// The fallback chain ends at `.url` so a credentials file written before this
// distinction existed still works.
const IN_TOOLBOX = process.env.WD_TOOLBOX === '1';
const URL = ((IN_TOOLBOX ? kv[`${NAME}.url`]
                         : (kv[`${NAME}.hosturl`] || kv[`${NAME}.url`])) || '')
  .replace(/\/+$/, '');
const USER = kv[`${NAME}.user`];
const PASS = kv[`${NAME}.password`];
if (!URL || !USER || !PASS) {
  const names = [...new Set(Object.keys(kv).map(k => k.split('.')[0]))].join(', ');
  die(`no credentials for "${NAME}" in ${CREDS}. Configured: ${names}`);
}

// --- credential hygiene -----------------------------------------------------
//
// Nothing in this file may print a password, and "just don't log it" is not
// enough: Playwright puts the fill() VALUE into its timeout error text, so a
// password field that renders slowly dumps the credential to the terminal
// without any code here asking it to. That has happened.
//
// So the guard is at the exit, not the call sites: every console.log and
// console.error is filtered. Any future code path that stringifies an error, a
// page URL or a form value is covered by construction.
// The password only. Scrubbing the username too was tried and is worse than
// useless: it is "admin" here, so every legitimate mention of the logged-in user
// in a button label or a log line came out as <redacted> and hid real output.
// A username is not a credential.
const SECRETS = [PASS].filter(s => s && s.length > 3);

function scrub(x) {
  let s = typeof x === 'string' ? x : require('util').inspect(x, { depth: 4 });
  for (const secret of SECRETS) s = s.split(secret).join('<redacted>');
  // The login flow's federate callback carries a one-time code and a JWT in its
  // query string, and those end up in hrefs and traced URLs.
  return s.replace(/([?&](code|state|token|jwt)=)[^&\s"']*/gi, '$1<redacted>');
}

for (const stream of ['log', 'error', 'warn']) {
  const orig = console[stream].bind(console);
  console[stream] = (...args) => orig(...args.map(scrub));
}

// Playwright's own error text is the leak vector, so never let it out: wait for
// the field ourselves and replace the message entirely.
async function safeFill(pg, sel, value, label) {
  const f = pg.locator(sel).first();
  try {
    await f.waitFor({ state: 'visible', timeout: STEP });
    await f.fill(value, { timeout: STEP });
  } catch (e) {
    throw new Error(`could not fill the ${label} field -- it never became visible`);
  }
}

// Issue an authenticated call against the gateway's REST API from inside the
// page, so it carries the session cookie. 8.3 authenticates the API with that
// cookie -- HTTP Basic from curl gets 401 -- which is why every one of these
// has to go through the browser.
//
// Writes additionally need X-CSRF-Token, fetched per call from
// GET /data/app/session. Without it 8.3 answers 403 on a fully authenticated
// session, and that 403 reads exactly like a permissions problem.
async function api(pg, method, path, body, raw = false) {
  let res;
  try {
    res = await pg.evaluate(async ([method, path, body, raw, timeoutMs]) => {
      const headers = { Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest' };
      if (method !== 'GET') {
        const s = await fetch('/data/app/session',
          { credentials: 'same-origin', signal: AbortSignal.timeout(timeoutMs) });
        const token = (await s.json()).csrfToken;
        if (!token) throw new Error('no csrfToken on /data/app/session');
        headers['X-CSRF-Token'] = token;
      }
      // raw === true means `body` is already a string to send verbatim (a
      // certificate PEM, for instance). The datafile endpoints take file bytes,
      // not JSON, and JSON-encoding them silently corrupts the upload.
      if (body !== null) {
        headers['Content-Type'] = raw ? 'application/octet-stream' : 'application/json';
      }
      const r = await fetch(path, {
        method,
        credentials: 'same-origin',
        headers,
        body: body === null ? undefined : (raw ? body : JSON.stringify(body)),
        signal: AbortSignal.timeout(timeoutMs),
      });
      const text = await r.text();
      let json = null;
      try { json = JSON.parse(text); } catch (_) { /* html error page */ }
      return { status: r.status, json, text };
    }, [method, path, body === undefined ? null : body, raw, FETCH_TIMEOUT_MS]);
  } catch (e) {
    throw describeFailure(`${method} ${path} (${FETCH_TIMEOUT_MS}ms budget)`, e);
  }

  if (res.status >= 400) {
    // Truncate only in the error message; callers get the whole body.
    throw new Error(`${NAME}: ${method} ${path} -> ${res.status} ${res.text.slice(0, 400)}`);
  }
  return res;
}

const { chromium } = loadPlaywright();

// Login, following the selectors proven by the toolbox's gateway_login.yaml
// playbook in the ignition-toolbox library (gateway/gateway_login.yaml) rather than
// anything invented here.
//
// Two things that cost time when guessed:
//   - It is a TWO-page flow, and each page is advanced by clicking a CONTINUE
//     button. Pressing Enter appears to work on some gateways and silently does
//     nothing on others.
//   - The login control must be matched as an ANCHOR (or by href), because the
//     trial banner carries a "Log In to Reset" BUTTON that a bare text match
//     hits instead -- after which the session stays anonymous and every later
//     step fails as if it were a permissions problem.
// A gateway commissioned from an empty volume opens its home page behind an
// "Enable Quick Start" modal, and the modal's overlay swallows the click on the
// Log In anchor. Playwright then reports `locator.click: Timeout` against a page
// whose dump plainly lists a "Log In" link -- which reads as a bad selector and
// is not one. Nothing else in this file ever sees it, because it only appears
// before someone has answered it once; on a fresh machine EVERY gateway has it,
// so bootstrap hits it four times in a row.
//
// "No thanks" rather than "Yes": Quick Start installs a sample project, a device
// simulator and its own tags, none of which belong in this stack, and on the
// redundant backup they would be synced away by the master a moment later
// anyway.
async function dismissQuickStart(pg) {
  const no = pg.locator("button:has-text('No thanks')").first();
  try {
    await no.waitFor({ state: 'visible', timeout: 3000 });
    await no.click({ timeout: STEP });
    await pg.waitForTimeout(750);
  } catch (e) { /* not a fresh gateway -- the usual case */ }
}

async function login(pg) {
  await pg.goto(`${URL}/web/home`, { waitUntil: 'domcontentloaded', timeout: 40000 });
  await dismissQuickStart(pg);

  // The gateway home is a SPA: domcontentloaded fires long before the nav and
  // the trial banner exist, and `networkidle` never fires at all because it
  // polls. So settle explicitly -- without this the login control is simply not
  // there yet and the run dies with "no login control found" on a page that
  // visibly has one.
  await pg.locator("a:has-text('Log In'), button:has-text('Log In'), a[href*='login']")
    .first().waitFor({ state: 'visible', timeout: 15000 })
    .catch(() => {});   // absent is legitimate when already authenticated

  // "already logged in" must be decided by a POSITIVE signal. Treating "no login
  // control found" as authenticated is how an anonymous session sailed through
  // and every later step failed as if it were a permissions problem.
  if (await isLoggedIn(pg)) return;

  const link = pg.locator(
    "a.login-link, a[href*='login'], a:has-text('Log In'), button:has-text('Log In')").first();
  if (await link.count() === 0) throw new Error('no login control found on /web/home');
  await link.click({ timeout: STEP });

  const userSel = "input[name='j_username'], input[name='username'], input[type='text']";
  await safeFill(pg, userSel, USER, 'username');
  await clickContinue(pg);

  const passSel = "input[name='j_password'], input[name='password'], input[type='password']";
  await safeFill(pg, passSel, PASS, 'password');
  await clickContinue(pg);

  await pg.waitForLoadState('domcontentloaded', { timeout: STEP }).catch(() => {});
  await pg.waitForTimeout(2500);

  if (!(await isLoggedIn(pg))) {
    throw new Error('login did not take -- still anonymous after submitting credentials');
  }
}

// Ask the gateway, don't read the page. Every DOM signal here is unreliable:
// the trial banner renders LATE, so checking for its "Log In to Reset" button
// right after load reports "already authenticated" and skips the login
// entirely -- which is what made the edge gateways silently stay anonymous.
//
// /data/api/v1/gateway-info answers 401 anonymous and 200 authenticated, and
// the fetch runs in the page so it carries the session cookie. Deterministic,
// and no waiting on render.
async function isLoggedIn(pg) {
  try {
    return await pg.evaluate(async (timeoutMs) => {
      const r = await fetch('/data/api/v1/gateway-info',
        { credentials: 'same-origin', signal: AbortSignal.timeout(timeoutMs) });
      return r.status === 200;
    }, FETCH_TIMEOUT_MS);
  } catch (e) {
    // Unchanged: a probe, not a verdict -- login() treats "false" as "try to
    // log in for real" either way, and that path has its own timeouts and its
    // own explicit failure if IT stalls. The only change here is that this can
    // no longer hang the probe itself forever.
    return false;
  }
}

// CONTINUE is flaky enough on a freshly-rendered form that the playbook retries
// it three times; do the same rather than fail the whole run on one miss.
async function clickContinue(pg) {
  const btn = pg.locator("button:has-text('Continue'), text='CONTINUE'").first();
  for (let i = 0; i < 3; i++) {
    try {
      await btn.click({ timeout: STEP / 3 });
      return;
    } catch (e) {
      if (i === 2) {
        // Some builds submit on Enter instead of showing a button.
        await pg.keyboard.press('Enter');
        return;
      }
      await pg.waitForTimeout(500);
    }
  }
}

// Wait for a data-grid row containing `text`. Every grid in this UI renders
// empty and then fetches, so any single-shot check races it.
async function waitForRow(pg, text, ms, near) {
  // Match rendered TEXT, not <tr> elements. These grids are not real tables --
  // rows are divs with role=row -- so querySelectorAll('tr') finds nothing and
  // every existence check reports false on a row that is plainly on screen.
  // `near` (the port) keeps "ignition" from matching the "Ignition edge 8.3.8"
  // in the page header.
  const deadline = Date.now() + ms;
  while (Date.now() < deadline) {
    const hit = await pg.evaluate(([t, n]) => {
      const body = document.body.innerText || '';
      if (!n) return body.includes(t);
      return new RegExp(t + '[\\s\\S]{0,120}' + n).test(body);
    }, [text, near || '']);
    if (hit) return true;
    await pg.waitForTimeout(1500);
  }
  return false;
}

// Approve any NOT APPROVED entry in the Remote Certificates grid on whichever
// Gateway Network page is currently open. The action lives behind a per-row
// kebab menu, so open that first.
async function approveRemoteCerts(pg) {
  let approved = 0;
  for (let i = 0; i < 8; i++) {
    const status = pg.locator("text=NOT APPROVED").first();
    if (await status.count() === 0) break;

    // The row's kebab is the next button after the status text in document
    // order. Anchoring on tr/[role=row] fails (these grids are divs) and a
    // page-wide button search picks the help menu in the top bar -- both of
    // which no-op silently and leave the connection FAULTED with no clue why.
    const kebab = status.locator('xpath=following::button[1]');
    if (await kebab.count() === 0) break;
    await kebab.click({ timeout: STEP, force: true });
    await pg.waitForTimeout(1500);

    const hit = await pg.evaluate(() => {
      const el = [...document.querySelectorAll('li, button, a, [role="menuitem"]')]
        .find(e => /^approve/i.test(e.textContent.trim()));
      if (!el) return false;
      el.click();
      return true;
    });
    if (!hit) {
      await dumpControls(pg, `cert-menu-${i}`);
      break;
    }
    await pg.waitForTimeout(1500);

    await pg.evaluate(() => {
      const dlg = document.querySelector('[role="dialog"], .modal, [class*="Modal"]');
      if (!dlg) return;
      const el = [...dlg.querySelectorAll('button')]
        .find(e => /^(approve|confirm|yes|ok|save)$/i.test(e.textContent.trim()));
      if (el) el.click();
    });
    await pg.waitForTimeout(2500);
    approved++;
  }
  if (approved) console.log(`  approved ${approved} remote certificate(s)`);
  return approved;
}

async function dumpControls(pg, label) {
  const shot = path.join(SHOT_DIR, `gw-${NAME}-${label}.png`);
  fs.mkdirSync(SHOT_DIR, { recursive: true });
  await pg.screenshot({ path: shot, fullPage: true });

  const grab = async (sel) => {
    try {
      return [...new Set((await pg.locator(sel).allInnerTexts())
        .map(t => t.replace(/\s+/g, ' ').trim()).filter(Boolean))];
    } catch (e) { return []; }
  };
  console.log(`url      : ${pg.url()}`);
  console.log(`screenshot: ${shot}`);
  console.log(`buttons  : ${JSON.stringify(await grab('button'))}`);
  console.log(`links    : ${JSON.stringify((await grab('a')).slice(0, 40))}`);
  // hrefs matter more than link text: the config areas are client-side routes
  // whose URLs are not guessable, and clicking a rail item does not always move
  // the router. Reading the href and navigating straight there is reliable.
  const hrefs = await pg.locator('a[href]').evaluateAll(els =>
    [...new Set(els.map(e => `${e.textContent.trim().slice(0, 28)} -> ${e.getAttribute('href')}`))]
      .filter(s => !/^\s*->/.test(s)));
  console.log(`hrefs    : ${JSON.stringify(hrefs.slice(0, 45), null, 1)}`);
  console.log(`headings : ${JSON.stringify(await grab('h1, h2, h3'))}`);
  const inputs = await pg.locator('input, select').evaluateAll(els =>
    els.map(e => ({ tag: e.tagName.toLowerCase(), type: e.type, name: e.name, id: e.id,
                    ph: e.placeholder, label: (e.labels && e.labels[0] && e.labels[0].innerText) || '' }))
       .filter(o => o.name || o.id || o.ph || o.label));
  console.log(`inputs   : ${JSON.stringify(inputs, null, 1)}`);
}

(async () => {
  const browser = await chromium.launch({ headless: !process.env.HEADFUL });
  const pg = await (await browser.newContext({ viewport: { width: 1600, height: 1200 } })).newPage();
  let code = 1;

  // --trace records the API calls the SPA makes. Config endpoints in 8.3 are
  // not guessable -- every invented /data/api/v1/... path 404s -- so the only
  // reliable way to find the call behind a UI action is to watch the page make
  // it. Paired with `api`, that turns an undriveable DOM control into a request.
  const traced = [];
  if (process.argv.includes('--trace') || process.env.TRACE) {
    pg.on('request', r => {
      const u = r.url();
      // TRACE_ALL keeps the JS chunks too: the config pages are lazily-loaded
      // modules that are NOT in the page's importmap, and finding the chunk is
      // the only way to read the endpoints a page uses without clicking it.
      const isAsset = /\.(js|css|png|svg|woff2?)(\?|$)/.test(u);
      if (/\/data\/|\/api\/|\/res\//.test(u) && (!isAsset || process.env.TRACE_ALL)) {
        // Tokens in these URLs are handled by scrub() on the way out.
        traced.push(`${r.method()} ${u.replace(URL, '')}` +
          (r.postData() ? `\n     body: ${r.postData().slice(0, 500)}` : ''));
      }
    });
  }

  try {
    // login() already bounds every wait inside it with STEP -- this wraps the
    // whole thing so a timeout in ANY of them (goto, the login control, the
    // fields, isLoggedIn's own fetch) reports plainly which gateway could not
    // be reached, rather than surfacing Playwright's raw "Timeout 40000ms
    // exceeded" with no indication of which of the three gateways it was.
    // login() runs first for every single command, so this is the one place
    // that covers all of them at once.
    try {
      await login(pg);
    } catch (e) {
      throw describeFailure(`login (${STEP}ms budget per step)`, e);
    }

    if (CMD === 'explore') {
      const p = arg('path', '/app/home');
      await pg.goto(`${URL}${p}`, { waitUntil: 'domcontentloaded', timeout: 40000 }).catch(() => {});
      await pg.waitForTimeout(parseInt(arg('settle', '3000'), 10));

      // --click "A > B > C" walks the nav by link text. Config URLs are not
      // guessable -- every invented path here silently redirected to Home,
      // which looks identical to a permissions problem.
      const trail = arg('click');
      if (trail) {
        for (const label of trail.split('>').map(s => s.trim()).filter(Boolean)) {
          const hit = await pg.evaluate((t) => {
            const el = [...document.querySelectorAll('a, button, [role="link"], [role="button"], li')]
              .find(e => e.textContent.trim() === t);
            if (!el) return false;
            el.click();
            return true;
          }, label);
          if (!hit) { console.error(`explore: no clickable "${label}" on ${pg.url()}`); break; }
          await pg.waitForTimeout(parseInt(arg('settle', '3000'), 10));
          console.log(`clicked   : ${label}  ->  ${pg.url()}`);
        }
      }

      // --sel <css> [--nth N]: click a raw selector, for controls with no text
      // (kebab menus, icon buttons). The escape hatch for when nothing else can
      // address an element.
      const sel = arg('sel');
      if (sel) {
        const n = parseInt(arg('nth', '0'), 10);
        const clicked = await pg.evaluate(([s, i]) => {
          const els = [...document.querySelectorAll(s)];
          if (!els[i]) return { ok: false, count: els.length };
          els[i].click();
          return { ok: true, count: els.length };
        }, [sel, n]);
        console.log(`sel      : ${sel}[${n}] -> ${JSON.stringify(clicked)}`);
        await pg.waitForTimeout(parseInt(arg('settle', '3000'), 10));
      }

      await dumpControls(pg, (trail || sel || p).replace(/[^a-z0-9]+/gi, '_').slice(0, 60));
      code = 0;

    } else if (CMD === 'trial-reset') {
      // Two different UIs. A standard gateway has a licensing page with a Reset
      // control; an EDGE gateway does not have that page at all -- it 404s --
      // and instead offers "Log In to Reset" on the expired-trial banner.
      // login() has already authenticated, so on a standard gateway that banner
      // button is gone and the licensing page is the route.
      let clicked = false;

      const banner = pg.locator("button:has-text('Reset')").first();
      if (await banner.count() > 0) {
        await banner.click({ timeout: STEP });
        clicked = true;
      } else {
        const r = await pg.goto(`${URL}/app/platform/system/licensing`,
                                { waitUntil: 'domcontentloaded', timeout: 40000 }).catch(() => null);
        await pg.waitForTimeout(2500);
        const reset = pg.locator("button:has-text('Reset')").first();
        if (await reset.count() > 0) {
          await reset.click({ timeout: STEP });
          clicked = true;
        }
      }

      if (!clicked) {
        await dumpControls(pg, 'no-reset-control');
        throw new Error('found no Reset control on the banner or the licensing page');
      }

      for (let i = 0; i < 20; i++) {
        await pg.waitForTimeout(1000);
        let t;
        try {
          t = await (await fetch(`${URL}/data/api/v1/trial`,
            { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) })).json();
        } catch (e) {
          throw describeFailure(`trial-reset: poll GET /data/api/v1/trial (${FETCH_TIMEOUT_MS}ms budget)`, e);
        }
        if (!t.expired && t.trialSecondsLeft > 0) {
          console.log(`trial reset: ${Math.round(t.trialSecondsLeft / 60)} min`);
          code = 0; break;
        }
      }
      if (code) console.error('trial-reset: clicked Reset but the trial is still expired');

    } else if (CMD === 'gan-connect') {
      // Create the outgoing Gateway Network connection on a SPOKE. Spokes dial
      // out to the hub; the hub never initiates. Host must be the CONTAINER name
      // (`ignition`) reached over the shared docker network -- inside a container
      // `localhost` is that container itself, and 8060 is the GAN port, not the
      // web port, which is why it is not published to the host at all.
      const host = arg('host', 'ignition');
      const port = arg('port', '8060');

      await pg.goto(`${URL}/app/network/gateway/connections/outgoing`,
                    { waitUntil: 'domcontentloaded', timeout: 40000 });
      await pg.waitForTimeout(4000);

      // Poll, don't snapshot. The data grid fetches after render, so a single
      // check right after load sees an empty table and happily creates a second
      // connection to a host that already has one.
      const already = await waitForRow(pg, host, 20000, port);
      if (already) {
        console.log(`gan-connect: a connection to ${host} already exists`);
        code = 0;
      } else {
        await pg.evaluate(() => {
          const el = [...document.querySelectorAll('button')]
            .find(e => e.textContent.trim() === 'Create Outgoing Connection');
          if (el) el.click();
        });
        await pg.waitForTimeout(2500);

        await pg.fill('#host-input', host);
        await pg.fill('#port-input', String(port));

        // Both default off. SSL on the GAN leg is the documented setup, and the
        // connection is inert without Enabled.
        for (const id of ['#enabled-input', '#useSSL-input']) {
          const box = pg.locator(id).first();
          if (await box.count() > 0 && !(await box.isChecked().catch(() => true))) {
            await box.check({ timeout: STEP }).catch(async () => {
              await pg.evaluate((s) => document.querySelector(s)?.click(), id);
            });
          }
        }

        // The dialog's submit button carries the SAME label as the page button
        // that opened it ("Create Outgoing Connection"), so an unscoped search
        // matches the page one and re-opens the form instead of saving. Scope to
        // the dialog and take the button that is not Cancel.
        const saved = await pg.evaluate(() => {
          const dlg = document.querySelector('[role="dialog"], .modal, [class*="Modal"], [class*="drawer" i]');
          const scope = dlg || document;
          const btns = [...scope.querySelectorAll('button')]
            .filter(e => !/^(cancel|close)$/i.test(e.textContent.trim()) && !e.disabled);
          const el = btns.find(e => /create|save|submit/i.test(e.textContent.trim()));
          if (!el) return false;
          el.click();
          return true;
        });
        if (!saved) {
          await dumpControls(pg, 'gan-create-no-save');
          throw new Error('no Create/Save control on the outgoing-connection form');
        }
        // Poll: the grid re-fetches after the save and a single immediate check
        // reads the pre-save DOM, reporting failure on a connection that was in
        // fact created.
        const listed = await waitForRow(pg, host, 25000, port);
        if (!listed) {
          await dumpControls(pg, 'gan-create-not-listed');
          throw new Error(`saved but ${host} is not in the outgoing connections list`);
        }
        console.log(`gan-connect: outgoing connection to ${host}:${port} created (SSL, enabled)`);
        code = 0;
      }

      // An SSL connection also needs the REMOTE gateway's certificate approved
      // on this side, listed under "Remote Certificates" as NOT APPROVED. Until
      // that happens the connection sits at CONNECTING forever with no error --
      // it looks exactly like a network problem.
      await approveRemoteCerts(pg);

    } else if (CMD === 'gan-approve') {
      // Approve pending INCOMING connections on the hub. Distinct from
      // approving certificates (scripts/ign-gan.sh, which is a file move):
      // the certificate is the TLS trust, this is the gateway agreeing to talk
      // to that peer. Both are required, certificate first -- a peer whose cert
      // is not trusted never reaches this list at all.
      // Driven through the gateway's REST API, not the DOM. Two DOM routes were
      // tried and both are traps: the per-row kebab and the bulk checkbox action
      // each report success and leave every row Pending Approval, which is
      // indistinguishable from having worked. The grids are divs rather than
      // tables and the row menus render in portals, so there is nothing stable
      // to click.
      //
      // The endpoint is a DEDICATED one, not the generic resource writer. That
      // distinction cost a round of 404s: the page reads its rows through
      // /data/api/v1/resources/list/ignition/gateway-network-incoming, so the
      // obvious guess is that it writes them back through
      // PUT /data/api/v1/resources/ignition/gateway-network-incoming. That path
      // does not exist -- it 404s.
      //
      // The real call comes from the page's own lazily-loaded chunk, which is
      // NOT in the importmap and does not appear in ia-gateway.js or
      // IgnitionGatewayLib.js. Find it with:
      //     TRACE_ALL=1 ign-gw.js explore --path <page> --trace
      // then read /res/sys/js/gateway/<Page>.chunk.bundle.js. For this page:
      //
      //   PUT /data/api/v1/gateway-network-incoming/toggleApproval/<remoteId>/<bool>
      //
      // remoteId is config.connectionId ("edge1|<uuid>"), URL-encoded; there is
      // no request body. securityStatus is IncomingConnection$SecurityStatus in
      // gateway-api-8.3.8.jar: PendingApproval | Approved | NotOnWhiteList.
      //
      // Every write also needs an X-CSRF-Token. 8.3 answers 403 without it even
      // on a fully authenticated session -- which is the same 403 that made
      // POST /data/api/v1/trial look forbidden-by-permission and sent the trial
      // reset down the click-the-button route. The token is handed out by
      // GET /data/app/session as `csrfToken`; the SPA attaches it to every
      // mutation. It is a session secret, so it is never logged.
      let result;
      try {
        result = await pg.evaluate(async (timeoutMs) => {
          const TYPE = 'ignition/gateway-network-incoming';
          const sess = await fetch('/data/app/session',
            { credentials: 'same-origin', signal: AbortSignal.timeout(timeoutMs) });
          const csrf = (await sess.json()).csrfToken;
          if (!csrf) throw new Error('no csrfToken on /data/app/session');

          const get = async () => {
            const r = await fetch(`/data/api/v1/resources/list/${TYPE}?limit=200&offset=0`,
              { credentials: 'same-origin', signal: AbortSignal.timeout(timeoutMs) });
            if (r.status !== 200) throw new Error(`list returned ${r.status}`);
            return (await r.json()).items || [];
          };

          // Count EVERY incoming connection by status, not just the pending ones.
          // "approved 0" is true of a healthy already-approved pair and of a
          // backup that has never dialled in, and those need opposite responses.
          const all = await get();
          const byStatus = {};
          for (const i of all) {
            const s = (i.config && i.config.securityStatus) || 'Unknown';
            byStatus[s] = (byStatus[s] || 0) + 1;
          }
          const pending = all
            .filter(i => i.config && i.config.securityStatus === 'PendingApproval');
          if (!pending.length) return { total: all.length, byStatus, pending: 0, approved: 0, remaining: 0, calls: [] };

          const calls = [];
          for (const i of pending) {
            const id = encodeURIComponent(i.config.connectionId);
            const r = await fetch(
              `/data/api/v1/gateway-network-incoming/toggleApproval/${id}/true`,
              {
                method: 'PUT',
                credentials: 'same-origin',
                headers: {
                  'X-CSRF-Token': csrf,
                  'X-Requested-With': 'XMLHttpRequest',
                  'Accept': 'application/json',
                },
                signal: AbortSignal.timeout(timeoutMs),
              });
            calls.push({ name: i.name, status: r.status, body: (await r.text()).slice(0, 200) });
          }

          // Re-read rather than trust the status codes -- this command exists
          // because the UI path claimed success and changed nothing.
          const remaining = (await get())
            .filter(i => i.config && i.config.securityStatus === 'PendingApproval');

          return {
            total: all.length,
            byStatus,
            pending: pending.length,
            approved: pending.length - remaining.length,
            remaining: remaining.length,
            calls,
          };
        }, FETCH_TIMEOUT_MS);
      } catch (e) {
        throw describeFailure(`gan-approve (${FETCH_TIMEOUT_MS}ms budget per call)`, e);
      }

      const shape = Object.keys(result.byStatus || {})
        .map(k => `${result.byStatus[k]} ${k}`).join(', ') || 'none';
      console.log(`gan-approve: ${result.total} incoming connection(s) -- ${shape}`);
      if (result.total === 0) {
        console.log('');
        console.log('  NO INCOMING CONNECTIONS AT ALL. This is not an approval problem:');
        console.log('  an incoming connection only exists once the other gateway has');
        console.log('  DIALLED IN, so there is nothing here to approve and approving');
        console.log('  cannot be what is missing. Check that the backup can reach this');
        console.log('  gateway on 8060 before looking at certificates:');
        console.log('     docker exec ignition-backup sh -c "getent hosts ignition"');
        console.log('     docker logs ignition-backup --tail 60 | grep -i redundan');
      }
      console.log(`gan-approve: ${result.pending} connection(s) pending`);
      for (const c of result.calls) {
        console.log(`  ${c.status}  ${c.name}${c.status >= 400 ? '  ' + c.body : ''}`);
      }

      if (result.remaining > 0) {
        console.error(`gan-approve: ${result.remaining} still pending`);
        console.error(`  approve by hand at ${URL}/app/network/gateway/connections/incoming`);
      }

      console.log(`gan-approve: approved ${result.approved} incoming connection(s)`);
      code = result.remaining > 0 ? 1 : 0;

    } else if (CMD === 'mqtt-server') {
      // Make a Cirrus Link MQTT module's broker connections match a declared
      // shape: Engine on the hub, Transmission on an edge -- the same resource
      // types (cert-file, server-set, server) with near-identical fields. Driven
      // from scripts/ign-mqtt.sh, which owns reading the broker credentials;
      // they arrive here in a 0600 file so they never touch argv.
      //
      // Payload: module, caName, caPem, username, password, and
      //   serverSet       the set every listed server belongs to
      //   serverSetConfig fields that set must have (primaryHostId, ...)
      //   servers         [{name, url}] -- in order: Transmission tries them in
      //                   list order, so the first is where an edge goes first
      //   serverConfig    fields every listed server must have (keepAlive, ...)
      //   bindNamespaces  namespaces to bind to the set (Engine: without the
      //                   Sparkplug one the set subscribes to nothing, T-D10)
      //   prune           delete every server NOT listed (the old broker's)
      //   force           re-send the CA and passwords even when nothing differs
      //   check           READ ONLY: write nothing, print a `drift:` line for
      //                   every write it would have made (scripts/drift.sh)
      //
      // IDEMPOTENT, and that is not a nicety: every Transmission server or set
      // write restarts every transmitter on the edge, and every Engine write
      // re-births every edge (docs/MQTT-DISTRIBUTOR.md T-D17). So each resource
      // is read, compared, and written only when something differs. Passwords
      // are encrypted on the gateway and cannot be compared; the user and CA,
      // written in the same PUT, stand for them (`force` re-sends them).
      const payloadPath = arg('payload');
      if (!payloadPath) throw new Error('mqtt-server needs --payload <file>');
      const p = JSON.parse(fs.readFileSync(payloadPath, 'utf8'));
      const isTx = p.module.includes('transmission');
      const R = `/data/api/v1/resources`;
      const list = async (type) => ((await api(pg, 'GET',
        `${R}/list/${p.module}/${type}?limit=100&offset=0`)).json.items || []);
      const ok = (r) => r && r.json && (r.json.success === true
        || (Array.isArray(r.json) && r.json.every(x => x.success !== false)));
      let changed = 0;
      const CHECK = !!p.check;
      let drift = 0;
      const drifted = (what) => { drift += 1; console.log(`  drift: ${what}`); };

      // Encrypt through the gateway itself. Secret-valued config fields are
      // {"type":"Embedded","data":{<jwe>}}, and the gateway will not accept a
      // plain string: it answers 422 "Unable to read required property 'type'",
      // which names the secret-value discriminator, not the resource type.
      //
      // The body is the plaintext itself, sent RAW -- not {plaintext: "..."},
      // and not JSON-encoded either. All three variants return 200 with a
      // valid-looking JWE, so the mistake surfaces only much later, when the
      // module tries to use the certificate and fails with
      // "java.security.cert.CertificateException: No certificate data found".
      const encrypt = async (plaintext) =>
        ({ type: 'Embedded',
           data: (await api(pg, 'POST', '/data/api/v1/encryption/encrypt', plaintext, true)).json });

      const write = async (verb, type, row) => {
        const r = await api(pg, verb, `${R}/${p.module}/${type}`, [row]);
        if (!ok(r)) throw new Error(`${verb} ${type} '${row.name}' refused: ${r.text.slice(0, 300)}`);
        changed += 1;
      };
      const differs = (have, want) => Object.keys(want)
        .filter(k => JSON.stringify(have[k]) !== JSON.stringify(want[k]));

      // --- the CA, as a cert-file resource -------------------------------------
      // Not a file upload: /data/api/v1/resources/datafile/ 404s for this type;
      // the PEM lives in config.fileContents, encrypted like a password.
      let cert = (await list('cert-file')).find(c => c.name === p.caName);
      if (CHECK) {
        if (!cert || !(cert.config || {}).fileContents) drifted(`broker CA certificate '${p.caName}' is missing`);
      } else if (!cert || p.force || !(cert.config || {}).fileContents) {
        if (!cert) {
          await write('POST', 'cert-file', { name: p.caName, description: 'Broker CA',
            enabled: true, collection: 'core', config: {} });
          cert = (await list('cert-file')).find(c => c.name === p.caName);
          if (!cert) throw new Error(`cert-file ${p.caName} was not created`);
        }
        await write('PUT', 'cert-file', { name: p.caName, description: cert.description ?? 'Broker CA',
          enabled: true, collection: cert.collection || 'core', signature: cert.signature,
          config: { fileName: `${p.caName}.pem`, fileContents: await encrypt(p.caPem) } });
        console.log(`mqtt-server: cert-file ${p.caName} stored`);
      } else {
        console.log(`mqtt-server: cert-file ${p.caName} present`);
      }

      // --- the server set --------------------------------------------------------
      const want = p.serverSetConfig || {};
      const set = (await list('server-set')).find(x => x.name === p.serverSet);
      if (CHECK) {
        if (!set) drifted(`server set '${p.serverSet}' is missing`);
        else {
          for (const k of differs(set.config || {}, want)) {
            drifted(`server set '${p.serverSet}' ${k} is ${JSON.stringify((set.config || {})[k])}, want ${JSON.stringify(want[k])}`);
          }
          if (set.enabled === false) drifted(`server set '${p.serverSet}' is disabled`);
        }
      } else if (!set) {
        await write('POST', 'server-set', { name: p.serverSet, description: p.description || null,
          enabled: true, collection: 'core', config: want });
        console.log(`mqtt-server: server set '${p.serverSet}' created`);
      } else if (differs(set.config || {}, want).length || set.enabled === false) {
        await write('PUT', 'server-set', { name: set.name, description: set.description ?? null,
          enabled: true, collection: set.collection || 'core', signature: set.signature,
          config: { ...set.config, ...want } });
        console.log(`mqtt-server: server set '${p.serverSet}' set (${differs(set.config || {}, want).join(',') || 'enabled'})`);
      } else {
        console.log(`mqtt-server: server set '${p.serverSet}' already right`);
      }

      // --- namespace bindings (Engine) -----------------------------------------
      // BEFORE the server, so no moment exists where the set has a connected
      // server and no Sparkplug subscription -- the subscribe-nothing trap.
      // bindIfPresent: custom namespaces another script creates (sparkplug-setup's
      // AlarmDemoNotify) -- bound when they exist, skipped when they do not yet.
      // A custom namespace binds itself to every set that exists WHEN IT IS
      // CREATED, so one made before this set has to be bound here.
      const present = (p.bindIfPresent || []).length
        ? (await list('custom-namespace')).map(c => c.name) : [];
      const toBind = [...(p.bindNamespaces || []), ...(p.bindIfPresent || []).filter(n => present.includes(n))];
      if (toBind.length) {
        const binds = await list('namespace-server-set');
        for (const ns of toBind) {
          if (binds.some(b => (b.config || {}).namespace === ns && (b.config || {}).serverSet === p.serverSet
                              && b.enabled !== false)) {
            console.log(`mqtt-server: namespace '${ns}' already bound to '${p.serverSet}'`);
            continue;
          }
          if (CHECK) { drifted(`namespace '${ns}' is not bound to server set '${p.serverSet}'`); continue; }
          await write('POST', 'namespace-server-set', { name: `${ns}-${p.serverSet}`, enabled: true,
            collection: 'core', config: { namespace: ns, serverSet: p.serverSet } });
          console.log(`mqtt-server: namespace '${ns}' bound to '${p.serverSet}'`);
        }
      }

      // --- the servers -------------------------------------------------------------
      let servers = await list('server');
      const template = (servers[0] || {}).config || {};
      for (const w of p.servers) {
        const wantCfg = { url: w.url, serverSet: p.serverSet, username: p.username,
          caCertFile: p.caName, hostnameVerification: true, ...(p.serverConfig || {}) };
        // Transmission's RPC client -- the connection
        // system.cirruslink.transmission.publish uses -- has its OWN CA and
        // credentials (rpc*). Left at the defaults (no CA, rpcUsername "admin")
        // it failed TLS every 2 s, "PKIX path building failed", while publish()
        // still returned normally and delivered nothing (measured 11/09/2026).
        // Engine's server has no rpc* fields.
        if (isTx) Object.assign(wantCfg, { rpcCaCertFile: p.caName, rpcUsername: p.username,
                                          rpcHostnameVerification: true });
        const have = servers.find(x => x.name === w.name);
        const diff = have ? differs(have.config || {}, wantCfg) : ['new'];
        if (have && !diff.length && have.enabled !== false && !p.force) {
          console.log(`mqtt-server: ${w.name} -> ${w.url} already right`);
          continue;
        }
        if (CHECK) {
          if (!have) drifted(`server '${w.name}' (${w.url}) is missing`);
          else {
            for (const k of diff) {
              drifted(`server '${w.name}' ${k} is ${JSON.stringify((have.config || {})[k])}, want ${JSON.stringify(wantCfg[k])}`);
            }
            if (have.enabled === false) drifted(`server '${w.name}' is disabled`);
          }
          continue;
        }
        const pw = await encrypt(p.password);
        const config = { ...(have ? have.config : template), ...wantCfg, password: pw };
        if (isTx) config.rpcPassword = pw;
        if (have) {
          await write('PUT', 'server', { name: w.name, description: have.description ?? null,
            enabled: true, collection: have.collection || 'core', signature: have.signature, config });
        } else {
          await write('POST', 'server', { name: w.name, description: p.description || null,
            enabled: true, collection: 'core', config });
        }
        console.log(`mqtt-server: ${w.name} -> ${w.url} (${diff.join(',') || 'forced'})`);
      }

      // --- everything else goes (the old broker's entry) --------------------------
      if (p.prune && CHECK) {
        for (const s of servers.filter(x => !p.servers.some(w => w.name === x.name))) {
          drifted(`extra server '${s.name}' (${(s.config || {}).url}) -- setup would delete it`);
        }
      } else if (p.prune) {
        servers = await list('server');
        for (const s of servers.filter(x => !p.servers.some(w => w.name === x.name))) {
          const r = await api(pg, 'DELETE',
            `${R}/${p.module}/server/${encodeURIComponent(s.name)}/${encodeURIComponent(s.signature)}`);
          if (r.status >= 300) throw new Error(`DELETE server '${s.name}' -> ${r.status}`);
          changed += 1;
          console.log(`mqtt-server: removed server '${s.name}' (${(s.config || {}).url})`);
        }
      }

      // Verify from a re-read rather than the status codes.
      const after = await list('server');
      const bad = p.servers.filter(w => !after.some(s => s.name === w.name && s.config.url === w.url
                                                     && s.config.serverSet === p.serverSet));
      for (const s of after) console.log(`  ${s.name}: ${s.config.url}  set=${s.config.serverSet}` +
        `  ca=${s.config.caCertFile || '(none)'}  keepAlive=${s.config.keepAlive}` +
        (isTx ? `  rpc ca=${s.config.rpcCaCertFile || '(none)'} rpc user ${s.config.rpcUsername === p.username ? 'set' : 'NOT set'}` : ''));
      if (CHECK) {
        console.log(`mqtt-server: ${drift} difference(s), nothing written`);
        code = drift ? 1 : 0;
      } else {
        console.log(`mqtt-server: ${changed} write(s)`);
        code = bad.length ? 1 : 0;
      }

    } else if (CMD === 'eam-setup') {
      // EAM install mode is a SINGLETON config resource, not a wizard:
      //   GET /data/api/v1/resources/singleton/com.inductiveautomation.eam/module-settings
      //   PUT /data/api/v1/resources/com.inductiveautomation.eam/module-settings   body [resource]
      // installMode is NotInstalled | Controller | Agent (from eam.js).
      //
      // Read-modify-write: the PUT carries the record's `signature` back, which
      // is how the endpoint refuses a blind overwrite of a stale copy.
      const SETTINGS = '/data/api/v1/resources/com.inductiveautomation.eam/module-settings';
      const role = (arg('role') || '').toLowerCase();
      if (!['controller', 'agent'].includes(role)) {
        throw new Error('eam-setup needs --role controller|agent');
      }

      // Read-modify-write helper: the PUT must carry the CURRENT signature, so
      // re-read between writes rather than reusing a stale copy.
      const readSettings = async () =>
        (await api(pg, 'GET', '/data/api/v1/resources/singleton/com.inductiveautomation.eam/module-settings')).json;
      const writeSettings = async (rec, cfg) => api(pg, 'PUT', SETTINGS, [{
        description: rec.description ?? null,
        enabled: rec.enabled !== false,
        collection: rec.collection || 'core',
        signature: rec.signature,
        config: cfg,
      }]);

      let cur = await readSettings();

      // Two reasons to drop through NotInstalled on the way:
      //
      //  - Switching straight from Controller to Agent is rejected with a bare
      //    400 and no message body. It has to pass through NotInstalled first.
      //    (The reverse is fine.) Verified on 8.3.8, 01/08/2026.
      //  - --reregister forces the agent to re-introduce itself. The controller
      //    caches an agent's licence state from REGISTRATION and does not
      //    refresh it: an agent that registered while its trial was expired
      //    keeps reporting "Trial Expired:Agent" long after a trial reset, and
      //    every task against it fails with "Trial expired on agent" even
      //    though the agent's own /data/api/v1/trial says expired=false.
      //    Re-registering is what clears it.
      const bounce = (cur.config.installMode === 'Controller' && role === 'agent')
                  || (process.argv.includes('--reregister')
                      && cur.config.installMode !== 'NotInstalled');
      if (bounce) {
        console.log(`eam-setup: ${cur.config.installMode} -> NotInstalled -> ${role}`);
        await writeSettings(cur, { ...cur.config, installMode: 'NotInstalled' });
        cur = await readSettings();
      }

      const config = { ...cur.config };

      if (role === 'controller') {
        config.installMode = 'Controller';
        // datasource is nullable in the form schema, so a controller runs
        // without a database. Agent event history just has nowhere to land.
        config.controllerSettings = { ...config.controllerSettings };
      } else {
        // An agent must name its controller by Gateway Network serverId, and
        // the form validates it against the live peer list -- so read it from
        // there rather than constructing it from the hub's name.
        let serverId = arg('controller');
        if (!serverId) {
          const gws = (await api(pg, 'GET', '/data/api/v1/gateway-network/gateways')).json;
          const peers = (gws.items || []).filter(g => g.status === 'Connected');
          if (peers.length !== 1) {
            throw new Error(
              `expected exactly one connected peer to use as controller, found ${peers.length}` +
              ` -- pass --controller <serverId>`);
          }
          serverId = peers[0].serverId;
          console.log(`eam-setup: controller discovered as ${serverId} (${peers[0].name})`);
        }
        config.installMode = 'Agent';
        config.agentSettings = { ...config.agentSettings, controllerServerId: serverId };
      }

      await writeSettings(cur, config);

      // Verify from a re-read, not the status code.
      const after = await readSettings();
      const mode = after.config.installMode;
      console.log(`eam-setup: installMode = ${mode}`);
      if (role === 'agent') {
        console.log(`eam-setup: controller = ${after.config.agentSettings?.controllerServerId}`);
      }
      code = mode.toLowerCase() === role ? 0 : 1;
      if (code) console.error(`eam-setup: expected ${role}, gateway reports ${mode}`);

    } else if (CMD === 'eam-agents') {
      // Agents register themselves with the controller once they are pointed at
      // it, then wait for approval -- the same two-step as a Gateway Network
      // incoming connection, and a separate act from it.
      // The LIVE agent list is /data/eam/api/v1/agents -- note the /data/eam/
      // prefix, which is a different namespace from the /data/api/v1/ used
      // everywhere else. The config-resource list
      // (resources/list/com.inductiveautomation.eam/agent-management) is NOT
      // this: it is empty until an agent is approved, so reading it reports
      // "no agents" while two are sitting there waiting.
      const AGENTS = '/data/eam/api/v1/agents';
      const list = async () => ((await api(pg, 'GET', AGENTS)).json.items || []);

      let items = await list();
      console.log(`eam-agents: ${items.length} agent(s) known to this controller`);
      for (const a of items) console.log(`  ${a.name.padEnd(12)} ${a.statusMessage}`);

      if (process.argv.includes('--approve')) {
        const pending = items.filter(a => !/^approved|running|active/i.test(a.statusMessage));
        for (const a of pending) {
          await api(pg, 'POST', `/data/eam/api/v1/approve-agent/${encodeURIComponent(a.name)}`);
          console.log(`  approve ${a.name} -> sent`);
        }
        // Verify by re-reading, not by the status code.
        items = await list();
        console.log('eam-agents: after approval');
        for (const a of items) console.log(`  ${a.name.padEnd(12)} ${a.statusMessage}`);
        code = items.some(a => /pending/i.test(a.statusMessage)) ? 1 : 0;
      } else {
        code = 0;
      }

    } else if (CMD === 'eam-push') {
      // Send a project to an EAM agent, creating the Send Project task first if
      // it is not already there.
      //
      // WHY THIS EXISTS. The tasks on this machine were made by hand in the
      // Tasks UI, and nothing recreated them anywhere else -- so a gateway
      // built from a clean clone had two approved, Connected agents, an empty
      // task list, and edges still running the stub `Edge` project they create
      // for themselves at commissioning. Nothing reported a problem, because
      // nothing had been asked to do anything. The edges then went trial-expired
      // about two hours later, since gw_trial is an INHERITED resource and
      // only arrives with the push (and nothing resets a trial automatically).
      //
      // THE TASK NAME IS A CONTRACT, not a label: gateway_admin.AGENTS runs
      // these by name from the /admin page's buttons, so "Send <project> to
      // <agent>" has to match there or the page silently has nothing to run.
      //
      // flattenProjectsKey is the "Include inherited project resources"
      // checkbox, and it is mandatory for an Edge target: an Edge gateway runs
      // exactly ONE project, so the parent has to be combined in at push time
      // rather than sent alongside. The shape below mirrors a task read back
      // off a working gateway rather than the documented example -- the live
      // one uses scheduleMode OnDemand, which is what the force call expects.
      const project = arg('project');
      const agent = arg('agent');
      if (!project || !agent) throw new Error('eam-push needs --project and --agent');
      const taskName = `Send ${project} to ${agent}`;

      const TYPE = 'com.inductiveautomation.eam/eam-tasks';
      const listTasks = async () =>
        ((await api(pg, 'GET', `/data/api/v1/resources/list/${TYPE}`)).json.items || []);

      // The agent has to be known and approved before a task can target it.
      // Creating one against an unknown gateway is accepted and then does
      // nothing, which is the least helpful of the available outcomes.
      const agents = (await api(pg, 'GET', '/data/eam/api/v1/agents')).json.items || [];
      const known = agents.find(a => a.name === agent);
      if (!known) {
        console.error(`eam-push: '${agent}' is not a registered agent on this controller.`);
        console.error(`  known: ${agents.map(a => a.name).join(', ') || '(none)'}`);
        code = 1;
      } else {
        if (/pending/i.test(known.statusMessage || '')) {
          console.error(`eam-push: '${agent}' is ${known.statusMessage} -- approve it first`);
          code = 1;
        } else {
          let tasks = await listTasks();
          if (tasks.some(t => t.name === taskName)) {
            console.log(`eam-push: task '${taskName}' already exists`);
          } else {
            await api(pg, 'POST', `/data/api/v1/resources/${TYPE}`, [{
              name: taskName,
              description: `Push ${project} to ${agent}, flattened with its ancestry`,
              enabled: true,
              config: {
                profile: {
                  type: 'eam_sendProject',
                  isSuspended: false,
                  scheduleMode: 'OnDemand',
                  scheduleDetails: '',
                },
                settings: {
                  targetGateways: [agent],
                  targetGroups: [],
                  controllerIsTargetKey: false,
                  flattenProjectsKey: true,
                  maxConcurrentAgents: 0,
                  selectedGateway: '',
                  sourceProject: project,
                },
              },
            }]);
            // Verify by re-reading. A 200 on the write says the request was
            // accepted, not that the resource is there under the name we need.
            tasks = await listTasks();
            if (!tasks.some(t => t.name === taskName)) {
              throw new Error(`created '${taskName}' but it is not in the task list`);
            }
            console.log(`eam-push: created task '${taskName}'`);
          }

          // Owner is the SHORT module name "eam". "core" and the full
          // com.inductiveautomation.eam both 500 with "No resource handler
          // registered", which reads like the route being wrong.
          await api(pg, 'POST',
            `/data/eam/api/v1/eam-tasks/force/eam/${encodeURIComponent(taskName)}?retry=true`);
          console.log(`eam-push: ran '${taskName}'`);

          // Deliberately NOT reporting success here. EAM's Send Project is
          // differential and compares resource METADATA, so a task that sent
          // nothing at all reports exactly what a task that sent everything
          // does. The caller verifies on the TARGET -- see scripts/eam-push.sh.
          code = 0;
        }
      }

    } else if (CMD === 'api') {
      // Authenticated request against the gateway's own REST API, issued from
      // inside the page so it carries the session cookie and same-origin
      // headers. 8.3 authenticates the API with that cookie -- HTTP Basic from
      // curl gets 401, which is why this has to go through a browser at all.
      //
      // This exists because some config actions cannot be driven through the
      // DOM: the record grids are divs rather than tables and their row menus
      // render in portals, so a click can report success and change nothing.
      // The API underneath is stable and its response is checkable.
      const p = arg('path');
      if (!p) throw new Error('api needs --path');
      const method = (arg('method', 'GET') || 'GET').toUpperCase();
      // --body-file rather than --body for anything non-trivial: argv is
      // world-readable on this box, and request bodies get long enough to be
      // mangled by shell quoting.
      // --body-file-raw sends the file verbatim instead of as JSON, for the
      // datafile endpoints that take file bytes (certificate PEMs).
      const rawFile = arg('body-file-raw');
      const bodyFile = arg('body-file');
      const bodyArg = rawFile ? fs.readFileSync(rawFile, 'utf8')
                    : bodyFile ? fs.readFileSync(bodyFile, 'utf8')
                    : arg('body');

      // Shares api() with every other command, so a write from here carries the
      // same X-CSRF-Token. They used to differ, and this one silently 403'd on
      // writes while the others worked.
      let res;
      try {
        res = rawFile
          ? await api(pg, method, p, bodyArg, true)
          : await api(pg, method, p, bodyArg ? JSON.parse(bodyArg) : undefined);
        console.log(`${res.status}  ${method} ${p}`);
        if (res.text) console.log(res.text);
        code = 0;
      } catch (e) {
        console.error(e.message);
        code = 1;
      }

    } else if (CMD === 'backup') {
      // Download a gateway backup (.gwbk) to --out.
      //
      // NOT through api(): that helper reads the response with `r.text()`,
      // which is correct for JSON and silently CORRUPTS a binary body -- every
      // byte sequence that is not valid UTF-8 comes back as U+FFFD, so the file
      // saves at roughly the right size, opens as a zip, and fails to restore.
      // context.request shares the session cookie and hands back real bytes.
      //
      // The route is GET /data/api/v1/backup, found by probing rather than from
      // the page: the Backup/Restore page issues NO request until its button is
      // clicked, so a trace of the loaded page shows nothing at all.
      const out = arg('out');
      if (!out) throw new Error('backup needs --out');
      try {
        const r = await pg.context().request.get(`${URL}/data/api/v1/backup`, {
          timeout: 180000,
        });
        // The gateway's own words, not only the status: a redundant master
        // with its backup down answers 503 and says why in the body.
        if (!r.ok()) {
          const body = await r.text();
          const why = (body.match(/<h2>(?:HTTP ERROR \d+ )?([^<]*)<\/h2>/) || [])[1] || body.replace(/\s+/g, ' ').slice(0, 120);
          throw new Error(`GET /data/api/v1/backup -> ${r.status()} ${why.trim()}`);
        }
        const buf = await r.body();
        // A gwbk is a zip. Checking the magic here means a gateway that answers
        // 200 with an HTML error page fails now, rather than months later when
        // someone tries to restore it.
        if (buf.length < 1024 || buf[0] !== 0x50 || buf[1] !== 0x4b) {
          throw new Error(`response is not a zip (${buf.length} bytes)`);
        }
        fs.writeFileSync(out, buf);
        console.log(`${buf.length}  ${out}`);
        code = 0;
      } catch (e) {
        console.error(e.message);
        code = 1;
      }

    } else if (CMD === 'db-create') {
      // Create a database connection through the UI, because a connection holds
      // a PASSWORD and there is no file-based way to write one: SecretConfig
      // accepts only `Embedded` (a JWE encrypted with the gateway's own key) or
      // `Referenced`, so a hand-written config.json can never carry a usable
      // credential. Creating it here lets the gateway do that encryption, after
      // which the non-secret fields can be patched on disk and config-scanned.
      //
      // The REST route was tried first and is a dead end for creation:
      // POST /data/api/v1/resources/ignition/database-connection answers 422
      // "Unable to read required property 'type'" for every envelope shape, and
      // would still not solve the secret.
      //
      // The DB password comes from the environment, never argv -- every process
      // on the box can read a command line.
      const dbName = arg('name');
      const jdbc = arg('url');
      const dbUser = arg('username');
      const driver = arg('driver', 'PostgreSQL');
      const dbPass = process.env.DB_PASSWORD;
      if (!dbName || !jdbc || !dbUser || !dbPass) {
        die('db-create needs --name --url --username and DB_PASSWORD in the env');
      }
      SECRETS.push(dbPass);   // scrub() covers it from here on

      await pg.goto(`${URL}/app/connections/databases`,
                    { waitUntil: 'domcontentloaded', timeout: 40000 });
      await pg.waitForTimeout(4000);

      const exists = async () => pg.evaluate((n) =>
        document.body.innerText.includes(n), dbName);
      if (await exists()) {
        console.log(`db-create: "${dbName}" already exists`);
        code = 0;
      } else {
        await pg.evaluate(() => {
          const el = [...document.querySelectorAll('button')]
            .find(e => /create database connection/i.test(e.textContent.trim()));
          if (el) el.click();
        });
        await pg.waitForTimeout(2500);

        // Step 1 is a driver radio list. Click the LABEL that names the driver;
        // the input itself is visually replaced and may not take a click.
        const picked = await pg.evaluate((d) => {
          const radios = [...document.querySelectorAll('input[type=radio]')];
          for (const r of radios) {
            const lbl = r.closest('label') || r.parentElement;
            if (lbl && lbl.innerText.trim().startsWith(d)) {
              (lbl).click(); r.click(); return true;
            }
          }
          return false;
        }, driver);
        if (!picked) {
          await dumpControls(pg, 'db-create-no-driver');
          throw new Error(`driver "${driver}" not offered on the create form`);
        }
        await pg.waitForTimeout(1200);

        // Advance past the driver step if the form is a wizard.
        await pg.evaluate(() => {
          const el = [...document.querySelectorAll('button')]
            .find(e => /^(next|continue)$/i.test(e.textContent.trim()) && !e.disabled);
          if (el) el.click();
        });
        await pg.waitForTimeout(2500);

        await safeFill(pg, '#name-input', dbName, 'name');
        await safeFill(pg, '#username-input', dbUser, 'username');
        await safeFill(pg, '#connectURL-input', jdbc, 'connect URL');

        // Password is a SecretConfig: a None/Embedded/Referenced radio group,
        // not a plain field. "Embedded" is what makes the gateway encrypt the
        // value with its own key -- which is precisely why this cannot be done
        // by writing config.json.
        const mode = await pg.evaluate(() => {
          const r = [...document.querySelectorAll('input[type=radio]')]
            .find(x => ((x.closest('label') || x.parentElement || {}).innerText || '')
                        .trim().startsWith('Embedded'));
          if (!r) return false;
          (r.closest('label') || r).click(); r.click(); return true;
        });
        if (!mode) {
          await dumpControls(pg, 'db-create-no-secret-mode');
          throw new Error('no Embedded option on the password field');
        }
        await pg.waitForTimeout(1500);

        // The revealed field's id is not knowable in advance; take the first
        // empty password input inside the dialog.
        const passSel = await pg.evaluate(() => {
          const el = [...document.querySelectorAll('input[type=password]')]
            .find(x => !x.disabled && x.offsetParent !== null);
          if (!el) return null;
          if (!el.id) el.id = 'ign-gw-secret-field';
          return '#' + el.id;
        });
        if (!passSel) {
          await dumpControls(pg, 'db-create-no-password-field');
          throw new Error('Embedded selected but no password field appeared');
        }
        await safeFill(pg, passSel, dbPass, 'password');

        // The dialog's submit carries the SAME label as the page button that
        // opened it, so scope to the dialog -- an unscoped match re-opens the
        // form instead of saving. Same trap as gan-connect.
        const saved = await pg.evaluate(() => {
          const dlg = document.querySelector('[role="dialog"], .modal, [class*="Modal"]') || document;
          const el = [...dlg.querySelectorAll('button')]
            .find(e => /create database connection/i.test(e.textContent.trim()) && !e.disabled);
          if (!el) return false;
          el.click(); return true;
        });
        if (!saved) {
          await dumpControls(pg, 'db-create-no-save');
          throw new Error('no enabled Create control on the database form');
        }

        // Poll: the grid re-fetches after the save, so an immediate check reads
        // the pre-save DOM and reports failure on a connection that was created.
        let listed = false;
        for (let i = 0; i < 20 && !listed; i++) {
          await pg.waitForTimeout(1000);
          listed = await exists();
        }
        if (!listed) {
          await dumpControls(pg, 'db-create-not-listed');
          throw new Error(`saved but "${dbName}" is not in the connections list`);
        }
        console.log(`db-create: "${dbName}" created`);
        code = 0;
      }

    } else if (CMD === 'module-install') {
      // Install a .modl the way the gateway's own Config -> Modules page does.
      //
      // WHY NOT scripts/ign-modules.sh: that writes data/modules.json directly.
      // Per the toolkit knowledge base, hand-registering a module "does NOT
      // register it with ModuleManager -- the gateway ignores it completely: no
      // start attempt, no fault, no log line at any level", and it also drops
      // the gateway into COMMISSIONING, which 302s every request (Perspective
      // sessions included) until a human finishes /welcome. This route installs
      // live, with no commissioning gate and no session interruption.
      //
      // The sequence, lifted from ModulesPage.chunk.bundle.js rather than
      // guessed (the endpoints are in a lazily-loaded chunk, not the importmap):
      //
      //   POST /data/api/v1/modules/upload?fileName=<name>   raw file bytes
      //        -> { moduleId, containsCert, certAccepted, containsEula,
      //             licenseAccepted }
      //   POST /data/api/v1/modules/certificate?moduleId=<id>   if unaccepted
      //   POST /data/api/v1/modules/eula?moduleId=<id>          if unaccepted
      //   POST /data/api/v1/modules/install?moduleId=<id>
      //
      // The upload body is BINARY. It cannot go through the page.evaluate/fetch
      // helper above -- a .modl is a zip and any string round-trip corrupts it.
      // Playwright's request context shares the browser's cookies, so it can
      // post the Buffer directly while staying authenticated.
      const file = arg('file');
      if (!file) throw new Error('module-install needs --file <path to .modl>');
      const bytes = fs.readFileSync(file);
      const name = path.basename(file);

      let csrf;
      try {
        csrf = await pg.evaluate(async (timeoutMs) => {
          const s = await fetch('/data/app/session',
            { credentials: 'same-origin', signal: AbortSignal.timeout(timeoutMs) });
          return (await s.json()).csrfToken;
        }, FETCH_TIMEOUT_MS);
      } catch (e) {
        throw describeFailure(`module-install: csrf session fetch (${FETCH_TIMEOUT_MS}ms budget)`, e);
      }
      if (!csrf) throw new Error('no csrfToken on /data/app/session');

      // A .modl can be tens of MB, so this gets a longer, explicit budget than
      // the plain JSON calls above rather than sharing FETCH_TIMEOUT_MS.
      const UPLOAD_TIMEOUT_MS = 60000;
      const post = async (p, data) => {
        const r = await pg.request.post(`${URL}${p}`, {
          headers: {
            'X-CSRF-Token': csrf,
            'X-Requested-With': 'XMLHttpRequest',
            'Content-Type': 'application/octet-stream',
          },
          data: data === undefined ? Buffer.alloc(0) : data,
          timeout: UPLOAD_TIMEOUT_MS,
        });
        const text = await r.text();
        let json = null;
        try { json = JSON.parse(text); } catch (_) { /* not json */ }
        if (r.status() >= 400) {
          throw new Error(`POST ${p} -> ${r.status()} ${text.slice(0, 300)}`);
        }
        return { status: r.status(), json, text };
      };

      console.log(`uploading ${name} (${bytes.length} bytes)`);
      const up = await post(
        `/data/api/v1/modules/upload?fileName=${encodeURIComponent(name)}`, bytes);
      const info = up.json || {};
      const moduleId = info.moduleId;
      if (!moduleId) throw new Error(`upload gave no moduleId: ${up.text.slice(0, 300)}`);
      console.log(`  moduleId=${moduleId} cert=${info.containsCert}/${info.certAccepted} ` +
                  `eula=${info.containsEula}/${info.licenseAccepted}`);

      const q = `?moduleId=${encodeURIComponent(moduleId)}`;
      if (info.containsCert && !info.certAccepted) {
        await post(`/data/api/v1/modules/certificate${q}`);
        console.log('  certificate accepted');
      }
      if (info.containsEula && !info.licenseAccepted) {
        await post(`/data/api/v1/modules/eula${q}`);
        console.log('  licence accepted');
      }
      await post(`/data/api/v1/modules/install${q}`);
      console.log('  install requested');

      // Verify from the module list, not from the install response -- the same
      // rule as every other write here. A module can install and then fault on
      // load, which the POST result cannot tell you.
      await pg.waitForTimeout(6000);
      const healthy = await api(pg, 'GET', '/data/api/v1/modules/healthy');
      const rows = (healthy.json && (healthy.json.items || healthy.json)) || [];
      const mine = (Array.isArray(rows) ? rows : []).filter(
        m => (m.id || m.moduleId) === moduleId);
      if (!mine.length) {
        console.log(`WARNING: ${moduleId} is not in the healthy list -- check ` +
                    `/data/api/v1/modules/quarantined`);
        code = 1;
      } else {
        const m = mine[0];
        console.log(`OK ${m.name || moduleId} ${m.version || ''} state=${m.state || '?'}`);
      }

    } else if (CMD === 'commission') {
      // The "Activate Pending Modules" wizard. While it is open the gateway
      // 302s EVERYTHING here, Perspective sessions included.
      //
      // What it actually asks for: the certFingerprint written into
      // modules.json already satisfies "Trust Certificates" (that section shows
      // 0 on a scripted install). What remains is "Accept License Agreements",
      // one row per module, each behind a Review link -- a human has to accept a
      // licence, which is not something a fingerprint can stand in for.
      await pg.goto(`${URL}/welcome`, { waitUntil: 'domcontentloaded', timeout: 40000 });
      await pg.waitForTimeout(3000);

      const pending = await pg.locator("text=NOT ACCEPTED").count();
      console.log(`commission: ${pending} module licence(s) to accept`);

      // Re-query each pass: accepting one re-renders the table, so a locator
      // list captured up front goes stale after the first click.
      for (let i = 0; i < 20; i++) {
        // Click in page context. Playwright's actionability checks time out on
        // these rows -- the control reports as present but never "stable", and a
        // normal .click() just burns the timeout.
        // Scope to a row that is still NOT ACCEPTED. An accepted row keeps its
        // Review control in the DOM, just disabled -- picking the first "Review"
        // on the page clicks that one, no dialog opens, and the run dies looking
        // for an Accept button that was never going to appear.
        const opened = await pg.evaluate(() => {
          const row = [...document.querySelectorAll('tr')]
            .find(r => /NOT ACCEPTED/i.test(r.textContent));
          if (!row) return false;
          const el = [...row.querySelectorAll('a, button')]
            .find(e => e.textContent.trim() === 'Review');
          if (!el) return false;
          el.click();
          return true;
        });
        if (!opened) break;
        await pg.waitForTimeout(1800);

        // The licence dialog. Tick any consent box, then accept.
        const box = pg.locator("input[type='checkbox']").first();
        if (await box.count() > 0 && !(await box.isChecked().catch(() => true))) {
          await box.check({ timeout: STEP }).catch(() => {});
        }
        const accepted = await pg.evaluate(() => {
          const el = [...document.querySelectorAll('button, a')]
            .find(e => /^(accept|i agree|agree|accept license)$/i.test(e.textContent.trim()));
          if (!el) return false;
          el.click();
          return true;
        });
        if (!accepted) {
          await dumpControls(pg, `licence-dialog-${i}`);
          throw new Error('licence dialog has no Accept control -- see the dump above');
        }
        await pg.waitForTimeout(1800);
      }

      const left = await pg.locator("text=NOT ACCEPTED").count();
      if (left > 0) {
        await dumpControls(pg, 'still-pending');
        throw new Error(`${left} module(s) still NOT ACCEPTED`);
      }

      await pg.evaluate(() => {
        const el = [...document.querySelectorAll('button')]
          .find(e => e.textContent.trim() === 'Finish Setup');
        if (el) el.click();
      });
      console.log('commission: Finish Setup clicked');
      await pg.waitForTimeout(3000);

      // Finish Setup is not the last step: the wizard then shows
      // "SETUP COMPLETED - Start And Launch The Gateway Now?" with a Start
      // Gateway button, and the gateway stays in the commissioning gate until
      // that is pressed too.
      for (let i = 0; i < 10; i++) {
        const started = await pg.evaluate(() => {
          const el = [...document.querySelectorAll('button')]
            .find(e => /start gateway/i.test(e.textContent.trim()));
          if (!el) return false;
          el.click();
          return true;
        });
        if (started) { console.log('commission: Start Gateway clicked'); break; }
        await pg.waitForTimeout(2000);
        await pg.reload({ waitUntil: 'domcontentloaded' }).catch(() => {});
        await pg.waitForTimeout(2000);
      }

      // Done when StatusPing stops reporting the COMMISSIONING sub-state.
      for (let i = 0; i < 60; i++) {
        await pg.waitForTimeout(3000);
        try {
          // Bounded even though the catch below swallows the result either
          // way: without AbortSignal here, a StatusPing that never answers --
          // rather than one that fails fast, which is the normal case during
          // the restart this comment already expects -- would stall this tick
          // forever instead of moving on to the next one.
          const s = await (await fetch(`${URL}/StatusPing`,
            { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) })).json();
          if (s.state === 'RUNNING' && !s.details) {
            console.log(`commission: gateway out of the gate after ~${i * 3}s`);
            code = 0; break;
          }
        } catch (e) { /* it restarts the web context mid-way */ }
      }
      if (code) console.error('commission: still in COMMISSIONING after 3 minutes');

    } else {
      die(`unknown command: ${CMD}`);
    }
  } catch (e) {
    console.error('ign-gw: FAILED -', e.message.split('\n')[0]);
    try { await dumpControls(pg, 'error'); } catch (_) {}
  } finally {
    if (traced.length) {
      console.log(`\n=== API calls (${traced.length}) ===`);
      for (const t of traced) console.log('  ' + t);
    }
    await browser.close();
  }
  process.exit(code);
})();
