#!/usr/bin/env bash
# Shared helpers. Source this, do not execute it.
#
#   . "$(dirname "$0")/lib.sh"

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STACKS_DIR="$REPO_ROOT/stacks"
PROJECTS_DIR="$REPO_ROOT/ignition/projects"
SECRETS_FILE="$REPO_ROOT/.secrets.env"
# Gateway logins and both address forms. Generated by make-env.sh.
GATEWAYS_FILE="$REPO_ROOT/.gateways.env"

# --- stack manifests ---------------------------------------------------------
#
# Every stack describes itself in stacks/<name>/stack.meta -- flat KEY=VALUE,
# grammar in docs/PORTABLE.md, enforced by `make validate`. These helpers are
# the ONLY reader on the bash side; scripts/hosts-setup.ps1 is the PowerShell
# one, and the grammar is exactly what both can read with a line regex.
#
# PARSED, never sourced. Sourcing would execute the file, and the PowerShell
# half could never match sourcing semantics anyway. bash-3.2-safe on purpose
# (sed + sort, no `declare -A`, no `mapfile`): pieces of this run on raw macOS
# hosts, not only inside the toolbox.
meta_get() {  # meta_get <stack> <KEY> [default]
  local f="$STACKS_DIR/$1/stack.meta" v=''
  # A stack parked under labs/ (not yet in demos.json, so not under stacks/,
  # which `make validate` requires to be startable from the console) still
  # answers a lookup BY NAME -- its stanza, say. It is in no enumeration.
  [ -f "$f" ] || f="$REPO_ROOT/labs/$1/stack.meta"
  [ -f "$f" ] && v="$(sed -n "s/^$2=//p" "$f" | head -1 | tr -d '\r')"
  case "$v" in \"*\") v="${v%\"}"; v="${v#\"}" ;; esac  # quoted STATUS_NOTE
  printf '%s' "${v:-${3:-}}"
}

# One stack name per line, sorted by ORDER. Order matters: `depends_on` cannot
# cross Compose projects, so the hub must answer before the spokes dial in and
# Postgres must be up before the hub tries its database connection. The backup
# sits straight after the hub because it registers with the master.
stacks_in_order() {
  local f
  for f in "$STACKS_DIR"/*/stack.meta; do
    [ -f "$f" ] || continue   # an unmatched glob stays literal on bash 3.2
    printf '%s %s\n' "$(sed -n 's/^ORDER=//p' "$f" | head -1 | tr -d '\r')" \
                     "$(basename "$(dirname "$f")")"
  done | sort -n | cut -d' ' -f2
}

# The filters end in `return 0` deliberately: they run under `set -e`, and a
# role that matches nothing (a repo with no backup, say) must be an empty
# answer, not a fatal one.
gateways() {
  local s
  for s in $(stacks_in_order); do
    [ "$(meta_get "$s" KIND)" = gateway ] && printf '%s\n' "$s"
  done
  return 0
}

gateways_with_role() {  # gateways_with_role <hub|backup|edge>
  local s
  for s in $(gateways); do
    [ "$(meta_get "$s" ROLE)" = "$1" ] && printf '%s\n' "$s"
  done
  return 0
}

# Gateways whose manifest KEY equals VALUE ("" matches key-absent). The trap
# these exist to contain: an inline `while ... && echo` filter whose LAST
# candidate is a non-match returns 1, and under `set -e` an array assignment
# from that substitution kills the whole script -- silently, after the
# assignment line. Exactly that happened to sf-gan-history the first time its
# targets were derived inline. Filter through these, never inline.
gateways_where() {  # gateways_where <KEY> <VALUE>
  local s
  for s in $(gateways); do
    [ "$(meta_get "$s" "$1")" = "$2" ] && printf '%s\n' "$s"
  done
  return 0
}

# The Sparkplug demo's edges: isolated gateways that run MQTT Transmission. Not
# every ROLE=edge-isolated gateway is one -- the standalone broker
# (stacks/ignition-broker) is isolated too, and must never receive the `Edge`
# project or a transmitter.
sparkplug_edges() {
  local s
  for s in $(gateways_where ROLE edge-isolated); do
    [ "$(meta_get "$s" MQTT_MODULE)" = transmission ] && printf '%s\n' "$s"
  done
  return 0
}

# The arrays keep their old names and shapes so no consumer changes. Stack
# name and container name are the same string (validate enforces it), which is
# what keeps everything downstream trivial. Word-splitting the command
# substitution is safe by construction: the grammar allows no whitespace in a
# stack name.
STACK_ORDER=( $(stacks_in_order) )
GATEWAYS=( $(gateways) )

# Container name -> the stanza naming it in the gateway credentials file. The
# default of $1 preserves the old case statement's fallthrough: an unknown name
# passes through unchanged, so `--gateway <literal-stanza>` keeps working.
stanza_for() { meta_get "$1" STANZA "$1"; }

# --- the one writable corner of the repo -------------------------------------
#
# wd-control mounts the repo READ-ONLY (stacks/wd-control/compose.yaml) and
# holds the Docker socket, so the less it can rewrite the better. But the demo
# console has to be able to record ONE thing -- which Ignition build to run --
# and that has to be somewhere the terminal reads too, or the page and
# `make up` end up on different versions with nothing to say so.
#
# So: exactly one gitignored directory, mounted rw into wd-control, and nothing
# else in the repo becomes writable. Chosen over the obvious alternative --
# putting the override in each stack's .env -- for two reasons: those live
# under the read-only mount, and four files that must agree can disagree.
# One file cannot.
WD_LOCAL="$REPO_ROOT/.wd-local"
IGN_VERSION_FILE="$WD_LOCAL/ignition-version"

wd_local_dir() {
  # A bind mount whose source is missing makes Docker create it AS ROOT, which
  # then cannot be written by the user who owns the checkout. Creating it here
  # -- from every path that runs before compose -- is what stops that.
  [ -d "$WD_LOCAL" ] || mkdir -p "$WD_LOCAL"
  printf '%s' "$WD_LOCAL"
}

# The chosen Ignition version, or empty. Empty is the norm: the compose files
# carry the repo's declared version as ${IGNITION_VERSION:-<v>} and that is
# what runs unless somebody has asked for something else.
ign_version_override() {
  [ -f "$IGN_VERSION_FILE" ] || return 0
  head -1 "$IGN_VERSION_FILE" | tr -d '[:space:]'
}

# --- settings a machine is allowed to keep -----------------------------------
#
# THE PROBLEM THIS SOLVES. An engineer is meant to open these gateways and change
# things -- that is half of what the MQTT demo is for. The setup scripts then
# write those settings back, because writing only the wanted value is what makes
# them idempotent. So by default a hand change lasts until the next
# `make sparkplug-setup`, and that is correct: the rig has to be able to return
# to a known state.
#
# But a FEW of those values are ones a machine might reasonably want to keep for
# good -- the broker keepalive, how long the rolling buffer holds, whether UDTs
# are converted. For those, the honest answer is that the script should not hold
# the value at all: it should ask here, and this machine's answer should be in a
# file that an update cannot touch.
#
# WHY A NEW FILE, when the repo already has two conventions. Neither fits:
#
#   stacks/<s>/.env      reaches a CONTAINER's environment, and is the right
#                        home for anything compose passes in (WD_MQTT_CUTTABLE
#                        is the worked example). It cannot reach a setting
#                        inside a gateway, because no setup script sources it.
#   stacks/<s>/stack.meta  is TRACKED, so an update overwrites it -- which is
#                        exactly the thing being avoided. It is for the repo's
#                        decisions, not a machine's.
#
# So: one gitignored file at the root, beside .secrets.env and read the same
# way, with a committed template listing every knob and its default. Checked
# 21/09/2026: nothing in this repo previously read a committed non-secret
# settings file, so this is new ground rather than an existing convention.
#
# PRECEDENCE, highest first:
#   1. the ambient environment   KEEPALIVE=20 make mqtt-setup   -- a one-off
#   2. .demo-settings.env        this machine's standing choice
#   3. the default in the call   the repo's opinion
#
# SET-BUT-EMPTY IS A REAL ANSWER, not a missing one. sparkplug-setup.sh already
# relies on it: an empty SPARKPLUG_CONVERT_UDTS means "leave the transmitter's
# setting alone" rather than "write false". So an explicitly empty value short
# circuits here rather than falling through to the default.
SETTINGS_FILE="$REPO_ROOT/.demo-settings.env"

setting() {  # setting <NAME> [default]
  local name="$1" def="${2:-}" v=''
  if [ -n "${!name+x}" ]; then printf '%s' "${!name}"; return 0; fi
  if [ -f "$SETTINGS_FILE" ]; then
    # Last wins, so appending a line overrides an earlier one -- the same
    # behaviour a shell would give, without sourcing the file.
    v="$(sed -n "s/^$name=//p" "$SETTINGS_FILE" | tail -1 | tr -d '\r' || true)"
    if [ -n "$v" ]; then printf '%s' "$v"; return 0; fi
  fi
  printf '%s' "$def"
  return 0
}

# --- which release this checkout is ------------------------------------------
#
# ONE ANSWER, ASKED FOR IN FIVE PLACES. `make status`, `verify-demos`, the login
# banner, the console's version chip and `make release` itself all have to agree
# about what this machine is running, and the way that goes wrong is five
# separate ideas of where to look.
#
# The committed VERSION file carries the last RELEASED version and is written in
# the release commit itself, so a checkout sitting on tag v1.2.0 reads exactly
# `1.2.0`. Everything past that is derived from git, because git is the only
# thing that knows: how many commits the checkout is past its tag, and whether
# somebody has edited it since.
#
#   v1.2.0            on the tag, clean -- a machine running a release
#   v1.2.0+7          seven commits past it (this dev VM tracking main)
#   v1.2.0+7-dirty    ...with uncommitted edits
#   unreleased        no VERSION file at all (a checkout older than the scheme)
#
# Read docs/RELEASING.md for what a release is. The tag is the release; VERSION
# is how a machine with no network tells you which one it has.
VERSION_FILE="$REPO_ROOT/VERSION"

# --no-optional-locks IS LOAD-BEARING. wd-control mounts the repo READ-ONLY
# (stacks/wd-control/compose.yaml) and the toolbox runs as an arbitrary uid, so a
# plain `git status` -- which wants to refresh .git/index -- fails there. Without
# the flag the console's chip would read "unknown" on a perfectly ordinary
# machine, which is exactly the kind of false alarm that teaches people to
# ignore the chip.
# safe.directory is the second half of the same problem. wd-control runs as root
# while the checkout is owned by the host user, and git 2.35+ refuses a repo it
# does not own with "detected dubious ownership" -- on stderr, exit 128, which
# reads as "this is not a git repository". Verified inside the running container
# (21/09/2026): without it every git call there fails; with it all three answer.
_git_ro() {
  git -c "safe.directory=$REPO_ROOT" --no-optional-locks -C "$REPO_ROOT" "$@" 2>/dev/null
}

have_git() {
  command -v git >/dev/null 2>&1 && [ -e "$REPO_ROOT/.git" ]
}

# The bare number, e.g. `1.2.0`, or empty. Empty is a real answer -- a checkout
# from before this scheme has no VERSION file -- so this never dies.
stack_version_number() {
  [ -f "$VERSION_FILE" ] || return 0
  head -1 "$VERSION_FILE" 2>/dev/null | tr -d '[:space:]' || true
  return 0
}

# Commits between the tag for VERSION and HEAD. 0 when the tag is missing (a
# shallow clone, or a machine that fetched no tags), which is the honest answer:
# "cannot count" and "none" both mean there is nothing extra to report.
stack_version_ahead() {
  local ver n=0
  ver="$(stack_version_number)"
  if [ -n "$ver" ] && have_git && _git_ro rev-parse -q --verify "refs/tags/v$ver" >/dev/null; then
    n="$(_git_ro rev-list --count "v$ver..HEAD" || echo 0)"
  fi
  case "$n" in ''|*[!0-9]*) n=0 ;; esac
  printf '%s' "$n"
  return 0
}

# 1 if the working tree has uncommitted changes, else 0.
stack_version_dirty() {
  local out=''
  if have_git; then out="$(_git_ro status --porcelain | head -1 || true)"; fi
  if [ -n "$out" ]; then printf '1'; else printf '0'; fi
  return 0
}

# The one string every surface prints. Always succeeds, always prints something.
stack_version() {
  local ver n dirty out
  ver="$(stack_version_number)"
  if [ -z "$ver" ]; then printf 'unreleased'; return 0; fi
  n="$(stack_version_ahead)"
  dirty="$(stack_version_dirty)"
  out="v$ver"
  # `if`, not `[ ... ] && out=...`: a && list whose test fails IS the whole
  # statement, so under `set -e` a clean checkout on its tag would end the
  # caller here -- the trap CLAUDE.md names, and this function is called from
  # `make status`, which is the first thing this repo tells anyone to run.
  if [ "$n" -gt 0 ];   then out="$out+$n"; fi
  if [ "$dirty" = 1 ]; then out="$out-dirty"; fi
  printf '%s' "$out"
  return 0
}

# --- output ------------------------------------------------------------------

if [ -t 1 ]; then
  C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'
  C_RED=$'\033[31m'; C_GRN=$'\033[32m'; C_YEL=$'\033[33m'; C_BLU=$'\033[34m'
else
  C_RESET=''; C_BOLD=''; C_DIM=''; C_RED=''; C_GRN=''; C_YEL=''; C_BLU=''
fi

say()  { printf '%s==>%s %s\n' "$C_BLU$C_BOLD" "$C_RESET" "$*"; }
ok()   { printf '%s  ok%s %s\n' "$C_GRN" "$C_RESET" "$*"; }
warn() { printf '%swarn%s %s\n' "$C_YEL" "$C_RESET" "$*" >&2; }
die()  { printf '%sfail%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; exit 1; }
dim()  { printf '%s%s%s\n' "$C_DIM" "$*" "$C_RESET"; }

# --- preconditions -----------------------------------------------------------

# How much RAM is actually available to Docker, in whole GB, or "" if the
# question cannot be answered here.
#
# /proc/meminfo from inside the toolbox is the RIGHT source: the kernel does
# not namespace it, so on Linux this is the host and under Docker Desktop it is
# the WSL2/HyperKit VM's allocation -- which is exactly the pool the containers
# compete for. MemAvailable, not MemFree: free memory excludes reclaimable page
# cache and reads near zero on any warm machine.
host_available_gb() {
  [ -r /proc/meminfo ] || return 0
  awk '/^MemAvailable:/ { printf "%d", $2 / 1024 / 1024; exit }' /proc/meminfo 2>/dev/null
}

# Say something BEFORE starting a lot of containers on a machine that cannot
# hold them. Not a block by default: this stack runs on hosts whose memory we
# cannot see accurately, and a false refusal is worse than a warning nobody
# needed. It IS fatal below the floor, because at that point the next thing to
# happen is the host swapping -- and what dies is usually not this stack.
#
# Written after a full start on the machine hosting a VM drove it into swap and
# took the VM down. Nothing warned anybody; nothing knew how big the host was.
#   memory_check <gb this is about to need> <what is being started>
memory_check() {
  local need="$1" what="$2" avail floor=2
  avail="$(host_available_gb)"
  [ -n "$avail" ] || return 0                      # unknown -- say nothing
  [ "$avail" -lt "$need" ] || return 0             # fits -- say nothing

  warn "$what wants about ${need} GB and this machine has ${avail} GB free."
  if [ "${WD_IGNORE_MEMORY:-}" = "1" ]; then
    warn "WD_IGNORE_MEMORY=1 -- continuing anyway."
    return 0
  fi
  if [ "$avail" -lt "$floor" ]; then
    die "refusing to start: under ${floor} GB free the host swaps, and what
     stops responding is usually something else on the machine. Close things,
     or run one demo at a time:  wd core  then  wd demo-start DEMO=<id>
     Override with WD_IGNORE_MEMORY=1 if you know better than this check."
  fi
  warn "Continuing, but prefer 'wd core' + 'wd demo-start DEMO=<id>' on a"
  warn "machine this size -- one demonstration needs a fraction of the whole."
}

need_docker() {
  command -v docker >/dev/null 2>&1 || die "docker is not installed or not on PATH"
  docker info >/dev/null 2>&1 || die "cannot talk to the Docker daemon (is it running?)"
}

# `backbone` is created once, outside any Compose project, and every stack joins
# it as external. Recreating it means every stack must be restarted to rejoin --
# which is why nothing here ever removes it, `destroy-all` included: the toolbox
# itself is attached to it while it runs.
ensure_backbone() {
  if ! docker network inspect backbone >/dev/null 2>&1; then
    say "creating the shared 'backbone' network"
    docker network create backbone >/dev/null
    ok "backbone created"
  fi
  ensure_mqtt_net
}

# `wd-mqtt` carries MQTT and nothing else: the hub pair's Distributor answers on
# it as mqtt-master / mqtt-backup, names that exist on no other network, and
# every MQTT-speaking edge dials only those. So `docker network disconnect
# wd-mqtt <edge>` cuts one edge off the broker while it stays on backbone for
# the console's observer (docs/MQTT-DISTRIBUTOR.md T-D12). Created here, beside
# backbone and for the same reason: every stack that joins it declares it
# external, so no one stack's `down` can remove it from under the others.
MQTT_NET=wd-mqtt
ensure_mqtt_net() {
  if ! docker network inspect "$MQTT_NET" >/dev/null 2>&1; then
    say "creating the MQTT-only '$MQTT_NET' network"
    docker network create "$MQTT_NET" >/dev/null
    ok "$MQTT_NET created"
  fi
}

# The broker login every MQTT client in the stack uses. The password is the
# generated MQTT_PASSWORD in .secrets.env (make-env.sh generates it on its own,
# no stack's .env carries it).
mqtt_user() {
  local v=""
  [ -f "$SECRETS_FILE" ] && v="$(grep -E '^MQTT_USER=' "$SECRETS_FILE" | head -1 | cut -d= -f2- || true)"
  printf '%s' "${v:-ignition}"
}

# A stack folder is valid only if it has a compose file.
stack_path() {
  local s="$1" p="$STACKS_DIR/$1"
  [ -d "$p" ] || die "no such stack: $s (looked in $STACKS_DIR)"
  [ -f "$p/compose.yaml" ] || die "stack '$s' has no compose.yaml"
  printf '%s' "$p"
}

# Expand "all" to every stack in dependency order; otherwise validate what was asked.
resolve_stacks() {
  if [ $# -eq 0 ] || [ "${1:-}" = "all" ]; then
    printf '%s\n' "${STACK_ORDER[@]}"
  else
    local s
    for s in "$@"; do stack_path "$s" >/dev/null; printf '%s\n' "$s"; done
  fi
}

# --- gateways ----------------------------------------------------------------

# Gateway containers share a name with their stack, which keeps this trivial.
gateway_running() {
  [ "$(docker inspect -f '{{.State.Running}}' "$1" 2>/dev/null || echo false)" = "true" ]
}

require_gateway() {
  gateway_running "$1" || die "gateway container '$1' is not running (try: make up)"
}

# Wait until a gateway reports RUNNING, not merely until the container starts --
# an Ignition gateway accepts TCP long before it will serve a project scan.
wait_for_gateway() {
  local c="$1" timeout="${2:-300}" waited=0
  say "waiting for '$c' to reach RUNNING (timeout ${timeout}s)"
  while [ "$waited" -lt "$timeout" ]; do
    # Command substitution rather than a `| grep -q` pipeline: under
    # `set -o pipefail` grep -q exits early, SIGPIPEs the producer and returns
    # 141, so the test can read false while the gateway is actually up.
    # --max-time: without it, a gateway that accepts the connection and never
    # answers hangs this curl forever, and the outer `timeout` above is only
    # ever checked BETWEEN iterations -- one call that never returns is not a
    # call it can bound. Same class of bug as the ign-gw.js fetches, fixed the
    # same day (18/09/2026) after a swap-and-hand-back command hung ~1h on exactly this.
    ping="$(docker exec "$c" curl -fsS --max-time 5 "http://localhost:8088/StatusPing" 2>/dev/null || true)"

    case "$ping" in
      # A gateway waiting on third-party module certificate acceptance answers
      # {"state":"RUNNING","details":"COMMISSIONING"} while 302-redirecting every
      # other request to /welcome. Matching RUNNING alone would call that ready.
      *COMMISSIONING*)
        warn "$c is RUNNING but stuck in COMMISSIONING -- it is serving nothing else."
        warn "Finish the wizard at /welcome, or back out the modules.json change."
        return 1
        ;;
      *RUNNING*)
        ok "$c is RUNNING (${waited}s)"
        return 0
        ;;
    esac

    sleep 5; waited=$((waited + 5))
  done
  die "'$c' did not reach RUNNING within ${timeout}s -- check: docker logs $c"
}

# The base URL of a gateway, read from the one file that already knows.
#
# `.gateways.env` lists each gateway twice -- `.url` by container name on the
# backbone network, `.hosturl` by whatever host port this machine publishes --
# and WD_TOOLBOX says which of the two applies. Inside the toolbox `localhost`
# is the toolbox itself, so a host-port URL there is not merely wrong, it
# reaches nothing and reads as "the gateway is down".
#
# Every script asks here rather than keeping its own map. There were three such
# maps, each with its own idea of the default ports, and adding the redundant
# backup meant `ign-trial.sh` reporting `http://localhost:` with no port at all
# -- a gateway that looked unreachable because a lookup had quietly missed.
gateway_url() {
  local container="$1" stanza key value
  stanza="$(stanza_for "$container")"
  key="hosturl"; [ "${WD_TOOLBOX:-}" = "1" ] && key="url"

  [ -f "$GATEWAYS_FILE" ] \
    || die "no .gateways.env -- it is generated: run 'make env'"

  value="$(grep -E "^${stanza}\.${key}=" "$GATEWAYS_FILE" | head -1 | cut -d= -f2-)"
  [ -n "$value" ] \
    || value="$(grep -E "^${stanza}\.url=" "$GATEWAYS_FILE" | head -1 | cut -d= -f2-)"
  [ -n "$value" ] || die "no URL for gateway '$container' (stanza '$stanza') in .gateways.env"
  printf '%s' "${value%/}"
}

# --- the demo console --------------------------------------------------------
#
# Where wd-control answers. Two address forms, for the same reason
# `.gateways.env` carries two: by container name on the backbone from inside the
# toolbox, by published port from the host. Both scripts/wd-demos.sh and
# scripts/verify-demos.sh ask here rather than each keeping a copy -- the port
# lives in stack.meta, and a second copy of it is a second thing to be wrong the
# day it moves.
control_base() {
  if [ "${WD_TOOLBOX:-}" = "1" ]; then
    printf 'http://wd-control:8080'
  else
    printf 'http://localhost:%s' "$(meta_get wd-control PORT_DEFAULT 8485)"
  fi
}

# Which demos have been ASKED for, one id per line.
#
# READ-ONLY, and it never starts anything. The exit code carries the part that
# matters: 0 with no output means "the console is up and you have asked for
# nothing", 1 means "the console could not say". A caller that cannot tell those
# apart will treat a healthy idle machine as an unknown one.
control_wanted() {
  local out
  out="$(curl -fsS --max-time 5 "$(control_base)/state" 2>/dev/null)" || return 1
  printf '%s' "$out" | python3 -c '
import json, sys
try:
    s = json.load(sys.stdin)
except Exception:
    raise SystemExit(1)
for d in s.get("demos", []):
    if d.get("wanted"):
        print(d["id"])
'
}

# The repo's path AS THE DOCKER DAEMON SEES IT.
#
# Needed by exactly one stack: wd-control runs the repo's own scripts, so it has
# to bind-mount the repo -- and a bind mount is resolved by the DAEMON, not by
# whoever typed the command. From the host that is simply $REPO_ROOT. From
# inside the toolbox, $REPO_ROOT is /work, a path the daemon has never heard of,
# and Docker does not fail on a missing bind source: it silently creates an
# EMPTY one, which is how three stacks came up healthy and did nothing.
#
# So ask Docker. The toolbox is itself a container with the repo mounted at
# /work, and the daemon knows where that mount came from.
host_repo_path() {
  local cid src
  if [ "${WD_TOOLBOX:-}" != "1" ]; then
    printf '%s' "$REPO_ROOT"
    return 0
  fi
  cid="$(cat /etc/hostname 2>/dev/null || true)"
  src="$(docker inspect "$cid" \
          --format '{{range .Mounts}}{{if eq .Destination "/work"}}{{.Source}}{{end}}{{end}}' \
          2>/dev/null || true)"
  [ -n "$src" ] || die "cannot work out this repo's path on the host -- run wd-control from the host, or report this"
  printf '%s' "$src"
}

# Copy a local directory into a named Docker volume.
#
# THIS EXISTS BECAUSE A RELATIVE BIND MOUNT IS RESOLVED BY THE CLIENT, NOT THE
# DAEMON, and inside the toolbox the client's filesystem is not the host's.
#
# `- ./initdb:/docker-entrypoint-initdb.d:ro` in a compose file means "the
# initdb directory next to this compose file" -- as seen by whatever is running
# `docker compose`. Run from the host that is the repo; run from the toolbox it
# becomes `/work/stacks/postgres/initdb`, a path the daemon has never heard of.
# And Docker does not fail on a missing bind source: it CREATES AN EMPTY
# DIRECTORY. So the old EMQX broker started with no certificates and crash-looped, and Postgres
# started with no init scripts and came up healthy with none of its databases --
# the second of which is completely silent. Found 05/08/2026 on the first
# from-scratch run on a second machine; every earlier test had the stacks
# already running from a native `make up`, which is why it never showed.
#
# The fix is to stop bind-mounting host paths at all. `docker cp` streams from
# the CLIENT's filesystem to the daemon, so it works identically whether the
# daemon is local, in a VM, or on another machine -- no path translation, no
# guessing what Docker Desktop does with `C:\...` when the client is a Linux
# container. The volume is created by `docker create` if it does not exist.
seed_volume() {  # seed_volume <volume> <local-dir>
  local volume="$1" src="$2" cid

  [ -d "$src" ] || die "nothing to seed from: $src"

  # Refuse to copy a .env. Seeding a whole stack directory is the obvious thing
  # to write and it sweeps the stack's .env -- every password in it -- into a
  # Docker volume that is then mounted into a container. That happened here
  # during development and was caught by looking, not by any check; this is the
  # check. Seed a directory that contains ONLY what the container should see.
  if [ -e "$src/.env" ]; then
    die "refusing to seed '$src' into volume '$volume': it contains a .env.
     Seeding copies the whole directory, so every secret in that file would end
     up inside the container. Point this at a directory holding only the files
     the container needs."
  fi

  # A throwaway container purely to give `docker cp` a destination inside the
  # volume. It is never started; `docker create` is enough to mount and to
  # bring the volume into existence.
  cid="$(docker create -v "$volume":/seed alpine:3.20 true)" \
    || die "could not create the helper container for volume '$volume'"

  # `/.` copies the CONTENTS of the directory rather than the directory itself.
  # Without the dot you get /seed/certs/... and the mount is one level out,
  # which presents as the same empty-directory symptom this function exists to
  # fix.
  if ! docker cp "$src/." "$cid":/seed/ >/dev/null; then
    docker rm -f "$cid" >/dev/null 2>&1 || true
    die "could not copy $src into volume '$volume'"
  fi
  docker rm -f "$cid" >/dev/null 2>&1 || true
}

# The volumes whose contents are owned by the repo, and where each is filled
# from. One table, read by both `bootstrap` and `stack.sh up`, because these two
# drifting apart is precisely how the bug above survived: a `make up` that
# skipped the seeding would mount an empty volume and the container would either
# crash-loop (the broker) or come up healthy and wrong (Postgres).
#
# Every entry is required by the container that mounts it, so a missing source
# is fatal rather than skipped -- an empty mount is the failure this exists to
# prevent. Two of the three are committed files and cannot be missing; the
# broker's certificates are generated, which is the one that ever fires.
# volume|source pairs, derived from every manifest that declares seeding.
seeded_volumes() {
  local s v
  for s in $(stacks_in_order); do
    v="$(meta_get "$s" SEED_VOLUME)"
    [ -n "$v" ] && printf '%s|%s/%s\n' "$v" "$s" "$(meta_get "$s" SEED_SRC)"
  done
  return 0
}

seed_all() {
  local volume src
  while IFS='|' read -r volume src; do
    [ -n "$volume" ] || continue
    [ -d "$STACKS_DIR/$src" ] \
      || die "cannot seed volume '$volume': $STACKS_DIR/$src does not exist.
     The broker's certificates are generated rather than committed -- run
     'make certs', or './wd bootstrap' to build the whole stack."
    seed_volume "$volume" "$STACKS_DIR/$src"
    ok "$volume"
  done <<EOF
$(seeded_volumes)
EOF
}

# --- secrets -----------------------------------------------------------------

# Read one value out of the gitignored root .secrets.env.
secret() {
  [ -f "$SECRETS_FILE" ] || die "no .secrets.env -- run: make env"
  local v
  v="$(grep -E "^$1=" "$SECRETS_FILE" | head -1 | cut -d= -f2-)" || true
  [ -n "$v" ] || die "'$1' is not set in .secrets.env"
  printf '%s' "$v"
}

# Seconds of Perspective trial left on a gateway, or -1 if that cannot be read.
#
# `GET /data/api/v1/trial` is an OPEN_ROUTE, so this needs no credentials on any
# of the four gateways -- which is what makes it usable from a poll loop.
#
# ALWAYS returns 0 and always prints an integer. That is deliberate: every
# caller assigns this in a command substitution, and under `set -euo pipefail` a
# helper that returns non-zero for a legitimate outcome kills the whole script
# at the point it just did its job (see the table in CLAUDE.md). "Unreadable" is
# a legitimate outcome here -- a gateway that is still starting answers 503 with
# an HTML page -- so it is reported as -1, and the caller decides.
trial_seconds() {  # trial_seconds <container>
  local json
  json="$(curl -s --max-time 5 "$(gateway_url "$1")/data/api/v1/trial" 2>/dev/null || true)"
  printf '%s' "$json" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
    print(0 if d.get("expired") else int(d.get("trialSecondsLeft", 0)))
except Exception:
    print(-1)
' 2>/dev/null || echo -1
}
