#!/usr/bin/env bash
#
# Arm store-and-forward on the edge transmitters.
#
#   scripts/sf-arm.sh [gateway ...]      default: both edges
#   scripts/sf-arm.sh --check            REPORT the history store only
#
# --check COVERS STEP 1 AND NOTHING ELSE, and that is not a shortcut. Step 1 has
# a real want/have (the `want` block below), so it can be compared without
# writing. Steps 2 and 3 CANNOT: the transmitter is re-saved unconditionally BY
# DESIGN -- that re-save IS step 3, and skipping it when the value looks right is
# precisely how a gateway ends up armed-looking with historyFlushType=NONE
# underneath. So a re-run rewriting the transmitter is not drift, and --check
# does not pretend to judge it. scripts/drift.sh reports it as not compared.
#
# Until this has run, cutting an edge off the broker LOSES its data instead of
# buffering it -- and every part of the system reports success while it happens.
# Three settings have to line up, and they are checked in this order because the
# third depends on the first two:
#
#   1. the history store resource must be `enabled` -- it ships DISABLED, and
#      `enabled` lives in resource.json, so the store's own config.json looks
#      perfectly healthy either way;
#   2. the transmitter must NAME that store in `historyStore` -- absent by
#      default, and with none the module quietly builds a NoOpHistoryStore;
#   3. the transmitter must then be RE-SAVED, because its flush type is computed
#      once, when the Transmitter object is built, from the store's `enabled`
#      attribute as it stood at that moment.
#
# Step 3 is the one that will catch you. Enabling the store restarts the
# transmission CLIENT, so the log starts saying `historyEnabled=true` and
# everything looks armed -- but the Transmitter still holds the flush type it
# computed while the store was disabled, and that value is NONE:
#
#     if ((!isConnected() || !isConnectedToPrimaryHost())
#             && historyFlushType == NONE) {
#         return;      // the payload is DROPPED, at debug level
#     }
#
# So the only difference between working and silently discarding everything is
# one word in one log line at connect time:
#
#     Handling transition to online with ... historyEnabled=true, historyFlushType=ASYNC
#                                                                              ^^^^^ not NONE
#
# which is exactly what this script waits for before reporting success.

. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

STORE="Default In-Memory Store"
# A knob, not a constant: one of the handful of values a machine may keep across
# an update (demo-settings.env.example, and the table in docs/RELEASING.md).
# See the history store step below, and the >= 1.5x keepalive rule with it.
ROLLING_MAX_AGE="$(setting ROLLING_MAX_AGE 60)"   # seconds
MODULE="com.cirruslink.mqtt.transmission.gateway"

# Only `--check` is intercepted; every other word still becomes a target, so
# `$#` below still means "was a gateway named" exactly as it did.
CHECK=0
DRIFT=0
ARGS=()
for a in "$@"; do
  case "$a" in
    --check) CHECK=1 ;;
    *)       ARGS+=( "$a" ) ;;
  esac
done
set -- ${ARGS[@]+"${ARGS[@]}"}

# stanza names in .gateways.env (generated by make-env.sh), and their containers
# stanza_for lives in lib.sh -- see the note in ign-trial.sh about four copies.

# Only the edges that DEMONSTRATE the MQTT road get an armed transmitter.
#
# Both edges carry the Transmission module -- that is what MQTT_MODULE says, and
# it stays true -- but the Gateway Network edge is supposed to have exactly one
# transport, which is the whole point of running the demonstration twice by two
# mechanisms. It did not: its transmitter shipped enabled like the other one, so
# it published Sparkplug as well, the hub's MQTT Engine mirrored a second edge
# node nobody mentions, and every sample was filed twice under two driver rows.
#
# Nothing failed, which is why it survived: cutting the Gateway Network link
# still emptied the Site 1 card and still gapped the trend, because both read
# the GAN road. The MQTT copy just kept flowing underneath, quietly making
# "cut Site 1 and it stops reaching the hub" untrue.
TARGETS=("$@")
[ ${#TARGETS[@]} -eq 0 ] && TARGETS=( $(gateways_where SF_TRANSPORT mqtt) )

# The other side of the same coin: a gateway that carries the module but does
# not demonstrate the MQTT road must have its transmitter DISABLED, not merely
# left unarmed. Written every run, because "we never enabled it" is not a state
# anything maintains -- it shipped enabled.
DISABLE=()
[ $# -eq 0 ] && DISABLE=( $(gateways_where SF_TRANSPORT gan) )

need_docker
cd "$REPO_ROOT"

WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

api() {  # api <stanza> <method> <path> [body-file]
  local stanza="$1" method="$2" path="$3" body="${4:-}"
  if [ -n "$body" ]; then
    node scripts/ign-gw.js api --gateway "$stanza" --method "$method" \
      --path "$path" --body-file "$body" 2>&1
  else
    node scripts/ign-gw.js api --gateway "$stanza" --path "$path" 2>&1
  fi
}

for container in "${TARGETS[@]}"; do
  stanza="$(stanza_for "$container")"
  [ -n "$stanza" ] || die "no gateway stanza known for '$container'"
  # A down gateway is a normal outcome for a CHECK -- the MQTT edge is a demo
  # stack and is usually stopped -- so it is skipped rather than fatal. The
  # apply path still requires it: arming a gateway that is not there is not a
  # thing to be tolerant about.
  if [ "$CHECK" -eq 1 ] && ! gateway_running "$container"; then
    dim "  $container is not running -- skipped"
    continue
  fi
  require_gateway "$container"

  say "$container"

  # --- 1. the history store ---------------------------------------------------
  api "$stanza" GET "/data/api/v1/resources/list/$MODULE/history-store" \
    | tail -1 > "$WORK/store.json"

  # The Rolling History Buffer rides on the same resource. It keeps every tag
  # change for the last ROLLING_MAX_AGE seconds whatever the connection state
  # and replays it as historical on every reconnect, so what the edge sent into
  # a broker that was standing down -- a hub handover, where the old half stops
  # consuming seconds before it says so -- arrives anyway. Without it a planned
  # handover lost an alarm activation in two of six; with it none did
  # (docs/MQTT-DISTRIBUTOR.md T-D11). Max age >= 1.5 x the servers' keepalive
  # (10 s, ign-mqtt.sh), which also covers a cut edge's blind seconds (T-D12).
  # The replays duplicate rows the hub already has; the history table ignores
  # them (scripts/pg-history-guard.sh).
  want="$(python3 - "$WORK/store.json" "$WORK/store-put.json" "$STORE" "$ROLLING_MAX_AGE" <<'PY'
import json, sys
src, dst, name, age = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])
items = json.load(open(src)).get("items", [])
row = next((i for i in items if i["name"] == name), None)
if row is None:
    print("missing"); raise SystemExit
cfg = dict(row["config"])
want = {"rollingHistoryBufferEnabled": True, "rollingHistoryMaxAge": age}
diff = [k for k, v in want.items() if cfg.get(k) != v]
if not row.get("enabled"):
    diff.insert(0, "enabled")
cfg.update(want)
json.dump([{"name": row["name"], "description": row["description"],
            "enabled": True, "config": cfg,
            "signature": row["signature"]}], open(dst, "w"))
print(",".join(diff) or "-")
PY
)"

  # THE GATE. `want` is the whole comparison; under --check we report it and go
  # no further -- steps 2 and 3 below write every run by design (see the header).
  if [ "$CHECK" -eq 1 ]; then
    case "$want" in
      missing)
        printf '  drift: %s has no MQTT Transmission history store named %s -- without one the module builds a NoOpHistoryStore and a cut edge LOSES its data\n' \
          "$container" "$STORE"
        DRIFT=1 ;;
      -)
        ok "$container history store '$STORE' enabled, rolling buffer ${ROLLING_MAX_AGE}s" ;;
      *)
        printf '  drift: %s history store %s differs in %s (Connections > MQTT Transmission > History Stores)\n' \
          "$container" "$STORE" "$want"
        DRIFT=1 ;;
    esac
    continue
  fi

  case "$want" in
    missing) die "no history store named '$STORE' on $container" ;;
    -)       dim "  history store '$STORE' already enabled, rolling buffer ${ROLLING_MAX_AGE}s" ;;
    *)
      api "$stanza" PUT "/data/api/v1/resources/$MODULE/history-store" "$WORK/store-put.json" \
        | grep -q '"success": true' || die "could not set the history store on $container"
      ok "history store '$STORE' set ($want): enabled, rolling buffer ${ROLLING_MAX_AGE}s" ;;
  esac

  # --- 2 & 3. the transmitter -------------------------------------------------
  # Written unconditionally, even when historyStore already names the store:
  # this IS step 3, and skipping it when the value looks right is precisely how
  # a gateway ends up armed-looking and NONE underneath.
  api "$stanza" GET "/data/api/v1/resources/list/$MODULE/transmitter" \
    | tail -1 > "$WORK/tx.json"

  python3 - "$WORK/tx.json" "$WORK/tx-put.json" "$STORE" <<'PY' || die "no transmitter on $container"
import json, sys
src, dst, store = sys.argv[1], sys.argv[2], sys.argv[3]
items = json.load(open(src)).get("items", [])
if not items:
    sys.exit(1)
row = items[0]
cfg = dict(row["config"])
cfg["historyStore"] = store
# Alarm events ride the same road as the values: without this the alarmed tag
# reaches the hub and its alarm never does (ships false). Journaled locally
# first, so the evidence table can show the edge's own record beside the hub's.
cfg["alarmEventEnable"] = True
cfg["alarmJournalName"] = "EdgeJournal"
json.dump([{"name": row["name"], "description": row["description"],
            "enabled": row["enabled"], "config": cfg,
            "signature": row["signature"]}], open(dst, "w"))
PY

  api "$stanza" PUT "/data/api/v1/resources/$MODULE/transmitter" "$WORK/tx-put.json" \
    | grep -q '"success": true' || die "could not save the transmitter on $container"
  ok "transmitter saved with historyStore='$STORE'"

  # --- verify from the log, not the response code -----------------------------
  # The transmitter restarts and reconnects; the flush type only appears on the
  # transition-to-online line, so give it a moment to get there.
  say "waiting for the flush type"
  armed=""
  for _ in $(seq 1 20); do
    line="$(docker logs --tail 400 "$container" 2>&1 \
            | grep 'Handling transition to online' | tail -1 || true)"
    case "$line" in
      *historyFlushType=ASYNC*|*historyFlushType=IN_ORDER*) armed="$line"; break ;;
    esac
    sleep 3
  done

  if [ -n "$armed" ]; then
    ok "store and forward is armed -- ${armed##*Handling transition to online with }"
  else
    warn "$container still reports historyFlushType=NONE"
    dim "  the last transition line was:"
    dim "  ${line:-<none found>}"
    die "store and forward is NOT armed on $container"
  fi
done

if [ "$CHECK" -eq 1 ]; then
  # `if`, not `&&` -- see CLAUDE.md on a && list taking over the exit status.
  if [ "$DRIFT" -ne 0 ]; then exit 1; fi
  exit 0
fi

# --- take the Gateway Network edges OFF the broker ----------------------------
for container in ${DISABLE[@]+"${DISABLE[@]}"}; do
  stanza="$(stanza_for "$container")"
  gateway_running "$container" || { warn "$container is not running -- skipped"; continue; }
  say "$container demonstrates the Gateway Network road -- disabling its transmitter"

  api "$stanza" GET "/data/api/v1/resources/list/$MODULE/transmitter" \
    | tail -1 > "$WORK/tx-off.json"

  # Prints "already off" and writes nothing when it is already disabled, so this
  # is quiet on every run after the first.
  state="$(python3 - "$WORK/tx-off.json" "$WORK/tx-off-put.json" <<'PY2'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
items = json.load(open(src)).get("items", [])
if not items:
    print("none"); raise SystemExit
row = items[0]
if not row.get("enabled"):
    print("already off"); raise SystemExit
# `enabled` is a top-level attribute of the resource, not a config setting --
# the same distinction that costs three separate traps when toggling one from
# Jython (see CLAUDE.md). Over REST it is simply this field.
json.dump([{"name": row["name"], "description": row["description"],
            "enabled": False, "config": row["config"],
            "signature": row["signature"]}], open(dst, "w"))
print("disable")
PY2
)"

  case "$state" in
    none)         warn "$container has no transmitter resource" ;;
    "already off") ok "transmitter already disabled" ;;
    disable)
      api "$stanza" PUT "/data/api/v1/resources/$MODULE/transmitter" "$WORK/tx-off-put.json" \
        | grep -q '"success": true' \
        || die "could not disable the transmitter on $container"
      ok "transmitter disabled -- this edge now has exactly one transport"
      ;;
  esac
done

echo
say "verify it end to end with a real outage"
dim "  break an edge from the Store & Forward page, wait, let it restore, then:"
dim "  the trend fills its own gap in, and the historian shows no missing seconds"
