"""Store & Forward: what the hub can see, and how to break the link on purpose.

The demonstration is one sentence long -- *cut an edge off, watch it keep
collecting, restore it, watch the missing data arrive with its original
timestamps* -- and everything here exists to make that sentence visible on one
page.

WHAT MAKES IT WORK AT ALL

Two settings, both of which were off and both of which fail silently:

  * The transmitter had no `historyStore`. With none, MQTT Transmission builds a
    NoOpHistoryStore and logs `historyEnabled=false` -- a broken link simply
    LOSES data, and the only sign is one line at connect time.
  * The store itself was `enabled: false`. Naming it in the transmitter is not
    enough; a disabled store resolves to null and you are back to the no-op.

Both live on the edges, not in this repo -- see docs/STORE-FORWARD.md.

BREAKING THE LINK

The MQTT edge is cut off the network its broker is on, not disabled: wd-control
disconnects its container from `wd-mqtt` (the network that carries MQTT only)
and reconnects it when the deadline passes. The edge keeps running and keeps
collecting, cannot reach the broker, and buffers to its history store -- what a
customer sees when a WAN link drops. The broker, MQTT Distributor on the hub
pair, has no per-client kick, which is why it is the network and not the broker
(docs/MQTT-DISTRIBUTOR.md, T-D12). Two things worth knowing here:

  * wd-control keeps the deadline on its own volume, so a 60-second break heals
    itself even if the browser is closed, the gateway restarts or wd-control
    does -- see control/mqttcut.py.
  * The cloud does not notice at once: the broker notices the silence after
    1.5 x keepalive (10 s) and sends the edge's Last Will, about 15 s in.

WHICH EDGE IS WHICH

The Sparkplug edge node id is generated by Transmission ("Edge Node e055db"),
so it identifies a node but not a container. Each edge therefore publishes its
own address as a metric (edge_stream.ADDRESS_TAG) and the hub matches that
against the addresses its EAM agent hostnames resolve to, to find its row. The
cut itself names the edge's STACK, from TRANSPORTS.

Jython 2.7: `except X, e`, and Java exceptions are not Exception subclasses.
"""
from java.lang import Throwable as JThrowable

import gateway_admin

LOG = "SFDemo"

# MQTT Engine's mirror of what the MQTT edge publishes.
SF_ROOT = "[MQTT Engine]Edge Nodes"
SF_GROUP = "My MQTT Group"
SF_DEVICE = "Demo"
SF_SIGNALS = ["FlowRate", "Pressure", "Temperature"]
ADDRESS_TAG = "Address"
PACK_TAG = "Pack"

# The two edges reach the hub by DIFFERENT roads, which is the point of the
# page: one Sparkplug over MQTTS through the broker, one straight over the
# Gateway Network. Everything that differs between them lives here.
#
#   gan   the hub mounts the edge's own provider as [Edge1], so its values are
#         read directly; the edge historises locally and Ignition's own store
#         and forward syncs that to the hub's historian.
#   mqtt  the edge publishes Sparkplug; MQTT Engine mirrors it under
#         [MQTT Engine]Edge Nodes/..., and the hub historises what arrives.
#
# Breaking them differs too -- see break_link.
#   history  where the hub's own historian filed this edge's data. The two
#            roads arrive under DIFFERENT driver rows, so the trend cannot
#            build one path shape for both -- see _history_path.
TRANSPORTS = [
    {"agent": "Ignition-Edge1", "site": "Site1", "transport": "gan",
     "label": "GATEWAY NETWORK", "short": "GAN",
     "root": "[Edge1]MQTT Tags/Demo",
     "historyDriver": ("ignition-edge1", "edge"),
     "historyRoot": "MQTT Tags/Demo",
     "detail": "Gateway Network -> ignition:8060"},
    {"agent": "Ignition-Edge2", "site": "Site2", "transport": "mqtt",
     "label": "MQTT OVER TLS", "short": "MQTTS",
     "root": None,
     "historyDriver": None,
     "historyRoot": None,
     # The stack wd-control cuts off wd-mqtt (control/mqttcut.py).
     "stack": "ignition-edge2",
     "detail": "Sparkplug B over ssl://mqtt-master:8883"},
]

# Presentation for the cards' metric tiles: short name, unit, decimals. The
# signals themselves are defined by edge_stream on the edges; this is only how
# the hub chooses to label them.
#
# The degree sign is a \u escape rather than a literal: the source has no
# coding declaration, so Jython reads it as ASCII, and a raw UTF-8 byte pair
# survives as far as the browser before rendering as "A°C".
SIGNAL_META = {
    "FlowRate":    ("FLOW", "L/min", 1),
    "Pressure":    ("PRESSURE", "bar", 2),
    "Temperature": ("TEMP", u"\u00b0C", 1),
}

# MQTT Engine keeps a live list of which edge nodes are up. Reading this beats
# inferring liveness from tag quality: quality stays Good on the last value an
# offline node sent, which is exactly the case we need to distinguish.
ONLINE_NODES = "[MQTT Engine]Engine Info/Edge Nodes/Online Nodes"

# The historian the trend reads. Created by scripts/sf-historian.sh.
HISTORY_PROVIDER = "Postgres"

DEFAULT_BREAK_SECONDS = 60


def _logger():
    return system.util.getLogger(LOG)


def _because(e):
    """An exception plus its cause chain.

    Ignition wraps every HTTP failure as `IOException: Unable to POST <url>`,
    which is the same message for a refused connection, a rejected protocol and
    a bad request -- the useful part is always underneath.
    """
    parts = [str(e)]
    try:
        cause = e.getCause()
        seen = 0
        while cause is not None and seen < 4:
            parts.append(str(cause))
            cause = cause.getCause()
            seen += 1
    except (Exception, JThrowable):
        pass
    return " <- ".join(parts)




def _now_millis():
    from java.lang import System as JSystem
    return JSystem.currentTimeMillis()


# The page draws three cards from the same snapshot, so a naive implementation
# asks wd-control three times per poll. One second of memo makes a poll one call
# without ever showing state that is meaningfully stale.
_CUT_CACHE = {"at": 0, "value": {}, "error": ""}


def _live_cuts():
    """stack -> milliseconds left, for every MQTT cut wd-control is holding.

    `error` is kept beside it: a control plane that is not answering must not
    be drawn as "nothing is cut", or the Cut button would be live beside a cut
    it cannot see -- the reason is recorded so `can` can say it before the
    click rather than after.
    """
    now = _now_millis()
    if now - _CUT_CACHE["at"] < 1000:
        return _CUT_CACHE["value"]
    import demo_control
    try:
        cuts, why = demo_control.mqtt_cuts()
    except (Exception, JThrowable), e:
        cuts, why = {}, "could not read the MQTT cuts: %s" % str(e)[:60]
    _CUT_CACHE.update(at=now, error=why,
                      value=dict((k, v * 1000) for k, v in cuts.items()))
    return _CUT_CACHE["value"]


# --- who is who ---------------------------------------------------------------

def _resolve(host):
    from java.net import InetAddress
    try:
        return str(InetAddress.getByName(host).getHostAddress())
    except (Exception, JThrowable):
        return ""


def _agent_addresses():
    """EAM agent name -> the address its hostname resolves to.

    gateway_admin.AGENTS already carries each edge's hostname for its status
    ping, so the page and the break button cannot drift apart into two lists.
    """
    out = {}
    for entry in gateway_admin.AGENTS:
        host = entry["ping"].split("//", 1)[-1].split(":", 1)[0]
        address = _resolve(host)
        if address:
            out[entry["agent"]] = {"host": host, "address": address,
                                   "site": entry["site"]}
    return out


def _browse(path):
    try:
        return [str(n["name"]) for n in system.tag.browse(path).getResults()]
    except (Exception, JThrowable), e:
        _logger().warn("browse failed at %r: %s" % (path, e))
        return []


# How stale the newest value may be before an edge counts as not streaming.
# The edges publish once a second; anything past this and something is wrong.
STALE_SECONDS = 12


def _online_nodes():
    """The set of edge node ids MQTT Engine currently considers online.

    Advisory only. The module formats this tag differently depending on how
    many nodes there are, so freshness of the data is the primary test and this
    is a second opinion -- see _is_streaming.
    """
    try:
        qv = system.tag.readBlocking([ONLINE_NODES])[0]
    except (Exception, JThrowable), e:
        _logger().warn("could not read %s: %s" % (ONLINE_NODES, e))
        return set()
    if qv is None or qv.value is None:
        return set()
    text = str(qv.value).strip()
    if not text:
        return set()
    # Comma- or newline-separated depending on count; normalise both, and drop
    # any bracketing a list representation may have picked up.
    parts = [p.strip().strip("[]'\"") for p in text.replace("\n", ",").split(",")]
    return set([p for p in parts if p])


def _is_streaming(node, online, age_seconds):
    """Whether this edge is actually feeding the hub right now.

    Freshness first. Tag QUALITY cannot answer this -- it stays Good on the last
    value an edge sent before it went away, which is exactly the case the page
    has to distinguish, and it is what made an obviously-live pair of edges both
    read OFFLINE on the first build of this page.
    """
    if 0 <= age_seconds <= STALE_SECONDS:
        return True
    return node in online


# --- what the page reads ------------------------------------------------------

# --- breaking the Gateway Network edge -----------------------------------------
#
# The MQTT edge is cut by wd-control, a third party: it is still there to put
# the edge back, and its deadline heals a forgotten cut on its own. The Gateway
# Network edge has no third party -- the link IS the road,
# so the hub cannot both break it and keep the means of putting it back.
#
# So the hub ASKS, over the link, while it is still up: `breakLink` on the edge
# writes a deadline and the edge's own timer drops and restores the connection.
# See edge_link in Styles_Template for why the deadline is a tag.
#
# The consequence is that the hub is BLIND for the duration -- it cannot ask a
# gateway it has just disconnected how long is left. So it remembers the
# deadline itself, in a memory tag rather than a module global, because gateway
# scripts restart on every trial top-up and the countdown would otherwise reset
# to nothing mid-cut.
GAN_DEADLINE_PROVIDER = "[default]"
GAN_DEADLINE_FOLDER = "SF Demo"


def _deadline_tag(agent):
    return "%s%s/%s Cut Until" % (GAN_DEADLINE_PROVIDER, GAN_DEADLINE_FOLDER,
                                 agent)


def _ensure_deadline_tag(agent):
    """Create the folder and the tag, from the provider ROOT.

    Configuring against "[default]SF Demo" directly would need that folder to
    exist already; declaring the folder inline creates both in one call, and
    merge leaves any sibling tag alone.
    """
    if system.tag.exists(_deadline_tag(agent)):
        return
    system.tag.configure(GAN_DEADLINE_PROVIDER, [{
        "name": GAN_DEADLINE_FOLDER,
        "tagType": "Folder",
        "tags": [{
            "name": "%s Cut Until" % agent,
            "tagType": "AtomicTag",
            "valueSource": "memory",
            "dataType": "Int8",
            "value": 0,
        }],
    }], "m")


def _gan_break_remaining(agent):
    """Milliseconds left on a Gateway Network cut, from the hub's own record."""
    path = _deadline_tag(agent)
    try:
        if not system.tag.exists(path):
            return 0
        qv = system.tag.readBlocking([path])[0]
    except (Exception, JThrowable):
        return 0
    if qv is None or qv.value is None:
        return 0
    try:
        return max(0, long(qv.value) - _now_millis())
    except (TypeError, ValueError):
        return 0


def _gan_break(spec, seconds):
    """Ask an edge to cut itself off the Gateway Network for `seconds`.

    The reply comes back before the link goes, because the edge's handler only
    arms the cut -- so a timeout here really does mean the request failed.
    """
    # remoteServer is the GATEWAY NETWORK name, not the EAM agent name. The two
    # differ here only by case ("ignition-edge1" against "Ignition-Edge1"),
    # which is exactly the kind of difference that fails as "server not found"
    # and reads like the edge being offline.
    server = gateway_admin.GAN_SERVERS.get(spec["agent"])
    if not server:
        return "No Gateway Network name known for %s." % spec["site"]

    try:
        message = system.util.sendRequest(
            gateway_admin.EDGE_PROJECT, "breakLink", {"seconds": int(seconds)},
            remoteServer=server, timeoutSec=15)
    except (Exception, JThrowable), e:
        _logger().warn("breakLink to %s failed: %s"
                       % (spec["agent"], _because(e)))
        return "Could not reach %s over the Gateway Network: %s" % (
            spec["site"], _because(e))

    _ensure_deadline_tag(spec["agent"])
    system.tag.writeBlocking([_deadline_tag(spec["agent"])],
                             [_now_millis() + int(seconds) * 1000])
    _logger().info("cut %s off the Gateway Network for %ds (%s)"
                   % (spec["site"], seconds, message))
    return ("Cut %s off the Gateway Network for %d seconds -- it is buffering "
            "now, and will restore itself." % (spec["site"], seconds))


def _read_signals(paths):
    """Values, formatted tiles and the newest timestamp for one edge."""
    try:
        qvs = system.tag.readBlocking(paths)
    except (Exception, JThrowable), e:
        _logger().warn("read failed for %r: %s" % (paths[:1], e))
        return None, [], [], 0

    signals, metrics, newest = [], [], 0
    for name, qv in zip(SF_SIGNALS, qvs):
        # Only a read that CARRIES A VALUE counts towards freshness. A remote
        # tag provider whose gateway has gone away answers with a null value
        # stamped NOW, so counting every read made the cut Gateway Network edge
        # show "LAST VALUE 0s ago" beside three dashes -- the tile contradicting
        # the readings next to it, and the one number on the card that is
        # supposed to be the honest test.
        has_value = qv is not None and qv.value is not None
        stamp = qv.timestamp.getTime() if (has_value and qv.timestamp) else 0
        newest = max(newest, stamp)
        short, unit, places = SIGNAL_META.get(name, (name.upper(), "", 1))
        if not qv or qv.value is None:
            text = "--"
        else:
            text = ("%." + str(places) + "f") % float(qv.value)
        signals.append({"name": name, "value": qv.value if qv else None,
                        "text": text})
        metrics.append({"value": text, "name": short, "unit": unit,
                        "level": "" if text != "--" else "warn"})
    return qvs, signals, metrics, newest


def live_pack(agent):
    """The theme an edge is ACTUALLY wearing, read back from the edge itself.

    The EAM page used to report what the hub last SENT, which is a promise
    rather than an observation: it says nothing about whether the push landed,
    and it cannot notice a theme that changed any other way. `edge_stream`
    publishes the committed pack as a tag, so both roads can now answer this --
    the Gateway Network edge because the hub mounts its provider, the MQTT one
    because its tags are published as Sparkplug metrics.

    Returns "" when it cannot be read, and the caller falls back to the push
    record. Never raises: it feeds a page.
    """
    spec = None
    for t in TRANSPORTS:
        if t["agent"] == agent:
            spec = t
            break
    if spec is None:
        return ""
    try:
        if spec["transport"] == "gan":
            path = "%s/%s" % (spec["root"], PACK_TAG)
        else:
            address = _agent_addresses().get(agent, {}).get("address", "")
            found = _mqtt_node_for(address, _online_nodes(), {})
            if found is None:
                return ""
            path = "%s/%s/%s/%s/%s" % (SF_ROOT, SF_GROUP, found[0],
                                       SF_DEVICE, PACK_TAG)
        qv = system.tag.readBlocking([path])[0]
        # A cut edge answers with a null value stamped NOW, so an absent value
        # is the tell -- not the timestamp, and not the quality.
        if qv is None or qv.value is None:
            return ""
        value = str(qv.value).strip()
        return "" if value in ("", "?") else value
    except (Exception, JThrowable), e:
        _logger().warn("cannot read %s's committed pack: %s" % (agent, e))
        return ""


def _mqtt_node_for(address_wanted, online, cache):
    """The MQTT Engine node whose published Address matches, if any."""
    for node in sorted(_browse("%s/%s" % (SF_ROOT, SF_GROUP))):
        base = "%s/%s/%s/%s" % (SF_ROOT, SF_GROUP, node, SF_DEVICE)
        paths = ["%s/%s" % (base, s) for s in SF_SIGNALS] + \
                ["%s/%s" % (base, ADDRESS_TAG)]
        qvs, signals, metrics, newest = _read_signals(paths[:-1])
        try:
            addr_qv = system.tag.readBlocking([paths[-1]])[0]
        except (Exception, JThrowable):
            addr_qv = None
        address = ""
        if addr_qv is not None and addr_qv.value is not None:
            address = str(addr_qv.value).strip()
        cache[address] = (node, signals, metrics, newest)
    return cache.get(address_wanted)


def nodes():
    """One row per edge, whichever road its data takes to get here.

    Both transports end up in the same shape, so the cards and the trend never
    have to know which is which -- only the `transport` field says, and that is
    there to be SHOWN rather than branched on.
    """
    agents = _agent_addresses()
    cuts = _live_cuts()
    online = _online_nodes()
    mqtt_cache = {}

    rows = []
    for spec in TRANSPORTS:
        info = agents.get(spec["agent"], {})
        address = info.get("address", "")

        if spec["transport"] == "gan":
            paths = ["%s/%s" % (spec["root"], s) for s in SF_SIGNALS]
            qvs, signals, metrics, newest = _read_signals(paths)
            node = spec["agent"]
        else:
            found = _mqtt_node_for(address, online, mqtt_cache)
            if found is None:
                node, signals, metrics, newest = spec["agent"], [], [], 0
            else:
                node, signals, metrics, newest = found

        age = int((_now_millis() - newest) / 1000) if newest else -1
        remaining = cuts.get(spec.get("stack"), 0) if spec["transport"] == "mqtt" \
            else _gan_break_remaining(spec["agent"])
        # Freshness is the only honest test for BOTH roads. Tag quality stays
        # Good on the last value an edge sent before it went away, and the MQTT
        # online list says nothing at all about the Gateway Network one.
        flowing = 0 <= age <= STALE_SECONDS

        rows.append({
            "node": node,
            "address": address,
            "agent": spec["agent"],
            "site": spec["site"],
            "label": spec["site"],
            "transport": spec["transport"],
            "transportLabel": spec["label"],
            "transportShort": spec["short"],
            "transportDetail": spec["detail"],
            "online": flowing,
            "broken": remaining > 0,
            "breakSeconds": int(round(remaining / 1000.0)),
            "state": _state_text(flowing, remaining),
            "stateLevel": _state_level(flowing, remaining),
            "signals": signals,
            "metrics": metrics,
            "signalText": "   ".join(
                ["%s %s" % (m["name"], m["value"]) for m in metrics]),
            "lastData": gateway_admin._fmt(newest) if newest else "--",
            "ageSeconds": age,
        })
    return rows


def _state_text(online, remaining):
    if remaining > 0:
        return "LINK CUT -- %ds" % int(round(remaining / 1000.0))
    return "STREAMING" if online else "OFFLINE"


def _state_level(online, remaining):
    """A word the view turns into a colour, so the palette stays in the styles."""
    if remaining > 0:
        return "bad"
    return "good" if online else "warn"


def _freshness_tile(row):
    """How long since this edge last said anything -- the honest liveness test.

    Three cases, because "no reading" means different things. A cut edge was
    streaming a second ago and has nothing to report only because we took its
    link away; an edge that has never been seen is a different problem, and
    labelling both "nothing yet" makes a working demonstration look broken.
    """
    age = row["ageSeconds"]
    if age >= 0:
        return {"value": "%ds" % age, "name": "LAST VALUE", "unit": "ago",
                "level": "" if row["online"] else "bad"}
    if row["broken"]:
        return {"value": "--", "name": "LAST VALUE",
                "unit": "since the cut", "level": "bad"}
    return {"value": "--", "name": "LAST VALUE", "unit": "nothing yet",
            "level": "bad"}


# summary() reads tags, the broker and the historian, and the page now calls it
# from a dozen bindings rather than three. They all refresh on the same 3s
# expression, so without this they each repeat the same work within milliseconds
# of each other. A TTL well under that interval keeps every binding on one
# consistent snapshot -- which also means the cards and the connectors can never
# disagree about whether an edge is streaming -- while still being "live".
_SUMMARY_CACHE = {"at": 0, "value": None}
SUMMARY_TTL_MILLIS = 1500


def summary():
    """Everything the page draws, shaped as the cards' parameters.

    One function rather than three so the hub card, the edge cards and the
    header line can never disagree about what state the system is in.
    """
    from java.lang import System as JSystem
    now = JSystem.currentTimeMillis()
    if (_SUMMARY_CACHE["value"] is not None
            and (now - _SUMMARY_CACHE["at"]) < SUMMARY_TTL_MILLIS):
        return _SUMMARY_CACHE["value"]
    value = _summary_uncached()
    _SUMMARY_CACHE["at"] = now
    _SUMMARY_CACHE["value"] = value
    return value


def _not_ready():
    """Why the store-and-forward demo cannot be acted on yet, in the control
    plane's words. Lazily imported and never allowed to raise -- see
    gateway_admin._not_ready for the reasoning."""
    try:
        import demo_control
        return demo_control.ready_note("store-forward")
    except (Exception, JThrowable):
        return ""


def _cut_can(row, not_ready):
    """One Cut button. Three refusals, each of them a thing that cannot work.

    A re-click used to silently re-cut and push the deadline out, so the
    remaining time -- which IS computed, and is on the node row beside it --
    disappeared and started again. It is on the button now.
    """
    import demo_action

    site = row["label"]
    gerund = "Cutting %s..." % site
    # The label names the site and nothing else: how long the cut lasts is the
    # dropdown directly above the button, and saying it twice cost every
    # button a second line on a 260px rail.
    label = "Cut " + site
    if not_ready:
        return demo_action.can(False, not_ready, label, gerund, note="")
    if row["broken"]:
        return demo_action.can(
            False, "%s is already cut -- back in %ds"
                   % (site, row["breakSeconds"]),
            label="Cut %s - %ds left" % (site, row["breakSeconds"]),
            busy_label=gerund)
    if not row["online"]:
        return demo_action.can(
            False, "%s is sending nothing to cut" % site, label, gerund)
    if row["transport"] == "mqtt" and _CUT_CACHE.get("error"):
        # The MQTT road is cut BY wd-control, so no wd-control means no cut.
        # The Gateway Network road is cut by the edge itself and does not care.
        return demo_action.can(
            False, str(_CUT_CACHE["error"])[:60], label, gerund)
    return demo_action.can(True, label=label, busy_label=gerund)


def _sf_can(rows, not_ready):
    """Every Store & Forward button, from the same snapshot the cards read."""
    import demo_action

    out = {}
    for index, row in enumerate(rows):
        out["cut%d" % (index + 1)] = _cut_can(row, not_ready)

    cuttable = [k for k in out if out[k]["ok"]]
    if not_ready:
        out["cutBoth"] = demo_action.can(False, not_ready, "Cut both",
                                         "Cutting both...", note="")
    elif not cuttable:
        # Both refusals are already on the two buttons above; this one says
        # which of them applies rather than repeating the longer of the two.
        out["cutBoth"] = demo_action.can(
            False, "neither edge can be cut just now", "Cut both",
            "Cutting both...")
    else:
        out["cutBoth"] = demo_action.can(True, label="Cut both",
                                         busy_label="Cutting both...")

    # RESTORE IS ONLY HALF POSSIBLE, ALWAYS. A Gateway Network cut cannot be
    # lifted from the hub -- the request would travel over the link it just cut
    # -- and restore_link() has said so in words for months. The button now
    # refuses instead of reporting a success it cannot deliver.
    mqtt_cut = [r for r in rows if r["broken"] and r["transport"] == "mqtt"]
    gan_cut = [r for r in rows if r["broken"] and r["transport"] == "gan"]
    # Refusals are ONE clause (the console's text budget, 21/09/2026). The
    # reason a Gateway Network cut cannot be lifted from here -- the request
    # would travel over the very link that was cut -- is in
    # docs/STORE-FORWARD.md, and was a 150-character tooltip nobody finished.
    if not_ready:
        # The banner already says why; "nothing is cut off" under a demo that
        # is not even running is a true sentence about the wrong question.
        out["restore"] = demo_action.can(False, not_ready, "Restore now",
                                         "Restoring...", note="")
    elif mqtt_cut:
        out["restore"] = demo_action.can(
            True, label="Restore now", busy_label="Restoring...",
            note=("%s comes back by itself in %ds"
                  % (gan_cut[0]["label"], gan_cut[0]["breakSeconds"]))
            if gan_cut else "")
    elif gan_cut:
        out["restore"] = demo_action.can(
            False, "%s comes back by itself in %ds"
                   % (gan_cut[0]["label"], gan_cut[0]["breakSeconds"]),
            label="Restore now", busy_label="Restoring...")
    else:
        out["restore"] = demo_action.can(
            False, "nothing is cut off", label="Restore now",
            busy_label="Restoring...")
    return out


def guards():
    """`summary().can` for the view to bind, and never an exception.

    The tab's four buttons bind their enabled state to this, so a transform
    that raised would draw them all with no enabled state at all -- the very
    defect being fixed -- and log nothing, because a Perspective transform
    reports its failure to the browser only.
    """
    import demo_action
    try:
        snap = summary()
        return {"can": snap["can"], "notReady": snap["notReady"]}
    except (Exception, JThrowable), e:
        _logger().warn("store-and-forward guards failed: %s" % e)
        blocked = demo_action.can(
            False, "the console cannot read the edges' state: %s" % str(e)[:70])
        return {"can": dict((k, blocked) for k in
                            ("cut1", "cut2", "cutBoth", "restore")),
                "notReady": ""}


def _summary_uncached():
    not_ready = _not_ready()
    rows = nodes()
    broken = [r for r in rows if r["broken"]]
    streaming = [r for r in rows if r["online"] and not r["broken"]]

    if broken:
        hub_state, hub_level = "BUFFERING UPSTREAM", "warn"
    elif streaming:
        hub_state, hub_level = "RECORDING", "good"
    else:
        hub_state, hub_level = "NO DATA", "warn"

    return {
        "hub": {
            "label": "Ignition-Standard",
            "sublabel": "Hub - MQTT Engine and historian",
            "icon": "standard",
            "state": hub_state,
            "stateLevel": hub_level,
            "state2": "",
            "state2Level": "good",
            "metrics": [
                {"value": "%d/%d" % (len(streaming), len(rows)),
                 "name": "EDGES", "unit": "streaming",
                 "level": "" if len(streaming) == len(rows) else "warn"},
                {"value": str(len(broken)), "name": "CUT", "unit": "buffering",
                 "level": "bad" if broken else ""},
                {"value": str(len(rows) * len(SF_SIGNALS)),
                 "name": "HISTORISED", "unit": "to %s" % HISTORY_PROVIDER,
                 "level": ""},
            ],
            "signalText": "%d of %d edges streaming" % (len(streaming), len(rows)),
            # No footer. It listed each edge against its road -- which is now
            # written ON the connector line that draws that road, directly
            # below this card. Saying it twice cost a row of card height for
            # nothing, and the height is what the trend needs.
            "footer": "",
        },
        "edges": [{
            "label": r["label"],
            # The road and the freshness now live on the CONNECTOR, because the
            # road is the line -- see connector(). Stating them here as well put
            # the one thing that differs between the two edges in the one place
            # you have to read rather than see, and left both cards looking the
            # same at a glance.
            "sublabel": "",
            "icon": "edge",
            "state": r["state"],
            "stateLevel": r["stateLevel"],
            "state2": r["transportLabel"],
            "state2Level": "good" if r["online"] else "warn",
            "metrics": r["metrics"] + [_freshness_tile(r)],
            "signalText": r["signalText"],
            # Also on the connector now. (When it was here it read r["node"],
            # which is whatever identifies the edge on its OWN road -- the
            # gateway name for the Gateway Network one, but a GENERATED Sparkplug
            # id for the other, so the second card was captioned "Edge Node
            # 8e21af" and looked like an edge nobody had named.)
            "footer": "",
        } for r in rows],
        "rows": rows,
        "total": len(rows),
        "online": len(streaming),
        "broken": len(broken),
        "anyBroken": len(broken) > 0,
        # The buttons, from the same snapshot as the cards -- so a Cut button
        # can never be live beside a card that says the edge is already cut.
        "can": _sf_can(rows, not_ready),
        # One banner rather than the same sentence on four buttons -- see the
        # note in demo_action.can about what `note` is for.
        "notReady": not_ready,
        "text": "%d of %d edges streaming%s" % (
            len(streaming), len(rows),
            (", %d cut off and buffering" % len(broken)) if broken else ""),
    }


def _words(state):
    """"LINK CUT -- 42s" -> "Link cut, 42s". The card shouted in capitals; a
    strip box sits beside a rail that does not, and one tab speaking in two
    registers is the inconsistency the shared rail exists to remove."""
    text = str(state or "").replace(" -- ", ", ")
    return text[:1].upper() + text[1:].lower()


def connector(index):
    """Parameters for the line drawn between the hub and one edge.

    WHICH ROAD an edge takes is the entire point of this page, and it used to be
    stated only as text on the edge's own card -- so the two roads looked
    identical and the difference had to be read rather than seen. The line is
    where that belongs: it is the road.

    `flowing` drives the animation, and it is deliberately the same test the
    card's state uses rather than a second opinion. Freshness is the only honest
    signal for BOTH roads: tag quality stays Good on the last value an edge sent
    before it vanished, and the MQTT online list says nothing at all about the
    Gateway Network edge.
    """
    rows = summary()["rows"]
    try:
        r = rows[int(index)]
    except (IndexError, ValueError):
        return {"transport": "", "flowing": False, "label": "",
                "detail": "", "footer": ""}
    return {
        "transport": r["transport"],
        "flowing": bool(r["online"]) and not r["broken"],
        "label": r["transportLabel"],
        "detail": r["transportDetail"],
        "footer": "%s   last data %s" % (r["agent"], r["lastData"]),
    }


def conn_classes(index):
    """Style classes for the LINE between the hub and one edge.

    Returned as a string rather than assembled in an expression because the
    class names encode a decision -- which road, and whether it is moving -- and
    that decision belongs beside the data it is made from.
    """
    c = connector(index)
    if not c["transport"]:
        return "wd-conn wd-conn--stalled"
    return "wd-conn wd-conn--%s wd-conn--%s" % (
        c["transport"], "flowing" if c["flowing"] else "stalled")


def conn_chip_classes(index):
    """Style classes for the label that sits IN the line."""
    c = connector(index)
    if not c["transport"] or not c["flowing"]:
        return "wd-conn-chip wd-conn-chip--stalled"
    return "wd-conn-chip wd-conn-chip--%s" % c["transport"]


def conn_text(index, which):
    """One of the connector's three lines of text."""
    return connector(index).get(which, "")


def card(which):
    """One card's parameters. `which` is 'hub', or a 0-based edge index."""
    data = summary()
    if which == "hub":
        return data["hub"]
    try:
        return data["edges"][int(which)]
    except (IndexError, ValueError):
        return {"label": "Edge", "sublabel": "", "icon": "edge",
                "state": "NOT SEEN", "stateLevel": "warn",
                "metrics": [{"value": "--", "name": name, "unit": ""}
                            for name, _, _ in
                            [SIGNAL_META[s] for s in SF_SIGNALS]],
                "signalText": "no Sparkplug birth from this edge yet",
                "footer": ""}


# --- breaking and restoring ---------------------------------------------------

def _spec_for(target):
    """The transport record for an agent, site or label."""
    target = str(target or "").strip()
    for spec in TRANSPORTS:
        if target in (spec["agent"], spec["site"], spec["label"]):
            return spec
    return None


def _mqtt_spec(target):
    """The MQTT transport record for an agent, site, label or address."""
    spec = _spec_for(target)
    if spec is None:
        for row in nodes():
            if str(target or "").strip() in (row["address"], row["node"]):
                spec = _spec_for(row["agent"])
                break
    return spec if spec and spec["transport"] == "mqtt" else None


def break_link(target, seconds=DEFAULT_BREAK_SECONDS):
    """Cut one edge off its road for `seconds`.

    `target` is an EAM agent name, a site name, or an address -- whichever the
    button has to hand. The MQTT edge is taken off `wd-mqtt` by wd-control; the
    Gateway Network edge cuts itself (_gan_break).
    """
    spec = _spec_for(target)
    if spec and spec["transport"] == "gan":
        return _gan_break(spec, seconds)
    spec = _mqtt_spec(target)
    if spec is None:
        return "%s is not an edge this page can cut." % target
    import demo_control
    ok, why = demo_control.mqtt_cut(spec["stack"], seconds)
    _CUT_CACHE["at"] = 0
    if not ok:
        return "Could not cut %s: %s" % (spec["site"], why)
    _logger().info("cut %s (%s) off the broker for %ds"
                   % (spec["site"], spec["stack"], seconds))
    return ("Cut %s off the broker for %d seconds -- it is buffering now. The "
            "cloud notices in about 15 s, when the broker gives up on it."
            % (spec["site"], seconds))


def restore_link(target):
    """Put the MQTT edge back early. It reconnects within a few seconds."""
    spec = _spec_for(target)
    if spec and spec["transport"] == "gan":
        # Not a missing feature -- an unreachable one. Restoring means asking
        # the edge, and the request would travel over the link we just cut. The
        # edge is holding the deadline and will restore itself; saying so is
        # better than a button that reports success and does nothing.
        left = int(round(_gan_break_remaining(spec["agent"]) / 1000.0))
        if left <= 0:
            return "%s is already back on the Gateway Network." % spec["site"]
        return ("%s restores itself in %ds. The hub cannot lift a Gateway "
                "Network cut early -- the request would have to travel over "
                "the link it just cut." % (spec["site"], left))
    spec = _mqtt_spec(target)
    if spec is None:
        return "%s is not an edge this page can restore." % target
    import demo_control
    ok, why = demo_control.mqtt_restore(spec["stack"])
    _CUT_CACHE["at"] = 0
    if not ok:
        return "Could not restore %s: %s" % (spec["site"], why)
    _logger().info("restored %s (%s)" % (spec["site"], spec["stack"]))
    return "%s restored -- buffered data is on its way up." % spec["site"]


def break_all(seconds=DEFAULT_BREAK_SECONDS):
    """Cut every edge at once, each by its own road. One sentence back."""
    failures, cut = [], []
    for spec in TRANSPORTS:
        message = break_link(spec["agent"], seconds)
        if message.startswith("Cut "):
            cut.append(spec["site"])
        else:
            failures.append(message)
    if failures:
        return " ".join(failures)
    if not cut:
        return "No edge on this page can be cut."
    return ("Cut %s off for %d seconds -- both buffering now. Each comes back "
            "by itself when its time runs out." % (" and ".join(cut), seconds))


def restore_all():
    """Put back every MQTT edge on this page that is cut.

    Only the MQTT road can be restored from here; the Gateway Network edge
    holds its own deadline and is out of reach until it lifts it. Reported
    rather than glossed over, so the page never claims to have done something
    it cannot do.
    """
    import demo_control
    lifted, failures = 0, []
    live = _live_cuts()
    for spec in TRANSPORTS:
        if spec["transport"] != "mqtt" or spec["stack"] not in live:
            continue
        ok, why = demo_control.mqtt_restore(spec["stack"])
        if ok:
            lifted += 1
        else:
            failures.append("Could not restore %s: %s." % (spec["site"], why))
    _CUT_CACHE["at"] = 0

    waiting = []
    for spec in TRANSPORTS:
        if spec["transport"] != "gan":
            continue
        left = int(round(_gan_break_remaining(spec["agent"]) / 1000.0))
        if left > 0:
            waiting.append("%s restores itself in %ds" % (spec["site"], left))

    if not lifted and not waiting and not failures:
        return "Nothing is cut off."
    parts = list(failures)
    if lifted:
        parts.append("Restored %d edge%s -- buffered data is on its way up."
                     % (lifted, "" if lifted == 1 else "s"))
    parts.extend([w + "." for w in waiting])
    return " ".join(parts)


# --- history ------------------------------------------------------------------

def ensure_history():
    """Turn on tag history for the Demo signals, idempotently.

    MQTT Engine recreates its tags whenever an edge sends a fresh birth
    certificate, and a recreated tag comes back with history off -- so this is
    re-applied rather than done once. Only tags that are actually missing it are
    written, so the usual case costs a read.

    Backfill lands correctly because Engine has `storeHistoricalEvents` on: a
    Sparkplug metric flagged historical goes to the historian carrying its
    ORIGINAL timestamp instead of updating the live value. That is the whole
    reason the trend fills its own gap in.
    """
    configured = 0
    for node in _browse("%s/%s" % (SF_ROOT, SF_GROUP)):
        for signal in SF_SIGNALS:
            path = "%s/%s/%s/%s/%s" % (SF_ROOT, SF_GROUP, node, SF_DEVICE, signal)
            try:
                current = system.tag.getConfiguration(path, False)
                if current and current[0].get("historyEnabled"):
                    continue
                system.tag.configure(
                    "%s/%s/%s/%s" % (SF_ROOT, SF_GROUP, node, SF_DEVICE),
                    [{"name": signal,
                      "historyEnabled": True,
                      "historyProvider": HISTORY_PROVIDER}],
                    "m")
                configured += 1
            except (Exception, JThrowable), e:
                _logger().warn("could not historise %s: %s" % (path, e))
    if configured:
        _logger().info("enabled history on %d tag(s)" % configured)
    return configured


# --- the trend ----------------------------------------------------------------

# One signal, not three. The chart has to make a single point -- this edge went
# quiet and then caught up -- and six lines bury it.
TREND_SIGNAL = "FlowRate"

# ia.chart.xy parses a date axis with a format string; this is the one the view
# sets as inputFormat. HH rather than the schema default kk, which is 1-24 and
# turns midnight into hour 24.
TREND_STAMP = "yyyy-MM-dd HH:mm:ss"

# The chart is drawn on a FIXED GRID rather than from raw samples, and that is
# not cosmetic -- without it the demonstration lies.
#
# `connect: false` breaks the line at an empty data point, but the break that
# actually bit us is amCharts' own: a line segment is dropped whenever two
# points sit more than ~1.1 x the date axis's BASE INTERVAL apart. The axis here
# declares a base interval of one second, and the historian delivers 1s samples
# 1-3s apart, so a perfectly healthy pair of lines came back speckled with
# dozens of breaks -- indistinguishable at a glance from the one break that
# matters, and on screen while nothing was cut at all.
#
# So STEP MUST MATCH THE AXIS BASE INTERVAL. Resampling onto a 2s grid looked
# tidier and rendered NOTHING: every segment was then 2x the base interval, so
# every segment was dropped, and the chart came up blank with its axes still
# ranged correctly off the data -- which reads exactly like a binding returning
# nothing. Change one and change the other.
#
# GAP is deliberately just above the worst jitter measured here (3.0s) and far
# below the shortest cut the page offers (60s), so it cannot confuse the two.
TREND_STEP_SECONDS = 1
TREND_GAP_SECONDS = 6


def _history_path(row, signal):
    """Where the hub's historian filed one signal, for whichever road it took.

    The two roads do NOT share a path shape, and using the live tag path for
    both is the trap: it works for the MQTT edge, whose tags the hub historises
    itself, and quietly returns nothing for the Gateway Network edge, whose tags
    are not the hub's at all. Postgres shows them under a second driver row --
    `sqlth_drv` gains (ignition-edge1, edge) alongside (ignition-standard, mqtt
    engine) -- so the query has to name that driver explicitly:

        histprov:<historian>:/drv:<source gateway>:<source provider>:/tag:<path>

    Worse than an error, the live path fails SILENTLY: queryTagHistory returns
    an empty result and the chart draws one line where two were expected, which
    reads exactly like an edge that is not sending.

    The MQTT edge keeps the live path, which is equivalent for a locally
    historised tag and stays readable.
    """
    spec = _spec_for(row.get("agent"))
    if spec and spec.get("historyDriver"):
        gateway, provider = spec["historyDriver"]
        return "histprov:%s:/drv:%s:%s:/tag:%s/%s" % (
            HISTORY_PROVIDER, gateway, provider, spec["historyRoot"], signal)
    return "%s/%s/%s/%s/%s" % (SF_ROOT, SF_GROUP, row["node"],
                               SF_DEVICE, signal)


def _grid(samples, start, end):
    """Raw (millis, value) samples -> one point per TREND_STEP_SECONDS.

    A bucket takes the newest sample that falls in it. An empty bucket carries
    the previous value forward while the hole is short enough to be delivery
    jitter, and becomes None once it is long enough to be an outage -- which is
    what breaks the line under `connect: false`.

    Carrying forward is safe at this resolution and is NOT the interpolation
    this file used to warn against: it spans at most TREND_GAP_SECONDS, where
    interpolating across a real outage would draw a straight line through the
    thing the page exists to show.
    """
    step = TREND_STEP_SECONDS * 1000
    tolerance = max(1, TREND_GAP_SECONDS // TREND_STEP_SECONDS)

    total = int((end - start) // step) + 1
    values = [None] * total
    for stamp, value in samples:
        index = int((stamp - start) // step)
        if 0 <= index < total:
            values[index] = value

    # Bridge short holes by interpolating between the samples either side.
    # Carrying the previous value forward instead leaves visible stair-steps on
    # a smooth signal -- small, but they read as data rather than as the
    # rendering artefact they are.
    index = 0
    while index < total:
        if values[index] is not None:
            index += 1
            continue
        run_end = index
        while run_end < total and values[run_end] is None:
            run_end += 1
        run = run_end - index
        if run <= tolerance and index > 0 and run_end < total:
            before, after = values[index - 1], values[run_end]
            for k in range(run):
                values[index + k] = round(
                    before + (after - before) * (k + 1.0) / (run + 1), 2)
        index = run_end

    # OMIT an outage bucket rather than emitting a null. A null `v` makes
    # ia.chart.xy draw NOTHING AT ALL -- not a broken line, the whole series
    # vanishes while the axes still range correctly off the data, which reads
    # exactly like a binding that returned nothing. Leaving the point out lets
    # amCharts' own gap detection break the line, and with every remaining point
    # exactly one base interval from its neighbour, a real hole is the only
    # distance it can ever see.
    points = []
    for index in range(total):
        if values[index] is None:
            continue
        points.append({
            "t": system.date.format(system.date.fromMillis(start + index * step),
                                    TREND_STAMP),
            "v": values[index],
        })
    return points


def trend(minutes=10):
    """One data source per edge, for the XY chart's date axis.

    Queried per edge rather than as one wide result, because the demonstration
    lives in the GAPS: a wide query interleaves both edges' timestamps and fills
    the other column with nulls, so with `connect: false` both lines end up
    dashed and neither outage is visible. Separate sources keep each line solid
    except where that edge really has nothing.

    The samples are then laid on an even grid -- see TREND_STEP_SECONDS -- so the
    only breaks in the drawn line are outages rather than delivery jitter.
    """
    from java.util import Date

    end = _now_millis()
    start = end - int(minutes) * 60 * 1000
    sources = {}
    for index, row in enumerate(summary()["rows"][:2]):
        key = "edge%d" % (index + 1)
        path = _history_path(row, TREND_SIGNAL)
        samples = []
        try:
            data = system.tag.queryTagHistory(
                paths=[path], startDate=Date(start), endDate=Date(end),
                returnSize=-1, returnFormat="Wide",
                noInterpolation=True, includeBoundingValues=False)
            for r in range(data.getRowCount()):
                value = data.getValueAt(r, 1)
                if value is None:
                    continue
                samples.append((data.getValueAt(r, 0).getTime(),
                                round(float(value), 2)))
        except (Exception, JThrowable), e:
            _logger().warn("history query failed for %s: %s" % (path, e))
        sources[key] = _grid(samples, start, end) if samples else []
    # The chart's series are declared statically, so a missing edge has to come
    # back as an empty list rather than a missing key.
    for index in (1, 2):
        sources.setdefault("edge%d" % index, [])
    return sources


def trend_names():
    """Series labels, so the legend says Site 1 rather than edge1."""
    rows = summary()["rows"][:2]
    names = {}
    for index, row in enumerate(rows):
        names["edge%d" % (index + 1)] = "%s  %s" % (row["label"], TREND_SIGNAL)
    for index in (1, 2):
        names.setdefault("edge%d" % index, "Edge %d" % index)
    return names
